### ISSUE TITLE
Build: bazel build failed in network filters

### ISSUE THREAD

**Issue by popozy** [envoyproxy/envoy#10552]
*Description*:
I meet the similar error about kafka networkfilter when building envoy-wasm:
the Traceback :
``` shell
ERROR: /home/envoy/source/extensions/filters/network/kafka/BUILD:163:1: Executing genrule //source/extensions/filters/network/kafka:kafka_response_generated_source failed (Exit 1) linux-sandbox failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy && \
  exec env - \
    BAZEL_COMPILER=clang \
    BAZEL_CXXOPTS='-stdlib=libc++' \
    BAZEL_LINKLIBS=-l%:libc++.a:-l%:libc++abi.a:-lm \
    BAZEL_LINKOPTS=-lm \
    CC=/root/package/llvm-project/build/bin/clang \
    CXX=/root/package/llvm-project/build/bin/clang++ \
    CXXFLAGS='-stdlib=libc++ -Wno-error' \
    LDFLAGS='-stdlib=libc++' \
    PATH=/root/package/llvm-project/build/bin:/root/package/z3-master/build:/root/package/gn/out:/root/package/llvm-project/build/bin:/usr/local/java/bin:/root/apache-ant-1.9.14/bin:/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/c435ff35b78e9d78b94f06dd7301a644/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy -w /tmp -w /dev/shm -D -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
      ./bazel-out/host/bin/source/extensions/filters/network/kafka/kafka_protocol_code_generator_bin response         bazel-out/aarch64-fastbuild/bin/source/extensions/filters/network/kafka/external/responses.h bazel-out/aarch64-fastbuild/bin/source/extensions/filters/network/kafka/external/kafka_response_resolver.cc         bazel-out/aarch64-fastbuild/bin/source/extensions/filters/network/kafka/external/response_metrics.h external/kafka_source/AddOffsetsToTxnResponse.json external/kafka_source/AddPartitionsToTxnResponse.json external/kafka_source/AlterConfigsResponse.json external/kafka_source/AlterReplicaLogDirsResponse.json external/kafka_source/ApiVersionsResponse.json external/kafka_source/ControlledShutdownResponse.json external/kafka_source/CreateAclsResponse.json external/kafka_source/CreateDelegationTokenResponse.json external/kafka_source/CreatePartitionsResponse.json external/kafka_source/CreateTopicsResponse.json external/kafka_source/DeleteAclsResponse.json external/kafka_source/DeleteGroupsResponse.json external/kafka_source/DeleteRecordsResponse.json external/kafka_source/DeleteTopicsResponse.json external/kafka_source/DescribeAclsResponse.json external/kafka_source/DescribeConfigsResponse.json external/kafka_source/DescribeDelegationTokenResponse.json external/kafka_source/DescribeGroupsResponse.json external/kafka_source/DescribeLogDirsResponse.json external/kafka_source/ElectPreferredLeadersResponse.json external/kafka_source/EndTxnResponse.json external/kafka_source/ExpireDelegationTokenResponse.json external/kafka_source/FetchResponse.json external/kafka_source/FindCoordinatorResponse.json external/kafka_source/HeartbeatResponse.json external/kafka_source/InitProducerIdResponse.json external/kafka_source/JoinGroupResponse.json external/kafka_source/LeaderAndIsrResponse.json external/kafka_source/LeaveGroupResponse.json external/kafka_source/ListGroupsResponse.json external/kafka_source/ListOffsetResponse.json external/kafka_source/MetadataResponse.json external/kafka_source/OffsetCommitResponse.json external/kafka_source/OffsetFetchResponse.json external/kafka_source/OffsetForLeaderEpochResponse.json external/kafka_source/ProduceResponse.json external/kafka_source/RenewDelegationTokenResponse.json external/kafka_source/SaslAuthenticateResponse.json external/kafka_source/SaslHandshakeResponse.json external/kafka_source/StopReplicaResponse.json external/kafka_source/SyncGroupResponse.json external/kafka_source/TxnOffsetCommitResponse.json external/kafka_source/UpdateMetadataResponse.json external/kafka_source/WriteTxnMarkersResponse.json
    ')
src/main/tools/linux-sandbox.cc:154: linux-sandbox-pid1 has PID 41442
src/main/tools/linux-sandbox-pid1.cc:175: working dir: /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy
src/main/tools/linux-sandbox-pid1.cc:194: writable: /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy
src/main/tools/linux-sandbox-pid1.cc:194: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:194: writable: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/unified
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/perf_event
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/freezer
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/devices
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/blkio
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/cpuset
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/net_cls,net_prio
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/cpu,cpuacct
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/pids
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/rdma
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/hugetlb
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/memory
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/files
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/firmware/efi/efivars
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/bpf
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/config
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/selinux
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/debug/tracing
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/pts
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/mqueue
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/hugepages
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/user/0
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/docker/netns/default
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/docker/netns/7912a705dc8e
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/docker/netns/8de312ce079f
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /tmp
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /boot
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /boot/efi
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /home
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/6135834168a8967c7a299bab30ca5c8638ed884742446dc3331cb063d9daca87/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/7a79decb12df183f59d27058948b08a966de1596ee1a31d7a8175779811751c8/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/7a2adc7cd48411cd44fbff1b49b442ae952b524a2431e8394dceb2e0ab0f9165/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/6aab83cc6f4bac9784f9c612df26334689b5cfba7419dfd0a429841ee88696f0/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/24f76977d44136beaa6ebda7d434eccf07fbe778e9445e3487551bbf60e6b8ac/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/3745919e34b650efd7f26629991d87447077016ea438c413e4ef005959fe3869/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/f455cacc3201749b47c103b7a1b7956feeeb32e4c07de2ba91087325dc413077/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/f59767aa73ec238bbeedbae48f6e6d7c9658e653a8e5ed38d5a6540e69d35935/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/206a9e10f13da9affccb3e3bb04881700aafc7a51db48529f4776970e6a9ae1c/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/dce139f77992c441dadba23ea4a9cc31b94527da5777900230dcc86fa148f8e4/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/kubelet/pods/f073bc69-7bc9-4eb0-bb20-e59610de5582/volumes/kubernetes.io~secret/kube-proxy-token-glz8h
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/b01849df3f098c38ac624d8af239ce0f6200890a90dc5a65220d5323442614b4/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/79e23dcccb97442cf1a023c723e85656c8f5f7407ac9c58046090b98ff1d9d10/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/b7836c251e76c584a02a7f8d4311ca153c0e8e0d72cab4aba8567d53f8c43097/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/kubelet/pods/b2635cb2-f456-477a-bd92-ef9b4682594f/volumes/kubernetes.io~secret/coredns-token-fbhpn
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/kubelet/pods/7f14ae8a-afd7-40ed-8c67-405771945efd/volumes/kubernetes.io~secret/coredns-token-fbhpn
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/44ecff368b1fe24996206e1c51b8d650890b3317b601b0071b1a6454834db94a/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/0383551dce51a4bfb933e7f1a6a696716f5b7d595507d1ebab585a3442eb370c/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/b0d18cdb44f5d0cc5284e912ed813a9ee4725a4caf0b7136021a5d70eb7c5c53/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/f634fd7eafdb1bc7ffac7634ab379f6d855e64008f224757c3de36966230d745/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/e652c19d5bbca5d4e3d747cd9d560c708d028424be6fbebb6985dd1679c83ddf/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/b8ae91411cf489656383832991963c1db9d1bbf173b007e1424606f125a51f61/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/a68f97687f416152764fb424bd3ba1f2afce9482d7130f6be4ab62e6bffa7750/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/616c06f65c3d6eac91a97f306eadffea21259d684ccfbbf01811871660836f32/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/kubelet/pods/505687f8-e9d6-4a30-b82f-0202323f4501/volumes/kubernetes.io~secret/flannel-token-5s972
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/fe8e8f9bcca512bab7328e60611cd0e0bed754f9111be9421b1fb6220e23b059/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/containers/059c64b94697667fc91786c31ce8191435299d3ce9ef93947d4c1241a5c4ed66/mounts/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /var/lib/docker/overlay2/ed397cbd523fc80a27f7e57a6cb6818c392f8d897097ad76d27db09f893a67c4/merged
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /tmp
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /dev/shm
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
Traceback (most recent call last):
  File "./bazel-out/host/bin/source/extensions/filters/network/kafka/kafka_protocol_code_generator_bin", line 349, in <module>
    Main()
  File "./bazel-out/host/bin/source/extensions/filters/network/kafka/kafka_protocol_code_generator_bin", line 303, in Main
    'Cannot exec() %r: file not found.' % main_filename
AssertionError: Cannot exec() '/root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy/./bazel-out/host/bin/source/extensions/filters/network/kafka/kafka_protocol_code_generator_bin.runfiles/envoy/source/extensions/filters/network/kafka/protocol/launcher.py': file not found.
```
It seems like launcher.py not found, however I found the file
``` shell
[root@localhost envoy]# ll /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy/./bazel-out/host/bin/source/extensions/filters/network/kafka/kafka_protocol_code_generator_bin.runfiles/envoy/source/extensions/filters/network/kafka/protocol/launcher.py
lrwxrwxrwx. 1 root root 139 Mar 27 09:48 /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/sandbox/linux-sandbox/200/execroot/envoy/./bazel-out/host/bin/source/extensions/filters/network/kafka/kafka_protocol_code_generator_bin.runfiles/envoy/source/extensions/filters/network/kafka/protocol/launcher.py -> /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/execroot/envoy/source/extensions/filters/network/kafka/protocol/launcher.py
[root@localhost envoy]# ll /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/execroot/envoy/source/extensions/filters/network/kafka/protocol/launcher.py
-rw-------. 1 root root 1836 Mar 26 17:03 /root/.cache/bazel/_bazel_root/9705b42e78be2f32cf7e0ddc5f30c7bd/execroot/envoy/source/extensions/filters/network/kafka/protocol/launcher.py
```
Any idea for what can I do to make it, buddies? ：）
And it seems like envoyproxy/envoy#7082 , but no useful information can help me: (

**Comment by popozy** [comment]
Enviroment:
+ PATH=/root/package/llvm-project/build/bin:/root/package/z3-master/build:/root/package/gn/out:/root/package/llvm-project/build/bin:/usr/local/java/bin:/root/apache-ant-1.9.14/bin:/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
+ clang++:
lang version 8.0.1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/package/llvm-project/build/bin
+ clang:
clang version 8.0.1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/package/llvm-project/build/bin

**Comment by orangeji11** [comment]
@popozy hi,i meet this question,too.
Have you solved it？

**Comment by popozy** [comment]
> @popozy hi,i meet this question,too.
> Have you solved it？

pity for us, I didn't found a effective solution to solve it. I found that the proposal to support envoy project on arm arch. was  not an urgent thing.

**Comment by nickolaev** [comment]
On ubuntu 20.04 I had to install `python-is-python3` for a similar problem. Might not be related though.
