### ISSUE TITLE
Bazel will not start

### ISSUE THREAD

**Issue by Barborica-Alexandru** [envoyproxy/envoy#10817]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: Bazel will no longer start

*Description*:
When trying to build the most recent version of envoy I keep getting the following error. Fresh debian container, fresh fedora container, same result.

Problem is only in LXC containers I have discovered. Compiles just fine on bare metal.

I realise that this is not an envoy issue, but I have no idea where else to post it.

*Logs*:
```
ERROR: bazel crash in async thread:
java.lang.IllegalArgumentException: Multiple entries with same key: Writeback=264 and Writeback=264
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
        at com.google.devtools.build.lib.unix.ProcMeminfoParser.<init>(ProcMeminfoParser.java:62)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getMemoryInMbHelper(LocalHostResourceManagerLinux.java:86)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getMemoryInMb(LocalHostResourceManagerLinux.java:40)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getLocalHostResources(LocalHostResourceManagerLinux.java:46)
        at com.google.devtools.build.lib.actions.LocalHostCapacity.getNewLocalHostCapacity(LocalHostCapacity.java:46)
        at com.google.devtools.build.lib.actions.LocalHostCapacity.getLocalHostCapacity(LocalHostCapacity.java:34)
        at com.google.devtools.build.lib.buildtool.BuildRequestOptions$JobsConverter.lambda$new$0(BuildRequestOptions.java:465)
        at com.google.devtools.build.lib.util.ResourceConverter.applyOperator(ResourceConverter.java:136)
        at com.google.devtools.build.lib.util.ResourceConverter.convert(ResourceConverter.java:122)
        at com.google.devtools.build.lib.util.ResourceConverter.convert(ResourceConverter.java:41)
        at com.google.devtools.common.options.OptionDefinition.getDefaultValue(OptionDefinition.java:270)
        at com.google.devtools.common.options.OptionValueDescription$DefaultOptionValueDescription.getValue(OptionValueDescription.java:123)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:378)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:325)
        at com.google.devtools.common.options.OptionsParser.parseWithSourceFunction(OptionsParser.java:642)
        at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseArgsAndConfigs(BlazeOptionHandler.java:207)
        at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseOptions(BlazeOptionHandler.java:274)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:275)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by yanavlasov** [comment]
@lizan did you ever see something like this?
@Barborica-Alexandru you can ask on bazel slack https://slack.bazel.build/

**Comment by lizan** [comment]
No, which version of bazel are you running? can you paste a full log?

**Comment by Barborica-Alexandru** [comment]
I'm running bazelisk and when compiling envoy it downloads bazel-3.0.0. But it's not bazel, i tried multiple versions going back to 2.2.0, none of them work in LXC anymore.
Full log (not much to see it instantly crashes):
```
java.lang.IllegalArgumentException: Multiple entries with same key: Writeback=924 and Writeback=924
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
        at com.google.devtools.build.lib.unix.ProcMeminfoParser.<init>(ProcMeminfoParser.java:62)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getMemoryInMbHelper(LocalHostResourceManagerLinux.java:86)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getMemoryInMb(LocalHostResourceManagerLinux.java:40)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getLocalHostResources(LocalHostResourceManagerLinux.java:46)
        at com.google.devtools.build.lib.actions.LocalHostCapacity.getNewLocalHostCapacity(LocalHostCapacity.java:46)
        at com.google.devtools.build.lib.actions.LocalHostCapacity.getLocalHostCapacity(LocalHostCapacity.java:34)
        at com.google.devtools.build.lib.buildtool.BuildRequestOptions$JobsConverter.lambda$new$0(BuildRequestOptions.java:465)
        at com.google.devtools.build.lib.util.ResourceConverter.applyOperator(ResourceConverter.java:136)
        at com.google.devtools.build.lib.util.ResourceConverter.convert(ResourceConverter.java:122)
        at com.google.devtools.build.lib.util.ResourceConverter.convert(ResourceConverter.java:41)
        at com.google.devtools.common.options.OptionDefinition.getDefaultValue(OptionDefinition.java:270)
        at com.google.devtools.common.options.OptionValueDescription$DefaultOptionValueDescription.getValue(OptionValueDescription.java:123)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:378)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:325)
        at com.google.devtools.common.options.OptionsParser.parseWithSourceFunction(OptionsParser.java:642)
        at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseArgsAndConfigs(BlazeOptionHandler.java:207)
        at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseOptions(BlazeOptionHandler.java:274)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:275)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
ERROR: bazel crash in async thread:
java.lang.IllegalArgumentException: Multiple entries with same key: Writeback=924 and Writeback=924
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
        at com.google.devtools.build.lib.unix.ProcMeminfoParser.<init>(ProcMeminfoParser.java:62)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getMemoryInMbHelper(LocalHostResourceManagerLinux.java:86)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getMemoryInMb(LocalHostResourceManagerLinux.java:40)
        at com.google.devtools.build.lib.actions.LocalHostResourceManagerLinux.getLocalHostResources(LocalHostResourceManagerLinux.java:46)
        at com.google.devtools.build.lib.actions.LocalHostCapacity.getNewLocalHostCapacity(LocalHostCapacity.java:46)
        at com.google.devtools.build.lib.actions.LocalHostCapacity.getLocalHostCapacity(LocalHostCapacity.java:34)
        at com.google.devtools.build.lib.buildtool.BuildRequestOptions$JobsConverter.lambda$new$0(BuildRequestOptions.java:465)
        at com.google.devtools.build.lib.util.ResourceConverter.applyOperator(ResourceConverter.java:136)
        at com.google.devtools.build.lib.util.ResourceConverter.convert(ResourceConverter.java:122)
        at com.google.devtools.build.lib.util.ResourceConverter.convert(ResourceConverter.java:41)
        at com.google.devtools.common.options.OptionDefinition.getDefaultValue(OptionDefinition.java:270)
        at com.google.devtools.common.options.OptionValueDescription$DefaultOptionValueDescription.getValue(OptionValueDescription.java:123)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:378)
        at com.google.devtools.common.options.OptionsParserImpl.parse(OptionsParserImpl.java:325)
        at com.google.devtools.common.options.OptionsParser.parseWithSourceFunction(OptionsParser.java:642)
        at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseArgsAndConfigs(BlazeOptionHandler.java:207)
        at com.google.devtools.build.lib.runtime.BlazeOptionHandler.parseOptions(BlazeOptionHandler.java:274)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:275)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:659)
        at io.grpc.Context$1.run(Context.java:595)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
