### ISSUE TITLE
SO_REUSEPORT crash in envoy 1.13.1

### ISSUE THREAD

**Issue by oblazek** [envoyproxy/envoy#10921]
Description:
> Envoy is crashing when SO_REUSEPORT socket option is used for our TCP listeners. Below is a related backtrace of a segfault in envoy version 1.13.1.

Repro steps:
> Our envoys are running on baremetal ubuntu 16.04 LTS with kernel 4.14.130. 

Logs:
> Apr 22 10:59:52 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:52.681][22259][info][upstream] [source/common/upstream/cds_api_impl.cc:90] cds: add/update cluster 'k8s2_ko__labrador_stable__service_freshness_svc__n__one_url0'
Apr 22 10:59:53 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:53.830][22259][warning][config] [source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) k8s2_ko__labrador_stable__service_freshness_svc__n__one: route: unknown cluster 'k8s2_ko__labrador_stable__service_freshness_svc__n__one_url0'
Apr 22 10:59:54 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:54.440][22259][info][upstream] [source/common/upstream/cds_api_impl.cc:74] cds: add 1955 cluster(s), remove 2 cluster(s)
Apr 22 10:59:55 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:55.372][22259][info][upstream] [source/server/lds_api.cc:73] lds: add/update listener 'k8s2_ko__labrador_stable__service_freshness_svc__n__one'
Apr 22 10:59:55 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:55.411][22516][critical][assert] [source/exe/main_common.cc:81] panic: out of memory
Apr 22 10:59:55 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:55.411][22513][critical][assert] [source/exe/main_common.cc:81] panic: out of memory
Apr 22 10:59:55 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:55.411][22503][critical][assert] [source/exe/main_common.cc:81] panic: out of memory
Apr 22 10:59:55 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:55.411][22516][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Aborted, suspect faulting address 0x56f3
Apr 22 10:59:55 lb-l7-5.ko tt-envoy[22257]: [2020-04-22 10:59:55.411][22516][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):

Backtrace:
```
Core was generated by `/www/envoy/bin/envoy -c /www/envoy/conf/conf.yaml --restart-epoch 0 --drain-tim'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f2a71b15428 in _IO_vfprintf_internal (s=0x1,
    format=0x56002b801a30 <Envoy::MainCommonBase::MainCommonBase(Envoy::OptionsImpl const&, Envoy::Event::TimeSystem&, Envoy::ListenerHooks&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Runtime::RandomGenerator, std::__1::default_delete<Envoy::Runtime::RandomGenerator> >&&, Envoy::Thread::ThreadFactory&, Envoy::Filesystem::Instance&, std::__1::unique_ptr<Envoy::ProcessContext, std::__1::default_delete<Envoy::ProcessContext> >)::$_0::__invoke()> "UH\211\345\350\a",
    ap=0x56002cd98340 <(anonymous namespace)::set_new_handler_lock>) at vfprintf.c:1621
1621 vfprintf.c: No such file or directory.
[Current thread is 1 (LWP 5081)]
(gdb)
(gdb) bt
#0  0x00007f2a71b15428 in _IO_vfprintf_internal (s=0x1,
    format=0x56002b801a30 <Envoy::MainCommonBase::MainCommonBase(Envoy::OptionsImpl const&, Envoy::Event::TimeSystem&, Envoy::ListenerHooks&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Runtime::RandomGenerator, std::__1::default_delete<Envoy::Runtime::RandomGenerator> >&&, Envoy::Thread::ThreadFactory&, Envoy::Filesystem::Instance&, std::__1::unique_ptr<Envoy::ProcessContext, std::__1::default_delete<Envoy::ProcessContext> >)::$_0::__invoke()> "UH\211\345\350\a",
    ap=0x56002cd98340 <(anonymous namespace)::set_new_handler_lock>) at vfprintf.c:1621
#1  0x000056002b801a39 in Envoy::MainCommonBase::MainCommonBase(Envoy::OptionsImpl const&, Envoy::Event::TimeSystem&, Envoy::ListenerHooks&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Runtime::RandomGenerator, std::__1::default_delete<Envoy::Runtime::RandomGenerator> >&&, Envoy::Thread::ThreadFactory&, Envoy::Filesystem::Instance&, std::__1::unique_ptr<Envoy::ProcessContext, std::__1::default_delete<Envoy::ProcessContext> >)::$_0::__invoke() () at source/exe/main_common.cc:81
#2  0x000056002cb74785 in (anonymous namespace)::handle_oom(void* (*)(void*), void*, bool, bool) ()
#3  0x000056002cbdc090 in tcmalloc::allocate_full_cpp_throw_oom(unsigned long) ()
#4  0x000056002b801f1d in std::__1::__libcpp_allocate (__size=7451599682960305765, __align=1) at /opt/llvm/bin/../include/c++/v1/new:253
#5  std::__1::allocator<char>::allocate (this=0x7f2a5caa0278, __n=7451599682960305765) at /opt/llvm/bin/../include/c++/v1/memory:1813
#6  std::__1::allocator_traits<std::__1::allocator<char> >::allocate (__a=..., __n=7451599682960305765) at /opt/llvm/bin/../include/c++/v1/memory:1546
#7  fmt::v5::internal::allocate<std::__1::allocator<char> > (alloc=..., n=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/format.h:284
#8  fmt::v5::basic_memory_buffer<char, 500ul, std::__1::allocator<char> >::grow (this=0x7f2a5caa0278, size=5081) at external/com_github_fmtlib_fmt/include/fmt/format.h:541
#9  0x000056002b802f08 in fmt::v5::internal::basic_buffer<char>::reserve (this=0x7f2a5caa0278, new_capacity=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/core.h:275
#10 fmt::v5::internal::basic_buffer<char>::resize (this=0x7f2a5caa0278, new_size=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/core.h:265
#11 fmt::v5::internal::reserve<fmt::v5::internal::basic_buffer<char> > (it=..., n=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/format.h:599
#12 fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::reserve (this=0x7f2a5caa0210, n=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/format.h:2272
#13 fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::write (this=0x7f2a5caa0210, value=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:2623
#14 fmt::v5::internal::arg_formatter_base<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::operator() (this=0x7f2a5caa0210, value=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:1433
#15 0x000056002b8022e9 in fmt::v5::internal::parse_format_string<false, char, fmt::v5::format_handler<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >&> (format_str=..., handler=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3097
#16 0x000056002b82c755 in fmt::v5::vformat_to<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> > (out=...,
    format_str=..., args=..., loc=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3130
#17 fmt::v5::internal::vformat_to<char> (buf=..., format_str=..., args=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3237
#18 fmt::v5::internal::vformat<char> (format_str=..., args=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3414
#19 0x000056002c18014e in fmt::v5::format<char [30], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*> (format_str=..., args=..., args=...) at external/com_github_fmtlib_fmt/include/fmt/core.h:1456
#20 Envoy::Server::ListenSocketFactoryImpl::createListenSocketAndApplyOptions (this=0x56003fb1de98) at source/server/listener_impl.cc:85
#21 0x000056002c180518 in Envoy::Server::ListenSocketFactoryImpl::getListenSocket (this=0x56003fb1de98) at source/server/listener_impl.cc:123
#22 0x000056002c1ce942 in Envoy::Server::ConnectionHandlerImpl::ActiveTcpListener::ActiveTcpListener (this=0x56003ba5b260, parent=..., config=...) at source/server/connection_handler_impl.cc:118
#23 0x000056002c1cda09 in std::__1::make_unique<Envoy::Server::ConnectionHandlerImpl::ActiveTcpListener, Envoy::Server::ConnectionHandlerImpl&, Envoy::Network::ListenerConfig&> (__args=..., __args=...) at /opt/llvm/bin/../include/c++/v1/memory:3003
#24 Envoy::Server::ConnectionHandlerImpl::addListener (this=0x56002e598f00, config=...) at source/server/connection_handler_impl.cc:33
#25 0x000056002c1cd19f in Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1::operator()() const (this=0x56003ffff500) at source/server/worker_impl.cc:44
#26 _ZNSt3__18__invokeIRZN5Envoy6Server10WorkerImpl11addListenerERNS1_7Network14ListenerConfigENS_8functionIFvbEEEE3$_1JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSC_DpOSD_ (__f=...) at /opt/llvm/bin/../include/c++/v1/type_traits:3530
#27 std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1&>(Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1&) (__args=...) at /opt/llvm/bin/../include/c++/v1/__functional_base:348
#28 std::__1::__function::__alloc_func<Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1(std::__1::allocator<std::__1::allocator>, void ())>::operator()() (this=0x56003ffff500)
    at /opt/llvm/bin/../include/c++/v1/functional:1533
#29 std::__1::__function::__func<Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1(std::__1::allocator<std::__1::allocator>, void ())>::operator()() (this=0x56003ffff4f0)
    at /opt/llvm/bin/../include/c++/v1/functional:1707
#30 0x000056002c1d5b66 in std::__1::__function::__value_func<void ()>::operator()() const (this=0x7f2a5caa06f0) at /opt/llvm/bin/../include/c++/v1/functional:1860
#31 std::__1::function<void ()>::operator()() const (this=0x7f2a5caa06f0) at /opt/llvm/bin/../include/c++/v1/functional:2419
#32 Envoy::Event::DispatcherImpl::runPostCallbacks (this=0x56002e6b6c00) at source/common/event/dispatcher_impl.cc:224
#33 0x000056002c4ed0b6 in event_process_active_single_queue ()
#34 0x000056002c4ebc3e in event_base_loop ()
#35 0x000056002c1cc8f8 in Envoy::Server::WorkerImpl::threadRoutine (this=0x56002e421e60, guard_dog=...) at source/server/worker_impl.cc:110
#36 0x000056002c6b8363 in std::__1::__function::__value_func<void ()>::operator()() const (this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/functional:1860
#37 std::__1::function<void ()>::operator()() const (this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/functional:2419
#38 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::operator()(void*) const (this=<optimized out>, arg=<optimized out>) at source/common/common/posix/thread_impl.cc:33
#39 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) (arg=<optimized out>) at source/common/common/posix/thread_impl.cc:32
#40 0x00007f2a71eb16ba in pthread_getattr_np (thread_id=94558776739096, attr=0x0) at pthread_getattr_np.c:88
#41 0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x00007f2a71b15428 in _IO_vfprintf_internal (s=0x1,
    format=0x56002b801a30 <Envoy::MainCommonBase::MainCommonBase(Envoy::OptionsImpl const&, Envoy::Event::TimeSystem&, Envoy::ListenerHooks&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Runtime::RandomGenerator, std::__1::default_delete<Envoy::Runtime::RandomGenerator> >&&, Envoy::Thread::ThreadFactory&, Envoy::Filesystem::Instance&, std::__1::unique_ptr<Envoy::ProcessContext, std::__1::default_delete<Envoy::ProcessContext> >)::$_0::__invoke()> "UH\211\345\350\a",
    ap=0x56002cd98340 <(anonymous namespace)::set_new_handler_lock>) at vfprintf.c:1621
        string = <optimized out>
        width = 8
        signed_number = <optimized out>
        is_short = 1023504608
        spec = 101 'e'
        ptr = <optimized out>
        ptr = <optimized out>
        outc = <optimized out>
        step0_jumps = {0, 160, 64, 1664, 1576, 1464, 1360, 2216, 2912, 208, 2032, 1848, 1760, -768, -760, 3024, 3000, 3104, 2128, 3120, -304, -704, 384, 312, -80, -1256, 2624, -1344, -1344, 2536}
        base = <optimized out>
        pad = <optimized out>
        offset = <optimized out>
        offset = <optimized out>
        step1_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 2032, 1848, 1760, -768, -760, 3024, 3000, 3104, 2128, 3120, -304, -704, 384, 312, -80, -1256, 2624, -1344, -1344, 0}
        args_value = <optimized out>
        is_negative = <optimized out>
        number = <optimized out>
        use_outdigits = <optimized out>
        step2_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2032, 1848, 1760, -768, -760, 3024, 3000, 3104, 2128, 3120, -304, -704, 384, 312, -80, -1256, 2624, -1344, -1344, 0}
        alt = 733045535
        left = 1331545088
        showsign = 1267700866
        group = 1554644144
        is_char = 14
        step3a_jumps = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1936, 0, 0, 0, -760, 3024, 3000, 3104, 2128, 0, 0, 0, 0, 312, 0, 0, 0, 0, 0, 0}
        the_arg = {pa_wchar = 94 L'^', pa_int = 94, pa_long_int = 94, pa_long_long_int = 94, pa_u_int = 94, pa_u_long_int = 94, pa_u_long_long_int = 94, pa_double = 4.6442170709077175e-322, pa_long_double = <invalid float value>,
          pa_string = 0x5e <error: Cannot access memory at address 0x5e>, pa_wstring = 0x5e <error: Cannot access memory at address 0x5e>, pa_pointer = 0x5e, pa_user = 0x5e}
        space = 1075408736
        is_long_double = 1
        is_long = 1
        step3b_jumps = {0 <repeats 11 times>, 1760, 0, 0, -760, 3024, 3000, 3104, 2128, 3120, -304, -704, 384, 312, -80, -1256, 2624, 0, 0, 0}
        step4_jumps = {0 <repeats 14 times>, -760, 3024, 3000, 3104, 2128, 3120, -304, -704, 384, 312, -80, -1256, 2624, 0, 0, 0}
        prec = 1907446824
        _buffer = {__routine = 0x40, __arg = 0x2e72657473756c63, __canceltype = 64, __prev = 0x56002b814178 <fmt::v5::internal::arg_formatter_base<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::write(char const*)+40>}
        _avail = <optimized out>
        thousands_sep = 0x5d31383a63632e6e <error: Cannot access memory at address 0x5d31383a63632e6e>
        grouping = 0x6d20666f2074756f <error: Cannot access memory at address 0x6d20666f2074756f>
        done = 750209056
        f = 0x6 <error: Cannot access memory at address 0x6>
        lead_str_end = 0x9ddfea08eb382d69 <error: Cannot access memory at address 0x9ddfea08eb382d69>
        end_of_spec = <optimized out>
        work_buffer = "@U\352q*\177\000\000\037شq*\177\000\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\216R\353q*\177\000\000\340\374\251\\*\177\000\000\220\240;.\000V\000\000\070\375\251\\*\177\000\000\360\375\251\\*\177\000\000\260\016\276,\000V\000\000\220\240;.\000V\000\000\005\000\000\000\000\000\000\000p\375\251\\*\177\000\000\364K\271,\000V\000\000\370Y\364,\000V\000\000\376=\271,\000V\000\000\005\000\000\000\000\000\000\000\001}\025,\000V\000\000\370Y\364,\000V\000\000\030EL.\000V\000\000\220\240;.\000V\000\000\063w\263,\000V\000\000\200\240;.\000V\000\000\220\240;.\000V\000\000\220\375\251\\*\177\000\000\251"...
        workstart = <optimized out>
        workend = <optimized out>
        ap_save = {{gp_offset = 3, fp_offset = 0, overflow_arg_area = 0x7f2a71ea5620 <_nl_global_locale+160>, reg_save_area = 0x7f2a71b4d81f <_int_malloc+1327>}}
        nspecs_done = 2681
        save_errno = 1554644056
        readonly_format = 1919905125
        __PRETTY_FUNCTION__ = "_IO_vfprintf_internal"
        __result = <optimized out>
#1  0x000056002b801a39 in Envoy::MainCommonBase::MainCommonBase(Envoy::OptionsImpl const&, Envoy::Event::TimeSystem&, Envoy::ListenerHooks&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Runtime::RandomGenerator, std::__1::default_delete<Envoy::Runtime::RandomGenerator> >&&, Envoy::Thread::ThreadFactory&, Envoy::Filesystem::Instance&, std::__1::unique_ptr<Envoy::ProcessContext, std::__1::default_delete<Envoy::ProcessContext> >)::$_0::__invoke() () at source/exe/main_common.cc:81
No locals.
#2  0x000056002cb74785 in (anonymous namespace)::handle_oom(void* (*)(void*), void*, bool, bool) ()
No symbol table info available.
#3  0x000056002cbdc090 in tcmalloc::allocate_full_cpp_throw_oom(unsigned long) ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#4  0x000056002b801f1d in std::__1::__libcpp_allocate (__size=7451599682960305765, __align=1) at /opt/llvm/bin/../include/c++/v1/new:253
No locals.
#5  std::__1::allocator<char>::allocate (this=0x7f2a5caa0278, __n=7451599682960305765) at /opt/llvm/bin/../include/c++/v1/memory:1813
No locals.
#6  std::__1::allocator_traits<std::__1::allocator<char> >::allocate (__a=..., __n=7451599682960305765) at /opt/llvm/bin/../include/c++/v1/memory:1546
No locals.
#7  fmt::v5::internal::allocate<std::__1::allocator<char> > (alloc=..., n=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/format.h:284
No locals.
#8  fmt::v5::basic_memory_buffer<char, 500ul, std::__1::allocator<char> >::grow (this=0x7f2a5caa0278, size=5081) at external/com_github_fmtlib_fmt/include/fmt/format.h:541
        old_data = 0x7f2a5caa0298 "\320ۧ?"
        old_capacity = 0
        new_capacity = 7451599682960305765
        new_data = <optimized out>
#9  0x000056002b802f08 in fmt::v5::internal::basic_buffer<char>::reserve (this=0x7f2a5caa0278, new_capacity=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/core.h:275
No locals.
#10 fmt::v5::internal::basic_buffer<char>::resize (this=0x7f2a5caa0278, new_size=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/core.h:265
No locals.
#11 fmt::v5::internal::reserve<fmt::v5::internal::basic_buffer<char> > (it=..., n=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/format.h:599
        c = @0x7f2a5caa0278: warning: RTTI symbol not found for class 'fmt::v5::basic_memory_buffer<char, 500ul, std::__1::allocator<char> >'
{_vptr$basic_buffer = 0x56002cbe0eb0 <vtable for fmt::v5::basic_memory_buffer<char, 500ul, std::__1::allocator<char> >+16>, ptr_ = 0x7f2a5caa0298 "\320ۧ?", size_ = 0, capacity_ = 500}
        size = 0
#12 fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::reserve (this=0x7f2a5caa0210, n=7451599682960305765) at external/com_github_fmtlib_fmt/include/fmt/format.h:2272
No locals.
#13 fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::write (this=0x7f2a5caa0210, value=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:2623
        it = <optimized out>
#14 fmt::v5::internal::arg_formatter_base<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::operator() (this=0x7f2a5caa0210, value=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:1433
No locals.
#15 0x000056002b8022e9 in fmt::v5::internal::parse_format_string<false, char, fmt::v5::format_handler<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >&> (format_str=..., handler=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3097
        p = 0x56002af9f97a "}: Setting socket options {}"
        begin = <optimized out>
        end = 0x56002af9f996 ""
        write = {handler_ = @0x7f2a5caa0490}
#16 0x000056002b82c755 in fmt::v5::vformat_to<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> > (out=...,
    format_str=..., args=..., loc=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3130
        h = {<fmt::v5::internal::error_handler> = {<No data fields>},
          context = {<fmt::v5::internal::context_base<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>, char>> = {
              parse_context_ = {<fmt::v5::internal::error_handler> = {<No data fields>}, format_str_ = {data_ = 0x56002af9f97a "}: Setting socket options {}", size_ = 28}, next_arg_id_ = 1},
              out_ = {<std::__1::iterator<std::__1::output_iterator_tag, void, void, void, void>> = {<No data fields>}, container = 0x7f2a5caa0278}, args_ = {types_ = 171, {values_ = 0x7f2a5caa0580, args_ = 0x7f2a5caa0580}}, loc_ = {locale_ = 0x0}}, map_ = {map_ = 0x0,
              size_ = 0}}, arg = {value_ = {{int_value = 1920298835, uint_value = 1920298835, long_long_value = 4472748857728790355, ulong_long_value = 4472748857728790355, double_value = 1.0707909644342217e-09, long_double_value = <invalid float value>,
                pointer = 0x3e12656372756f53, string = {value = 0x3e12656372756f53 <error: Cannot access memory at address 0x3e12656372756f53>, size = 7451599682960305765}, sstring = {value = 0x3e12656372756f53 <error: Cannot access memory at address 0x3e12656372756f53>,
                  size = 7451599682960305765}, ustring = {value = 0x3e12656372756f53 <error: Cannot access memory at address 0x3e12656372756f53>, size = 7451599682960305765}, custom = {value = 0x3e12656372756f53, format = 0x6769666e6f432e65}}},
            type_ = fmt::v5::internal::string_type}}
#17 fmt::v5::internal::vformat_to<char> (buf=..., format_str=..., args=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3237
No locals.
#18 fmt::v5::internal::vformat<char> (format_str=..., args=...) at external/com_github_fmtlib_fmt/include/fmt/format.h:3414
        buffer = warning: RTTI symbol not found for class 'fmt::v5::basic_memory_buffer<char, 500ul, std::__1::allocator<char> >'
{<std::__1::allocator<char>> = {<No data fields>}, <fmt::v5::internal::basic_buffer<char>> = {_vptr$basic_buffer = 0x56002cbe0eb0 <vtable for fmt::v5::basic_memory_buffer<char, 500ul, std::__1::allocator<char> >+16>, ptr_ = 0x7f2a5caa0298 "\320ۧ?",
            size_ = 0, capacity_ = 500},
          store_ = "\320ۧ?\000V\000\000\360\002\252\\*\177\000\000NmN,\000V\000\000\255\001\000\000\000\000\000\000\000\304\313,\000V\000\000@\003\252\\*\177\000\000\274\066\071,\000V\000\000XK\220;\000V\000\000\031kN,\000V\000\000\020\000\000\000\000\000\000\000\000\304\313,\000V\000\000\060\003\252\\*\177\000\000P\034N,\000V\000\000P\336\262+\000V\000\000P\336\262+\000V\000\000\230\236\243?\000V\000\000XK\220;\000V\000\000\300ޱ?\000V\000\000\001\000\000\000\000\000\000\000\240\003\252\\*\177\000\000,QD,\000V\000\000\200\003\252\\*\177\000\000\336RD,\000V\000\000\200\234\313,\000V\000\000\221`\",\000V\000\000\370\003\252\\"...}
#19 0x000056002c18014e in fmt::v5::format<char [30], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*> (format_str=..., args=..., args=...) at external/com_github_fmtlib_fmt/include/fmt/core.h:1456
No locals.
#20 Envoy::Server::ListenSocketFactoryImpl::createListenSocketAndApplyOptions (this=0x56003fb1de98) at source/server/listener_impl.cc:85
        ok = false
        message = <optimized out>
        socket = <optimized out>
#21 0x000056002c180518 in Envoy::Server::ListenSocketFactoryImpl::getListenSocket (this=0x56003fb1de98) at source/server/listener_impl.cc:123
        socket = {__ptr_ = 0x0, __cntrl_ = 0x0}
#22 0x000056002c1ce942 in Envoy::Server::ConnectionHandlerImpl::ActiveTcpListener::ActiveTcpListener (this=0x56003ba5b260, parent=..., config=...) at source/server/connection_handler_impl.cc:118
No locals.
#23 0x000056002c1cda09 in std::__1::make_unique<Envoy::Server::ConnectionHandlerImpl::ActiveTcpListener, Envoy::Server::ConnectionHandlerImpl&, Envoy::Network::ListenerConfig&> (__args=..., __args=...) at /opt/llvm/bin/../include/c++/v1/memory:3003
No locals.
#24 Envoy::Server::ConnectionHandlerImpl::addListener (this=0x56002e598f00, config=...) at source/server/connection_handler_impl.cc:33
---Type <return> to continue, or q <return> to quit---
        tcp_listener = <optimized out>
        details = <optimized out>
#25 0x000056002c1cd19f in Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1::operator()() const (this=0x56003ffff500) at source/server/worker_impl.cc:44
        e = <optimized out>
#26 _ZNSt3__18__invokeIRZN5Envoy6Server10WorkerImpl11addListenerERNS1_7Network14ListenerConfigENS_8functionIFvbEEEE3$_1JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSC_DpOSD_ (__f=...) at /opt/llvm/bin/../include/c++/v1/type_traits:3530
No locals.
#27 std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1&>(Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1&) (__args=...) at /opt/llvm/bin/../include/c++/v1/__functional_base:348
No locals.
#28 std::__1::__function::__alloc_func<Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1(std::__1::allocator<std::__1::allocator>, void ())>::operator()() (this=0x56003ffff500)
    at /opt/llvm/bin/../include/c++/v1/functional:1533
No locals.
#29 std::__1::__function::__func<Envoy::Server::WorkerImpl::addListener(Envoy::Network::ListenerConfig&, std::__1::function<void (bool)>)::$_1(std::__1::allocator<std::__1::allocator>, void ())>::operator()() (this=0x56003ffff4f0)
    at /opt/llvm/bin/../include/c++/v1/functional:1707
No locals.
#30 0x000056002c1d5b66 in std::__1::__function::__value_func<void ()>::operator()() const (this=0x7f2a5caa06f0) at /opt/llvm/bin/../include/c++/v1/functional:1860
No locals.
#31 std::__1::function<void ()>::operator()() const (this=0x7f2a5caa06f0) at /opt/llvm/bin/../include/c++/v1/functional:2419
No locals.
#32 Envoy::Event::DispatcherImpl::runPostCallbacks (this=0x56002e6b6c00) at source/common/event/dispatcher_impl.cc:224
        callback = {<std::__1::__function::__maybe_derive_from_unary_function<void ()>> = {<No data fields>}, <std::__1::__function::__maybe_derive_from_binary_function<void ()>> = {<No data fields>}, __f_ = {__buf_ = {
              __lx = "\371\276\071\001\000\000\000\000\\\240\005", '\000' <repeats 13 times>, "H\350\211:\000V\000"}, __f_ = 0x56003ffff4f0}}
#33 0x000056002c4ed0b6 in event_process_active_single_queue ()
No symbol table info available.
#34 0x000056002c4ebc3e in event_base_loop ()
No symbol table info available.
#35 0x000056002c1cc8f8 in Envoy::Server::WorkerImpl::threadRoutine (this=0x56002e421e60, guard_dog=...) at source/server/worker_impl.cc:110
No locals.
#36 0x000056002c6b8363 in std::__1::__function::__value_func<void ()>::operator()() const (this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/functional:1860
No locals.
#37 std::__1::function<void ()>::operator()() const (this=<optimized out>) at /opt/llvm/bin/../include/c++/v1/functional:2419
No locals.
#38 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::operator()(void*) const (this=<optimized out>, arg=<optimized out>) at source/common/common/posix/thread_impl.cc:33
No locals.
#39 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) (arg=<optimized out>) at source/common/common/posix/thread_impl.cc:32
No locals.
#40 0x00007f2a71eb16ba in pthread_getattr_np (thread_id=94558776739096, attr=0x0) at pthread_getattr_np.c:88
        rl = {rlim_cur = 0, rlim_max = 0}
        fp = 0x0
        thread = 0x56002e4c4518
        iattr = 0x0
        ret = 0
#41 0x0000000000000000 in ?? ()
No symbol table info available.
(gdb)
```

Note:
> The above crash happens when listener is added by LDS.

**Comment by l8huang** [comment]
I'm using 1.13.1 and don't have crash issue with reuseport enabled. I tried last commit in maser branch(32b8445b8fac9e46f67c2f2ce884716b7bc9dde8/1.15.0-dev/Clean/DEBUG/BoringSSL), couldn't reproduce it with a minimal static config.

@oblazek Could you please send the commit version you are using? If a static config can reproduce the issue, it could be helpful.

**Comment by mattklein123** [comment]
In looking at this again this looks like an OOM so I'm going to close. If you have a self contained repro please let us know.

**Comment by oblazek** [comment]
That doesn't sound right.. we are running envoy on a baremetal machines with approx 192GB RAM and the whole system including envoy is consuming around 10GB so not sure how this can OOM.

**Comment by mattklein123** [comment]
> That doesn't sound right.. we are running envoy on a baremetal machines with approx 192GB RAM and the whole system including envoy is consuming around 10GB so not sure how this can OOM.

I'm working on fixing related issues right now and I can't repro this. Are you still able to repro this on current master? It's possible this is a bug in the format library.

**Comment by oblazek** [comment]
We've rolled it back, but yeah np I will try that again with current master.
