### ISSUE TITLE
Envoy is red on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [envoyproxy/envoy#11400]
https://buildkite.com/bazel/envoy/builds/1179

Please help fixing the problems, in the meantime, I'll have to disable Envoy in Bazel downstream.

Related issues: 
https://github.com/envoyproxy/envoy/pull/11218
https://github.com/envoyproxy/envoy/pull/11226

/cc @lizan

**Comment by meteorcloudy** [comment]
There are currently two issues:

In RBE build:
```
ERROR: java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid resource field value in the request.
	at com.google.devtools.build.lib.remote.RemoteServerCapabilities.get(RemoteServerCapabilities.java:82)
	at com.google.devtools.build.lib.remote.RemoteModule.verifyServerCapabilities(RemoteModule.java:143)
	at com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:303)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:355)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:208)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:603)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:663)
	at io.grpc.Context$1.run(Context.java:595)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

And in coverage build:
```
(00:19:51) ERROR: output '_coverage/_coverage_report.dat' was not created
(00:19:51) ERROR: not all outputs were created or valid
...
//test/integration:stats_integration_test                                FAILED in 6 out of 6 in 9.4s
```

**Comment by mattklein123** [comment]
@lizan PTAL

**Comment by lizan** [comment]
@meteorcloudy I don't have any idea why RBE fails in Bazel CI, have you changed RBE settings recently?
