### ISSUE TITLE
Coverage runs of fuzzers fail due to an exception which should be caught, but is not

### ISSUE THREAD

**Issue by sqkerner** [envoyproxy/envoy#12102]
Running ` test/run_envoy_bazel_coverage.sh` on a fuzz target creates a binary that can't catch exceptions.  

```shell
$ git checkout upstream/master
(at commit 7abb0e0bb)

$ FUZZ_COVERAGE=true VALIDATE_COVERAGE=false test/run_envoy_bazel_coverage.sh //test/extensions/filters/network/local_ratelimit:local_ratelimit_fuzz_test

FAILED: Build did NOT complete successfully
//test/extensions/filters/network/local_ratelimit:local_ratelimit_fuzz_test FAILED in 6.5s
```

In the test log:

```
INFO: Seed: 1
INFO: Loaded 1 modules   (851023 inline 8-bit counters): 851023 [0x1eb1e2be, 0x1ebedf0d), 
INFO: Loaded 1 PC tables (851023 PCs): 851023 [0x1ebedf10,0x1f8ea400), 
INFO:        1 files found in fuzz_corpus
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
terminating with uncaught exception of type Envoy::ProtoValidationException
==23== ERROR: libFuzzer: deadly signal
    #0 0x17f4f50 in __sanitizer_print_stack_trace (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x17f4f50)
    #1 0x17a1238 in fuzzer::PrintStackTrace() (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x17a1238)
    #2 0x1786383 in fuzzer::Fuzzer::CrashCallback() (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x1786383)
    #3 0x7f7da524e10f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1410f)
error: failed to decompress '.debug_aranges', zlib is not available
error: failed to decompress '.debug_info', zlib is not available
error: failed to decompress '.debug_abbrev', zlib is not available
error: failed to decompress '.debug_line', zlib is not available
error: failed to decompress '.debug_str', zlib is not available
error: failed to decompress '.debug_loc', zlib is not available
error: failed to decompress '.debug_ranges', zlib is not available
    #4 0x7f7da50b2760 in raise (/lib/x86_64-linux-gnu/libc.so.6+0x3b760)
    #5 0x7f7da509c55a in abort (/lib/x86_64-linux-gnu/libc.so.6+0x2555a)
    #6 0x64937aa in abort_message (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x64937aa)
    #7 0x6493696 in demangling_terminate_handler() (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x6493696)
    #8 0x6493532 in std::__terminate(void (*)()) (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x6493532)
    #9 0x6492b55 in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x6492b55)
    #10 0x6492aee in __cxa_throw (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x6492aee)
    #11 0x17fcc17 in void Envoy::MessageUtil::validate<envoy::extensions::filters::network::local_ratelimit::LocalRateLimitTestCase>(envoy::extensions::filters::network::local_ratelimit::LocalRateLimitTestCase const&, Envoy::ProtobufMessage::ValidationVisitor&) (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x17fcc17)
    #12 0x17f9659 in void Envoy::TestUtility::validate<envoy::extensions::filters::network::local_ratelimit::LocalRateLimitTestCase>(envoy::extensions::filters::network::local_ratelimit::LocalRateLimitTestCase const&) (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x17f9659)
    #13 0x17f6ee9 in Envoy::Extensions::NetworkFilters::LocalRateLimitFilter::TestOneProtoInput(envoy::extensions::filters::network::local_ratelimit::LocalRateLimitTestCase const&) (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x17f6ee9)
    #14 0x17f6e03 in LLVMFuzzerTestOneInput (/usr/local/google/home/skerner/.cache/bazel/_bazel_skerner/2ddb1726a15ec9e20b8bcb3ee0a8d669/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test+0x17f6e03)
```

Hmm, that is odd, because the exception is caught.  From test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test.cc :

```
DEFINE_PROTO_FUZZER( 
    const envoy::extensions::filters::network::local_ratelimit::LocalRateLimitTestCase& input) { 
 
  try { 

    // Stack shows that this call throws a ProtoValidationException:
    TestUtility::validate(input);   

  } catch (const ProtoValidationException& e) {

    // Why doesn't control get here?

    ENVOY_LOG_MISC(debug, "ProtoValidationException: {}", e.what()); 
    return; 
  } ...
```

The script `test/run_envoy_bazel_coverage.sh` runs bazel as follows:

```
bazel coverage --config=fuzz-coverage --test_tag_filters=-nocoverage //test/extensions/filters/network/local_ratelimit:local_ratelimit_fuzz_test
```

If I add `--config=asan` to the bazel coverage run, then the build works and the exception is caught.

What could cause the generated code to fail to catch exceptions?

**Comment by sqkerner** [comment]
Here is the commit that introduced `--config=plain-fuzzer`:

https://gitlab.staging.cncf.ci/envoyproxy/envoy/commit/6e9273419b598dda99267405d8079ffdc2b5c78c

Its commit message says:

> (2) Build fuzz coverage reports without any sanitizers (`plain-fuzzer`). 
     - Caveat: Avoid linking libfuzzer with `-fsanitize=fuzzer`, since the libfuzzer implementation is built with a private libc++ implementation whose exception handling conflicts with libc++. I had to build it myself....

@asraa, could this be related?

**Comment by asraa** [comment]
Yes... it's te libc++/private libc++ conflict when throwing and catching exceptions. Building libfuzzer from scratch in that PR fixed that issue for me, but let me see if I can reproduce the issue and figure this out this afternoon
