### ISSUE TITLE
envoy coredump when print accesslog with filed "DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT"

### ISSUE THREAD

**Issue by huhaipeng** [envoyproxy/envoy#12937]
title: envoy coredump while printing accesslog with filed "DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT"

*Description*:

when print  accesslog with filed "DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT" in tcp proxy filter，envoy will coredump.The reason why coredump is that, `downstream_direct_remote_address_`is inited with null,but envoy has no functions to set `downstream_direct_remote_address_` in and  use it in ` const std::string& Utility::formatDownstreamAddressNoPort(const Network::Address::Instance& address)`.

*Repro steps*:

* Configure accesslog format with filed `%DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT%`

  ```yaml
   listeners:
     - name: listener_1
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            typed_config:
              "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy"
              "stat_prefix": service_google
              "cluster": service_google
              access_log:
              - name: envoy.file_access_log
                typed_config:
                  "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                  path: /tmp/access.log
                  json_format:
                    realip_remote_addr: "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT%"
                  
                  
    clusters:
    - name: service_google
      connect_timeout: 10s
      type: STRICT_DNS
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service_google
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: www.google.com
                  port_value: 80
  ```

* make a request to port 80

  ```
  curl localhost:80 -v
  
  ```

* then envoy will coredump, log backtrace as follow:

  ```
  [2020-09-02 10:26:05.304][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x0
  [2020-09-02 10:26:05.304][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
  [2020-09-02 10:26:05.304][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 44f8c365a1f1798f0af776f6aa64279dc68f5666/1.12.1/Modified/DEBUG/BoringSSL
  [2020-09-02 10:26:05.330][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: Envoy::SignalAction::sigHandler() [0x562d36f35b8c]
  [2020-09-02 10:26:05.330][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: __restore_rt [0x7f135432b8a0]
  [2020-09-02 10:26:05.346][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: _ZZN5Envoy9AccessLog19StreamInfoFormatterC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEENK4$_18clB5cxx11ERKNS_10StreamInfo10StreamInfoE [0x562d36c15f12]
  [2020-09-02 10:26:05.362][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: std::_Function_handler<>::_M_invoke() [0x562d36c15dbb]
  [2020-09-02 10:26:05.378][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: std::function<>::operator()() [0x562d36aff921]
  [2020-09-02 10:26:05.395][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: _ZNK5Envoy9AccessLog19StreamInfoFormatter6formatB5cxx11ERKNS_4Http9HeaderMapES5_S5_RKNS_10StreamInfo10StreamInfoE [0x562d36c0fc71]
  [2020-09-02 10:26:05.411][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: _ZNK5Envoy9AccessLog13FormatterImpl6formatB5cxx11ERKNS_4Http9HeaderMapES5_S5_RKNS_10StreamInfo10StreamInfoE [0x562d36c0c440]
  [2020-09-02 10:26:05.427][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: _ZNK5Envoy9AccessLog17JsonFormatterImpl5toMapB5cxx11ERKNS_4Http9HeaderMapES5_S5_RKNS_10StreamInfo10StreamInfoE [0x562d36c0cbc2]
  [2020-09-02 10:26:05.443][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: _ZNK5Envoy9AccessLog17JsonFormatterImpl6formatB5cxx11ERKNS_4Http9HeaderMapES5_S5_RKNS_10StreamInfo10StreamInfoE [0x562d36c0c7a5]
  [2020-09-02 10:26:05.459][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::Extensions::AccessLoggers::File::FileAccessLog::emitLog() [0x562d36b31f3c]
  [2020-09-02 10:26:05.476][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: Envoy::Extensions::AccessLoggers::Common::ImplBase::log() [0x562d36b325b5]
  [2020-09-02 10:26:05.492][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: Envoy::TcpProxy::Filter::~Filter() [0x562d3608cfbb]
  [2020-09-02 10:26:05.508][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: __gnu_cxx::new_allocator<>::destroy<>() [0x562d35fbd6cc]
  [2020-09-02 10:26:05.524][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: std::allocator_traits<>::destroy<>() [0x562d35fbd660]
  [2020-09-02 10:26:05.540][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #14: std::_Sp_counted_ptr_inplace<>::_M_dispose() [0x562d35fbd41c]
  [2020-09-02 10:26:05.556][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #15: std::_Sp_counted_base<>::_M_release() [0x562d354fba8c]
  [2020-09-02 10:26:05.571][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #16: std::__shared_count<>::~__shared_count() [0x562d354fba3a]
  [2020-09-02 10:26:05.587][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #17: std::__shared_ptr<>::~__shared_ptr() [0x562d359b836e]
  [2020-09-02 10:26:05.603][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #18: std::shared_ptr<>::~shared_ptr() [0x562d359b76f8]
  [2020-09-02 10:26:05.619][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #19: Envoy::Network::FilterManagerImpl::ActiveReadFilter::~ActiveReadFilter() [0x562d365c2427]
  [2020-09-02 10:26:05.635][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #20: Envoy::Network::FilterManagerImpl::ActiveReadFilter::~ActiveReadFilter() [0x562d365c2213]
  [2020-09-02 10:26:05.651][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #21: Envoy::Network::FilterManagerImpl::ActiveReadFilter::~ActiveReadFilter() [0x562d365c224c]
  [2020-09-02 10:26:05.667][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #22: std::default_delete<>::operator()() [0x562d365bbddf]
  [2020-09-02 10:26:05.683][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #23: std::unique_ptr<>::~unique_ptr() [0x562d365bbd23]
  [2020-09-02 10:26:05.699][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #24: __gnu_cxx::new_allocator<>::destroy<>() [0x562d365bbcc9]
  [2020-09-02 10:26:05.715][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #25: std::allocator_traits<>::destroy<>() [0x562d365bbc20]
  [2020-09-02 10:26:05.731][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #26: std::__cxx11::_List_base<>::_M_clear() [0x562d365bbb7e]
  [2020-09-02 10:26:05.747][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #27: std::__cxx11::_List_base<>::~_List_base() [0x562d365bbafc]
  [2020-09-02 10:26:05.763][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #28: std::__cxx11::list<>::~list() [0x562d365bb638]
  [2020-09-02 10:26:05.779][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #29: Envoy::Network::FilterManagerImpl::~FilterManagerImpl() [0x562d365ba318]
  [2020-09-02 10:26:05.795][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #30: Envoy::Network::ConnectionImpl::~ConnectionImpl() [0x562d365b33a1]
  [2020-09-02 10:26:05.811][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #31: Envoy::Network::ConnectionImpl::~ConnectionImpl() [0x562d365b3533]
  [2020-09-02 10:26:05.827][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #32: Envoy::Network::ConnectionImpl::~ConnectionImpl() [0x562d365b35ec]
  [2020-09-02 10:26:05.843][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #33: std::default_delete<>::operator()() [0x562d3659a4bf]
  [2020-09-02 10:26:05.859][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #34: std::unique_ptr<>::~unique_ptr() [0x562d36593cb3]
  [2020-09-02 10:26:05.875][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #35: Envoy::Server::ConnectionHandlerImpl::ActiveTcpConnection::~ActiveTcpConnection() [0x562d3658fda4]
  [2020-09-02 10:26:05.891][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #36: Envoy::Server::ConnectionHandlerImpl::ActiveTcpConnection::~ActiveTcpConnection() [0x562d3658fe5c]
  [2020-09-02 10:26:05.907][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #37: std::default_delete<>::operator()() [0x562d355fca1f]
  [2020-09-02 10:26:05.923][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #38: std::unique_ptr<>::reset() [0x562d365a5956]
  [2020-09-02 10:26:05.939][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #39: Envoy::Event::DispatcherImpl::clearDeferredDeleteList() [0x562d365a2900]
  [2020-09-02 10:26:05.955][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #40: Envoy::Event::DispatcherImpl::DispatcherImpl()::$_0::operator()() [0x562d365a444c]
  [2020-09-02 10:26:05.971][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #41: std::_Function_handler<>::_M_invoke() [0x562d365a430d]
  [2020-09-02 10:26:05.987][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #42: std::function<>::operator()() [0x562d356c84ae]
  [2020-09-02 10:26:06.003][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #43: Envoy::Event::TimerImpl::TimerImpl()::$_0::operator()() [0x562d365d1ead]
  [2020-09-02 10:26:06.019][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #44: Envoy::Event::TimerImpl::TimerImpl()::$_0::__invoke() [0x562d365d1e56]
  [2020-09-02 10:26:06.035][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #45: event_process_active_single_queue [0x562d36caf9f1]
  [2020-09-02 10:26:06.050][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #46: event_process_active [0x562d36caa0ea]
  [2020-09-02 10:26:06.066][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #47: event_base_loop [0x562d36ca8fbc]
  [2020-09-02 10:26:06.082][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #48: Envoy::Event::LibeventScheduler::run() [0x562d365d0668]
  [2020-09-02 10:26:06.098][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #49: Envoy::Event::DispatcherImpl::run() [0x562d365a3f8a]
  [2020-09-02 10:26:06.114][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #50: Envoy::Server::WorkerImpl::threadRoutine() [0x562d36589eec]
  [2020-09-02 10:26:06.130][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #51: Envoy::Server::WorkerImpl::start()::$_3::operator()() [0x562d3658af4c]
  [2020-09-02 10:26:06.146][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #52: std::_Function_handler<>::_M_invoke() [0x562d3658ae0d]
  [2020-09-02 10:26:06.146][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #53: std::function<>::operator()() [0x562d356c84ae]
  [2020-09-02 10:26:06.162][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #54: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::operator()() [0x562d36f3b9a2]
  [2020-09-02 10:26:06.178][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #55: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x562d36f3b975]
  [2020-09-02 10:26:06.178][22489][critical][backtrace] [bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #56: start_thread [0x7f13543206db]
  Segmentation fault (core dumped)
  ```

  gdb coredump call stack as follow:

  ```
  #0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
  #1  0x0000562f48a25c7b in Envoy::SignalAction::sigHandler (sig=11, info=0x7f9dc4d6f270,
      context=0x7f9dc4d6f140) at source/common/signal/signal_action.cc:74
  #2  <signal handler called>
  #3  0x0000562f489df290 in Envoy::StreamInfo::Utility::formatDownstreamAddressNoPort[abi:cxx11](Envoy::Network::Address::Instance const&) (address=...) at source/common/stream_info/utility.cc:153
  #4  0x0000562f48705f12 in Envoy::AccessLog::StreamInfoFormatter::StreamInfoFormatter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_18::operator()[abi:cxx11](Envoy::StreamInfo::StreamInfo const&) const (this=0x562f4b0bb2f8, stream_info=...)
      at source/common/access_log/access_log_formatter.cc:411
  #5  0x0000562f48705dbb in std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (Envoy::StreamInfo::StreamInfo const&), Envoy::AccessLog::StreamInfoFormatter::StreamInfoFormatter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::$_18>::_M_invoke(std::_Any_data const&, Envoy::StreamInfo::StreamInfo const&) (__functor=..., __args=...)
      at /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/std_function.h:301
  #6  0x0000562f485ef921 in std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (Envoy::StreamInfo::StreamInfo const&)>::operator()(Envoy::StreamInfo::StreamInfo const&) const (this=0x562f4b0bb2f8, __args=...)
  ```

**Comment by huhaipeng** [comment]
this bug has been fixed in v1.14.0
