### ISSUE TITLE
ASAN failure test/common/network/connection_impl_test.cc:116:31

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy#13180]
*Title*: *One line description*
ASAN failure test/common/network/connection_impl_test.cc:116:31

*Description*:

2020-09-18T19:08:40.4740481Z TestRandomGenerator running with seed 1542769512
2020-09-18T19:08:40.4740874Z TestRandomGenerator running with seed 1542769512
2020-09-18T19:08:40.4741913Z test/common/network/connection_impl_test.cc:116:31: runtime error: constructor call on address 0x61a000007140 with insufficient space for an object of type 'Envoy::Network::ClientConnection'
2020-09-18T19:08:40.4742645Z 0x61a000007140: note: pointer points here
2020-09-18T19:08:40.4743137Z  00 00 00 00  be be be be be be be be  be be be be be be be be  00 00 00 00 00 00 00 00  00 00 00 00
2020-09-18T19:08:40.4743575Z               ^ 
2020-09-18T19:08:40.4746304Z     #0 0x33e4460 in std::__1::__unique_if<Envoy::Network::(anonymous namespace)::TestClientConnectionImpl>::__unique_single std::__1::make_unique<Envoy::Network::(anonymous namespace)::TestClientConnectionImpl, Envoy::Event::Dispatcher&, std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<Envoy::Network::Socket::Option const>, std::__1::allocator<std::__1::shared_ptr<Envoy::Network::Socket::Option const> > > >&>(Envoy::Event::Dispatcher&, std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<Envoy::Network::Socket::Option const>, std::__1::allocator<std::__1::shared_ptr<Envoy::Network::Socket::Option const> > > >&) /proc/self/cwd/test/common/network/connection_impl_test.cc:116:31
2020-09-18T19:08:40.4749392Z     #1 0x33e01b3 in Envoy::Network::(anonymous namespace)::ConnectionImplTest::setUpBasicConnection() /proc/self/cwd/test/common/network/connection_impl_test.cc:132:26
2020-09-18T19:08:40.4750311Z     #2 0x3381a68 in Envoy::Network::(anonymous namespace)::ConnectionImplTest_UniqueId_Test::TestBody() /proc/self/cwd/test/common/network/connection_impl_test.cc:271:3
2020-09-18T19:08:40.4751340Z     #3 0x86355c4 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10
2020-09-18T19:08:40.4752263Z     #4 0x86350bf in testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2508:5
2020-09-18T19:08:40.4752946Z     #5 0x863847f in testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2684:11
2020-09-18T19:08:40.4753762Z     #6 0x863bcb9 in testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2816:28
2020-09-18T19:08:40.4754499Z     #7 0x86622a7 in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5338:44
2020-09-18T19:08:40.4755564Z     #8 0x8660f73 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10
2020-09-18T19:08:40.4756680Z     #9 0x8660871 in testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:4925:10
2020-09-18T19:08:40.4757437Z     #10 0x4c3e458 in Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2473:46
2020-09-18T19:08:40.4758056Z     #11 0x4c38e93 in main /proc/self/cwd/test/main.cc:34:10
2020-09-18T19:08:40.4758832Z     #12 0x7ff46cad8b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
2020-09-18T19:08:40.4759852Z     #13 0x3257929 in _start (/b/f/w/bazel-out/k8-opt/bin/test/common/network/connection_impl_test.runfiles/envoy/test/common/network/connection_impl_test+0x3257929)
2020-09-18T19:08:40.4760363Z 
2020-09-18T19:08:40.4761097Z SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test/common/network/connection_impl_test.cc:116:31 in 

*Repro steps*:
https://github.com/envoyproxy/envoy/pull/12546 @ a8aeadd52f8f8885fd2756c091467cdad9167afc
envoy-presubmit (Linux-x64 asan) Failing after 32m — Linux-x64 asan failed

Note: this build is compiled with --config=clang.asan and -C opt --copts -g because of relocation offset overflow during linking which prevents the normal -C dbg --config=clang.asan build from linking.

**Comment by jplevyak** [comment]
Here is another example:

2020-09-22T01:56:45.1443471Z test/common/network/connection_impl_test.cc:116:31: runtime error: constructor call on address 0x61a000007140 with insufficient space for an object of type 'Envoy::Network::ClientConnection'
2020-09-22T01:56:45.1444340Z 0x61a000007140: note: pointer points here
2020-09-22T01:56:45.1444741Z  00 00 00 00  be be be be be be be be  be be be be be be be be  00 00 00 00 00 00 00 00  00 00 00 00
2020-09-22T01:56:45.1445158Z               ^ 
2020-09-22T01:56:45.1447828Z     #0 0x33d4e80 in std::__1::__unique_if<Envoy::Network::(anonymous namespace)::TestClientConnectionImpl>::__unique_single std::__1::make_unique<Envoy::Network::(anonymous namespace)::TestClientConnectionImpl, Envoy::Event::Dispatcher&, std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<Envoy::Network::Socket::Option const>, std::__1::allocator<std::__1::shared_ptr<Envoy::Network::Socket::Option const> > > >&>(Envoy::Event::Dispatcher&, std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>&, std::__1::unique_ptr<Envoy::Network::TransportSocket, std::__1::default_delete<Envoy::Network::TransportSocket> >&&, std::__1::shared_ptr<std::__1::vector<std::__1::shared_ptr<Envoy::Network::Socket::Option const>, std::__1::allocator<std::__1::shared_ptr<Envoy::Network::Socket::Option const> > > >&) /proc/self/cwd/test/common/network/connection_impl_test.cc:116:31
2020-09-22T01:56:45.1450721Z     #1 0x33d0ad3 in Envoy::Network::(anonymous namespace)::ConnectionImplTest::setUpBasicConnection() /proc/self/cwd/test/common/network/connection_impl_test.cc:132:26
2020-09-22T01:56:45.1451556Z     #2 0x3372388 in Envoy::Network::(anonymous namespace)::ConnectionImplTest_UniqueId_Test::TestBody() /proc/self/cwd/test/common/network/connection_impl_test.cc:271:3
2020-09-22T01:56:45.1452666Z     #3 0x8623ec4 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2580:10
2020-09-22T01:56:45.1453516Z     #4 0x86239bf in testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2655:5
2020-09-22T01:56:45.1466985Z     #5 0x8626e14 in testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2832:11
2020-09-22T01:56:45.1467709Z     #6 0x862b319 in testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2986:28
2020-09-22T01:56:45.1468385Z     #7 0x86542a8 in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5697:44
2020-09-22T01:56:45.1469606Z     #8 0x8652dd3 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2580:10
2020-09-22T01:56:45.1470591Z     #9 0x86526d1 in testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5280:10
2020-09-22T01:56:45.1471275Z     #10 0x4c2f388 in Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2485:46
2020-09-22T01:56:45.1471845Z     #11 0x4c29dc3 in main /proc/self/cwd/test/main.cc:34:10
2020-09-22T01:56:45.1472676Z     #12 0x7f88b62cdb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
2020-09-22T01:56:45.1473801Z     #13 0x32455e9 in _start (/b/f/w/bazel-out/k8-opt/bin/test/common/network/connection_impl_test.runfiles/envoy/test/common/network/connection_impl_test+0x32455e9)
