### ISSUE TITLE
Out of disk space on Azure Pipeline

### ISSUE THREAD

**Issue by jplevyak** [envoyproxy/envoy#13212]
##[error]Unhandled exception. System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at Microsoft.VisualStudio.Services.Agent.TraceManager.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.Services.Agent.TraceManager.Dispose()
   at Microsoft.VisualStudio.Services.Agent.HostContext.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.Services.Agent.HostContext.Dispose()
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.Main(String[] args)

Repo:
Linux-x86 gcc               target
https://github.com/envoyproxy/envoy/pull/12546

**Comment by lizan** [comment]
already fixed
