### ISSUE TITLE
Question: Configuration of basic TCP listener

### ISSUE THREAD

**Issue by sptrakesh** [envoyproxy/envoy#13540]
*Title*: *How to configure raw TCP filter?*

*Description*:
Trying to configure a proxy to our custom MQTT broker using filter.   I am not trying to do SSL termination at proxy at present.  Currently client certificate validation logic is built into the broker, so I am looking ideally for a straight pass-through type proxy (currently working with HA Proxy).  Trying to figure out error reported by envoy.  Running via a docker stack with envoy acting as proxy to various containers in the stack.

```
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[2].address) filter_chains: Cannot find field.) has unknown fields
```

The filter configuration is as follows:

```
    - address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8883
        filter_chains:
          - filters:
              - name: envoy.filters.network.tcp_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                  stat_prefix: mqtt_server
                  cluster: mqtt-server
                  idle_timeout: 60s
```

The cluster configuration I am testing with for reference is as follows:

```
    - name: mqtt-server
      connect_timeout: 0.5s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: mqtt-service
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: mqtt-service
                    port_value: 8883
```

**Comment by htuch** [comment]
`filter_chains` is not a property of the address .

**Comment by sptrakesh** [comment]
Thanks, I fixed that issue, and envoy now starts up without error.  However, connection to the MQTT broker fails with SSL related error.  The log from MQTT.fx is as follows:

```
2020-10-14 05:49:37,721 ERROR --- MqttFX ClientModel             : Please verify your Settings (e.g. Broker Address, Broker Port & Client ID) and the user credentials!
org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_181]
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 7 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_181]
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
```

**Comment by sptrakesh** [comment]
It does seem to be SSL related (probably needs a 2 way SSL configuration).  Another raw TCP service which I am proxying (no SSL) works without issues.

**Comment by htuch** [comment]
Have you configured a TLS context on the listener?

**Comment by sptrakesh** [comment]
Following the documentation at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl I configured both downstream and upstream contexts as shown below.  I still get the same error from MQTT.fx

Downstream
```
    - address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8883
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: mqtt_server
                cluster: mqtt-server
                idle_timeout: 300s
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/opt/wirepulse/certs/server.crt"
                    private_key:
                      filename: "/opt/wirepulse/certs/server.key"
                validation_context:
                  trusted_ca:
                    filename: "/opt/wirepulse/certs/ca.crt"
              require_client_certificate: true
```
These are the same server certs that the MQTT broker uses.

Upstream
```
    - name: mqtt-server
      connect_timeout: 0.5s
      type: strict_dns
      lb_policy: random
      load_assignment:
        cluster_name: mqtt-service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: mqtt-service
                      port_value: 8883
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificates:
              - certificate_chain:
                  filename: "/opt/wirepulse/certs/client.crt"
                private_key:
                  filename: "/opt/wirepulse/certs/client.key"
```
These are the same client certificates the MQTT clients use to communicate.

**Comment by htuch** [comment]
Not sure, I can't really debug MQTT. You might want to look at Envoy under `-l trace` to see what is going on around the handshake. Also looking at the handshake under Wireshark could help.

**Comment by sptrakesh** [comment]
For now decided to leave MQTT on HA proxy.
