### ISSUE TITLE
some error when compilation on arm64

### ISSUE THREAD

**Issue by Chwetion** [envoyproxy/envoy#13668]
I met same issue https://github.com/envoyproxy/envoy/pull/12898 when I fast build envoy in aarch64, use branch release/v1.16 @danzh2010 
I use envoyproxy/envoy-build-ubuntu image and [envoy-filter-example](https://github.com/envoyproxy/envoy-filter-example)  to build envoy

```
# run command:
docker pull envoyproxy/envoy-build-ubuntu:b480535e8423b5fd7c102fd30c92f4785519e33a-arm64
mkdir -p /root/source && cd /root/source
git clone https://github.com/envoyproxy/envoy-filter-example.git
cd envoy-filter-example
git submodule update --init
cd envoy
git checkout release/v1.16
docker run --rm -it -v "/root/source":/source --name=envoy-build-env envoyproxy/envoy-build-ubuntu:b480535e8423b5fd7c102fd30c92f4785519e33a-arm64 /bin/bash
cd /source/envoy-filter-example/http-filter-example
bazel build //:envoy
```

```
# error message:
bazel-out/aarch64-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_framer.cc: In member function 'bool quic::QuicFramer::AppendIetfAckFrameAndTypeByte(const quic::QuicAckFrame&, quic::QuicDataWriter*)':
bazel-out/aarch64-fastbuild/bin/external/com_googlesource_quiche/quiche/quic/core/quic_framer.cc:5546:61: error: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int' [-Werror=sign-compare]
 5546 |         static_cast<size_t>(writer->remaining() - ecn_size) <
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
 5547 |             QuicDataWriter::GetVarInt62Len(gap) +
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5548 |                 QuicDataWriter::GetVarInt62Len(ack_range)) {
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: error: unrecognized command line option '-Wno-range-loop-analysis' [-Werror]
cc1plus: all warnings being treated as errors
```

uname -a: `Linux ecs-526c-0002 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by sunjayBhatia** [comment]
Are you configuring Bazel to use the gcc toolchain?

Seems like a similar issue again as https://github.com/envoyproxy/envoy/issues/10422

cc @danzh2010

**Comment by Chwetion** [comment]
no, all step as description @sunjayBhatia 
```
docker pull envoyproxy/envoy-build-ubuntu:b480535e8423b5fd7c102fd30c92f4785519e33a-arm64
mkdir -p /root/source && cd /root/source
git clone https://github.com/envoyproxy/envoy-filter-example.git
cd envoy-filter-example
git submodule update --init
cd envoy
git checkout release/v1.16
docker run --rm -it -v "/root/source":/source --name=envoy-build-env envoyproxy/envoy-build-ubuntu:b480535e8423b5fd7c102fd30c92f4785519e33a-arm64 /bin/bash
cd /source/envoy-filter-example/http-filter-example
bazel build //:envoy
```

**Comment by Chwetion** [comment]
I successfully compiled the binary file by modifying the bazel/envoy_internal.bzl file. But I don't know if this will affect the binary.
Edit: commented out Werror.
```
...
# Compute the final copts based on various options.
def envoy_copts(repository, test = False):
    posix_options = [
        "-Wall",
        "-Wextra",
#       "-Werror",
        "-Wnon-virtual-dtor",
        "-Woverloaded-virtual",
        "-Wold-style-cast",
        "-Wformat",
        "-Wformat-security",
        "-Wvla",
    ]
...
```

**Comment by sunjayBhatia** [comment]
I think you will find given the path setup in that container image and the fact that you're not passing `--config=clang` to `bazel build` you are still building with GCC (just tried it and verified)

Now the fact that `bazel build <envoy target>` doesn't "just work" in the build container is not great

To get around your initial issues and not remove `-Werror`, I would run `bazel build --config=clang <build target>`

**Comment by sunjayBhatia** [comment]
We could add some CI verification that `bazel build <...>` without any decoration "just works" at least from within the build container image

**Comment by Chwetion** [comment]
Hi @sunjayBhatia, i try to run `bazel build --config=clang //:envoy` replace `bazel build //:envoy` step , but met some error as follow: 
```
ERROR: /root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/com_googlesource_quiche/BUILD.bazel:544:17: C++ compilation of rule '@com_googlesource_quiche//:http2_hpack_decoder_hpack_decoding_error_lib' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 96 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error: unrecognized command line option '-fno-limit-debug-info'
gcc: error: unrecognized command line option '-Wgnu-conditional-omitted-operand'
gcc: error: unrecognized command line option '-Wc++2a-extensions'; did you mean '-fms-extensions'?
gcc: error: unrecognized command line option '-Wrange-loop-analysis'
Target //:envoy failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 96.091s, Critical Path: 15.38s
INFO: 348 processes: 348 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by sunjayBhatia** [comment]
Ah my bad, I forgot it is not that simple

You may be best served following the instructions here: https://github.com/envoyproxy/envoy/tree/master/ci#on-linux

The `./ci/do_ci.sh` script sets up the build environment and toolchains for you

**Comment by Chwetion** [comment]
but i need compile my out tree filter, as https://github.com/envoyproxy/envoy-filter-example.

**Comment by sunjayBhatia** [comment]
Ah yes, a similar pattern is available for the filter example if you take a look at the CI configuration here: https://github.com/envoyproxy/envoy-filter-example/blob/b9b73e2907f64c6dc15a53d5c0bccf11e1cc3820/.circleci/config.yml

which should do setup of the bits needed in this script: https://github.com/envoyproxy/envoy-filter-example/blob/b9b73e2907f64c6dc15a53d5c0bccf11e1cc3820/ci/do_ci.sh

looks like the environment variables and compiler setup happens at the top, if this doesn't work we should bother the authors/maintainers of this rep as it looks like CI has been red for a while as well

**Comment by Chwetion** [comment]
@sunjayBhatia I use `"./ci/do_ci.sh build"`(at envoy-filter-example dir) replace `bazel build //:envoy`(at envoy-filter-example/envoy dir) step, still error:
```
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125
		configure_unix_toolchain(<3 more arguments>)
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 352, in configure_unix_toolchain
		_find_generic(repository_ctx, <3 more arguments>)
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 322, in _find_generic
		auto_configure_fail(msg)
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, in auto_configure_fail
		fail(<1 more arguments>)

Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: /root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/BUILD:469:14: @bazel_tools//tools/cpp:compiler depends on @local_config_cc//:cc-compiler-aarch64 in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125
		configure_unix_toolchain(<3 more arguments>)
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 352, in configure_unix_toolchain
		_find_generic(repository_ctx, <3 more arguments>)
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 322, in _find_generic
		auto_configure_fail(msg)
	File "/root/.cache/bazel/_bazel_root/19f15e35caa486164d08070e840bf9f2/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, in auto_configure_fail
		fail(<1 more arguments>)

Auto-Configuration Error: Cannot find gcc or CC (clang); either correct your path or set the CC environment variable
ERROR: Analysis of target '//:envoy' failed; build aborted: Analysis failed
INFO: Elapsed time: 31.098s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 148 targets configured)
```
maybe I should ask in another project

**Comment by Chwetion** [comment]
@sunjayBhatia sorry i found out that this is a problem caused by the development branch I pulled, when I switched to `git checkout v1.16.0`, all ok. thx.

**Comment by NomadXD** [comment]
I am having the same issue as above. I tried it on Ubuntu 20.04 and Manjaro linux as well. Still no luck. So as I think it occurs because gcc doesn't know about -Wrange-loop-analysis flag and it raises the error. I'm using gcc 9.30. Maybe should try it with gcc 10
