### ISSUE TITLE
Docker Compose not working on envoy/examples/ext_authz

### ISSUE THREAD

**Issue by pawanyoda** [envoyproxy/envoy#14492]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *DockerCompose not working on envoy/examples/ext_authz*

*Description*:
>While running this command `docker-compose up --build -d` not able to build ext_authz.
>Getting error:
```
➜  ext_authz git:(master) ✗ docker-compose up --build -d
Building front-envoy
Traceback (most recent call last):
  File "site-packages/docker/credentials/store.py", line 80, in _execute
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/Users/pawankumar/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/docker-credential-gcloud', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/docker/credentials/store.py", line 35, in get
  File "site-packages/docker/credentials/store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-gcloud exited with "You do not currently have an active account selected. See https://cloud.google.com/sdk/docs/authorizing for more information.".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 346, in ensure_image_exists
  File "compose/service.py", line 1125, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 311, in get_all_credentials
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "You do not currently have an active account selected. See https://cloud.google.com/sdk/docs/authorizing for more information.".')
[15758] Failed to execute script docker-compose
```
I am able to do docker-compose other projects like ratelimit and envoyproxy.

```
docker version:
docker version                                                                                                 
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
hi @pawanyoda thanks for reporting this, i can look into it - its working in ci so im not sure  exactly why its failing - but ill test locally

/assign phlax

**Comment by dio** [comment]
@pawanyoda seems like this issue here: https://github.com/docker/compose/issues/5930#issuecomment-724525064 is related? Not sure why it only happens for the `ext_authz` example.

**Comment by mk46** [comment]
Hi @pawanyoda Try to install docker-compose by [pip](https://docs.docker.com/compose/install/#install-using-pip)

**Comment by hakuno** [comment]
I guess it is related to Docker Compose itself.

Some time ago I also had some trouble with https://github.com/docker/for-win/issues/9561

Plus, you got some error message

```
'Credentials store docker-credential-gcloud exited with "You do not currently have an active account selected. See https://cloud.google.com/sdk/docs/authorizing for more information.".'
```

**Comment by phlax** [comment]
@pawanyoda can you confirm if any of the fixes/workarounds in https://github.com/docker/compose/issues/5930 resolve the issue ?
