### ISSUE TITLE
Could not build the main branch after pulling the latest changes

### ISSUE THREAD

**Issue by alishir** [envoyproxy/envoy#14990]
*Title*: Could not build the main branch after pulling the latest changes

*Description*:
> I've built envoy with `ENVOY_DOCKER_BUILD_DIR=~/build ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'` successfully. Today I pulled the latest changes and try to build the project with that command and I got following errors:

```
❯ ENVOY_DOCKER_BUILD_DIR=~/build ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'                                                                            08:34:05
No remote cache is set, skipping setup remote cache.
ENVOY_SRCDIR=/source
ENVOY_BUILD_TARGET=//source/exe:envoy-static
ENVOY_BUILD_ARCH=x86_64
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
HEAD is now at 30e5df3 config: update configs for v3 readiness. (#137)
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
building using 6 CPUs
building for x86_64
clang toolchain with libc++ configured
bazel fastbuild build with tests...
Building...
Building...
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
DEBUG: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /build/tmp/_bazel_envoybuild/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
ERROR: Traceback (most recent call last):
        File "/source/source/extensions/compression/brotli/compressor/BUILD", line 24, column 19, in <toplevel>
                envoy_cc_extension(
        File "/source/bazel/envoy_library.bzl", line 124, column 13, in envoy_cc_extension
                fail("Category not set for %s" % name)
Error in fail: Category not set for config
ERROR: Traceback (most recent call last):
        File "/source/source/extensions/compression/brotli/decompressor/BUILD", line 26, column 19, in <toplevel>
                envoy_cc_extension(
        File "/source/bazel/envoy_library.bzl", line 124, column 13, in envoy_cc_extension
                fail("Category not set for %s" % name)
Error in fail: Category not set for config
ERROR: /source/source/exe/BUILD:28:17: no such target '//source/extensions/compression/brotli/compressor:config_envoy_extension': target 'config_envoy_extension' not declared in package 'source/extensions/compression/brotli/compressor' defined by /source/source/extensions/compression/brotli/compressor/BUILD and referenced by '//source/exe:envoy_common_lib'
ERROR: /source/source/exe/BUILD:28:17: no such target '//source/extensions/compression/brotli/decompressor:config_envoy_extension': target 'config_envoy_extension' not declared in package 'source/extensions/compression/brotli/decompressor' defined by /source/source/extensions/compression/brotli/decompressor/BUILD and referenced by '//source/exe:envoy_common_lib'
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.360s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (283 packages loaded, 8960 targets configured)
    currently loading: @com_github_grpc_grpc//
```

**Comment by rojkov** [comment]
This has been already fixed with #14987
