### ISSUE TITLE
Poor error message when extension category missing

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#15081]
```
Traceback (most recent call last):
  File "./docs/generate_extension_db.py", line 86, in <module>
    extension_db[extension] = GetExtensionMetadata(target)
  File "./docs/generate_extension_db.py", line 70, in GetExtensionMetadata
    ('[' in categories or '(' in categories) else [categories])
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x7fa20d053518>
```

when the `category` field is missing from `envoy_cc_extension` target.

**Comment by snowp** [comment]
@phlax
