### ISSUE TITLE
Unable to build docs locally.

### ISSUE THREAD

**Issue by mk46** [envoyproxy/envoy#15536]
Followed https://github.com/envoyproxy/envoy/tree/main/docs#building-documentation-locally.
Command `./docs/build.sh`  throw exception 
```
INFO: Build completed successfully, 1 total action
Envoy source must either be located at /source, or ENVOY_SRCDIR env var must be set
Traceback (most recent call last):
  File "/home/necuser/.cache/bazel/_bazel_necuser/213e71b2d087549d893f7fdc744ab64d/execroot/envoy/bazel-out/k8-fastbuild/bin/tools/extensions/generate_extension_rst.runfiles/envoy/tools/extensions/generate_extension_rst.py", line 35, in <module>
    subprocess.run("tools/extensions/generate_extension_db".split(), check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)

```

**Comment by mk46** [comment]
CC @phlax

**Comment by phlax** [comment]
hmm - as a workaround for now you can do

```
export `ENVOY_SRCDIR=$(pwd)
./docs/build.sh

```

**Comment by mk46** [comment]
@phlax Thanks. Should we mention the same in https://github.com/envoyproxy/envoy/tree/main/docs#building-documentation-locally as of now?

**Comment by mattklein123** [comment]
I think the error message is pretty clear but please feel free to update the link above.
