### ISSUE TITLE
Getting errors from envoy proxy with istio 1.9.1 version on GRPC web service

### ISSUE THREAD

**Issue by akhilgoel09** [envoyproxy/envoy#16222]
Hi Guys,

I am using istio 1.9.1 and getting the below errors from my web service:

istio-grpc-error logs:

[2021-04-28T23:17:13.094Z] "POST /int.expre.subscriptions.v1.SubscriptionService/GetSubscriptionsForAccount HTTP/2" 415 UR upstream_reset_after_response_started{remote_reset} - "-" 60 0 5 4 "172.20.49.218" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Mobile Safari/537.36" "62efd112-2004-955f-8a81-a9773cc7ef8d" "subscription.staging.expressplay.com" "100.102.102.179:9201" outbound|80||subscription-service.cap-staging.svc.cluster.local 100.97.224.11:37818 100.97.224.11:8443 172.20.49.218:56345 subscription.staging.expressplay.com -

Service error logs:

2021-04-28 23:14:57.403  WARN 1 --- [-worker-ELG-1-1] i.g.n.s.i.grpc.netty.NettyServerHandler  : Expected header TE: trailers, but null is received. This means some intermediate proxy may not support trailers
2021-04-28 23:14:57.430  WARN 1 --- [-worker-ELG-1-1] i.g.n.s.i.grpc.netty.NettyServerHandler  : Exception in onDataRead()
java.lang.NullPointerException: null
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:476) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.access$800(NettyServerHandler.java:101) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:787) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:292) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378) ~[grpc-netty-shaded-1.24.0.jar!/:1.24.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) ~[grpc-netty-shaded-

On  web page error:

  grpc-message: Content-Type 'application/grpc-web-text' is not supported

My envoy.yml file:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: subscription-service
spec:
  workloadLabels:
    app: subscription-service
  filters:
  - listenerMatch:
      listenerType: ANY
      listenerProtocol: HTTP
    insertPosition:
      index: FIRST
    filterType: HTTP
    filterName: "envoy.filters.http.grpc_web"
    filterConfig: {}
```

can anybody help with this issue?

**Comment by yanavlasov** [comment]
@fengli79 @lizan may be able to help with the grpc-web filter

**Comment by akhilgoel09** [comment]
sure, it will be a great help if you can.

**Comment by vitruvvius** [comment]
+1

**Comment by GNUGradyn** [comment]
+1
