### ISSUE TITLE
protobuf deserialize failure with non UTF-8 message on tracing span

### ISSUE THREAD

**Issue by Shikugawa** [envoyproxy/envoy#16254]
*Description*:
Protobuf deserialize failure will be occurred with non UTF-8 character on gRPC message on tracing span. This problem won't be a problem except for SkyWalking tracer because they don't use gRPC as transport. For more detail, this problem will occur here.

https://github.com/envoyproxy/envoy/blob/main/source/common/tracing/http_tracer_impl.cc#L159-L188

*Repro steps*:
1. Run skywalking sandbox
2. Request `for i in $(seq 1 100); do curl localhost:8000/trace/1 -o /dev/null; done`
3. We can see this error

Envoy side
```
service1_1        | [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'KeyStringValuePair.value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
```

SkyWalking side
```
skywalking-oap_1  | io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
skywalking-oap_1  |     at io.grpc.Status.asRuntimeException(Status.java:524)
skywalking-oap_1  |     at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
skywalking-oap_1  |     at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
skywalking-oap_1  |     at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:296)
skywalking-oap_1  |     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
skywalking-oap_1  |     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
skywalking-oap_1  |     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
skywalking-oap_1  |     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
skywalking-oap_1  |     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
skywalking-oap_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
skywalking-oap_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
skywalking-oap_1  |     at java.base/java.lang.Thread.run(Thread.java:834)
skywalking-oap_1  | Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
skywalking-oap_1  |     at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:141)
skywalking-oap_1  |     at com.google.protobuf.Utf8$DecodeUtil.handleTwoBytes(Utf8.java:1909)
skywalking-oap_1  |     at com.google.protobuf.Utf8$DecodeUtil.access$700(Utf8.java:1883)
skywalking-oap_1  |     at com.google.protobuf.Utf8$UnsafeProcessor.decodeUtf8(Utf8.java:1411)
skywalking-oap_1  |     at com.google.protobuf.Utf8.decodeUtf8(Utf8.java:340)
skywalking-oap_1  |     at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:809)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.common.v3.KeyStringValuePair.<init>(KeyStringValuePair.java:60)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.common.v3.KeyStringValuePair.<init>(KeyStringValuePair.java:9)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.common.v3.KeyStringValuePair$1.parsePartialFrom(KeyStringValuePair.java:676)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.common.v3.KeyStringValuePair$1.parsePartialFrom(KeyStringValuePair.java:670)
skywalking-oap_1  |     at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:888)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SpanObject.<init>(SpanObject.java:135)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SpanObject.<init>(SpanObject.java:16)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SpanObject$1.parsePartialFrom(SpanObject.java:3128)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SpanObject$1.parsePartialFrom(SpanObject.java:3122)
skywalking-oap_1  |     at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:888)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject.<init>(SegmentObject.java:82)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject.<init>(SegmentObject.java:16)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject$1.parsePartialFrom(SegmentObject.java:1656)
skywalking-oap_1  |     at org.apache.skywalking.apm.network.language.agent.v3.SegmentObject$1.parsePartialFrom(SegmentObject.java:1650)
skywalking-oap_1  |     at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
skywalking-oap_1  |     at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
skywalking-oap_1  |     at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
skywalking-oap_1  |     at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
skywalking-oap_1  |     ... 10 more
skywalking-oap_1  | 
```

**Comment by Shikugawa** [comment]
In addition, we found that the value of `http.method` span tag has trailing malformed character. This is why we faced UTF-8 deserialize failure.

```
front-envoy_1     |   tags {
front-envoy_1     |     key: "http.method"
front-envoy_1     |     value: "GET\\#\177"
front-envoy_1     |   }
```
