### ISSUE TITLE
Build error on mac os

### ISSUE THREAD

**Issue by Patrick0308** [envoyproxy/envoy#16768]
*Description*:
Building error on mac os. Commit id is `1a05155c4`

*Repro steps*:
```BASH 
$ tools/vscode/refresh_compdb.sh
```

*Admin and Stats Output*:

```
❯ tools/vscode/refresh_compdb.sh
Skipping proto_format.sh due to no API change
$TEST_TMPDIR defined: output root default is '/tmp/envoy-compdb' and max_idle_secs default is '15'.
$TEST_TMPDIR defined: output root default is '/tmp/envoy-compdb' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
DEBUG: /private/tmp/envoy-compdb/_bazel_jiangchao/5e5c70090c71b56a3789e051dded47eb/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/tmp/envoy-compdb/_bazel_jiangchao/5e5c70090c71b56a3789e051dded47eb/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/tmp/envoy-compdb/_bazel_jiangchao/5e5c70090c71b56a3789e051dded47eb/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/tmp/envoy-compdb/_bazel_jiangchao/5e5c70090c71b56a3789e051dded47eb/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/tmp/envoy-compdb/_bazel_jiangchao/5e5c70090c71b56a3789e051dded47eb/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
INFO: Analyzed 3115 targets (1479 packages loaded, 99102 targets configured).
INFO: Found 3115 targets...
ERROR: /private/tmp/envoy-compdb/_bazel_jiangchao/5e5c70090c71b56a3789e051dded47eb/external/com_google_protobuf/BUILD:129:11: Compiling src/google/protobuf/io/coded_stream.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 33 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_protobuf/src/google/protobuf/io/coded_stream.cc:954:27: error: out-of-line definition of 'WriteVarint32ToArrayOutOfLineHelper' does not match any declaration in 'google::protobuf::io::CodedOutputStream'
uint8* CodedOutputStream::WriteVarint32ToArrayOutOfLineHelper(uint32 value,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
INFO: Elapsed time: 270.931s, Critical Path: 6.74s
INFO: 578 processes: 573 internal, 5 darwin-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/jiangchao/Projects/envoy/tools/gen_compilation_database.py", line 98, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "/Users/jiangchao/Projects/envoy/tools/gen_compilation_database.py", line 20, in generate_compilation_database
    subprocess.check_call(["bazel", "build"] + bazel_options + [
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--config=compdb', '--remote_download_outputs=all', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//source/...', '//test/...', '//tools/...']' returned non-zero exit status 1.

**Comment by junr03** [comment]
The protobuf dep was recently updated, has bazel correctly downloaded the new dep in your build? Have you tried busting the cache and building from clean state?

**Comment by Patrick0308** [comment]
I try 
```bash
$ git checkout main
$ git pull
$ bazel clean --expunge
$ tools/vscode/refresh_compdb.sh
```
It's not useful.

**Comment by Patrick0308** [comment]
Updating protobuf to 3.17.3 resolved this problem.
