### ISSUE TITLE
Upgrade to 1.18, HTTP Post 4xx failures

### ISSUE THREAD

**Issue by khushbr** [envoyproxy/envoy#18257]
*Description*:
We are trying to upgrade our service to Envoy 1.18. As part of testing, we noticed the Envoy throwing large count of 4xx.

On the surface level, no breaking changes from [1.18.0 release](https://www.envoyproxy.io/docs/envoy/v1.19.0/version_history/v1.18.0) are impacting us. The documentation mentions `grpc_json_transcoder: the filter now adheres to encoder and decoder buffer limits. Requests and responses that require buffering over the limits will be directly rejected` but we do not use the `grpc_json_transcoder`. The below error indicates a buffering limit breach and I am wondering if a limit was added/updated in 1.18.0 version. 

Error Log:
```
[Thu Apr 22 20:58:31.811612 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946] [ERROR] deep_pltr_inference_service._flask._view internal error:
[Thu Apr 22 20:58:31.811630 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946] Traceback (most recent call last):
[Thu Apr 22 20:58:31.811633 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]   File "/opt/amazon/lib/python3.7/site-packages/deep_pltr_inference_service/_flask/_view.py", line 77, in alt_keyword_response
[Thu Apr 22 20:58:31.811636 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]     request_json = flask.request.json
[Thu Apr 22 20:58:31.811639 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]   File "/opt/amazon/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
[Thu Apr 22 20:58:31.811642 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]     return getattr(self._get_current_object(), name)
[Thu Apr 22 20:58:31.811646 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]   File "/opt/amazon/lib/python3.7/site-packages/werkzeug/wrappers/json.py", line 69, in json
[Thu Apr 22 20:58:31.811649 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]     return self.get_json()
[Thu Apr 22 20:58:31.811651 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]   File "/opt/amazon/lib/python3.7/site-packages/werkzeug/wrappers/json.py", line 116, in get_json
[Thu Apr 22 20:58:31.811653 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]     data = self._get_data_for_json(cache=cache)
[Thu Apr 22 20:58:31.811655 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]   File "/opt/amazon/lib/python3.7/site-packages/werkzeug/wrappers/json.py", line 85, in _get_data_for_json
[Thu Apr 22 20:58:31.811658 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]     return self.get_data(cache=cache)
[Thu Apr 22 20:58:31.811660 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]   File "/opt/amazon/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 456, in get_data
[Thu Apr 22 20:58:31.811662 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946]     rv = self.stream.read()
[Thu Apr 22 20:58:31.811664 2021] [wsgi:error] [pid 409] [client 172.17.0.5:35946] OSError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
```
Also to add, we did not change anything else in the setup, only Envoy version was upgraded.
*Current Envoy Version*  : 1.17.1

**Comment by wbpcode** [comment]
Can you provide some Envoy debug logs?
