### ISSUE TITLE
Dev Container APT is broken due to missing ISRG Root X1 CA cert

### ISSUE THREAD

**Issue by terorie** [envoyproxy/envoy#18388]
*Title*: Dev Container APT is broken, presumably due to missing ISRG Root X1 CA cert*

*Description*:
> Creating a GitHub codespace for Envoy on the latest main branch fails because the dev container fails to initialize.

I am 90% sure this happens because https://apt.kitware.com uses Let's Encrypt.
As of Oct 1, Let's Encrypt certificates require trusting the ISRG Root X1 CA cert.
A lot of the Internet has recently broken because clients were relying on the old CA cert that's now gone and don't support ISRG Root X1.

*Repro steps*:
1. Create GitHub codespace for Envoy
2. Wait for failure in dev container deploy log

*Logs*:
```
[2021-10-03T13:38:12.097Z] Ign:25 https://apt.kitware.com/ubuntu bionic InRelease
[2021-10-03T13:38:12.282Z] Err:26 https://apt.kitware.com/ubuntu bionic Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 66.194.253.25 443]
[2021-10-03T13:38:12.295Z] Reading package lists...
[2021-10-03T13:38:13.262Z] 
[2021-10-03T13:38:13.298Z] E: The repository 'https://apt.kitware.com/ubuntu bionic Release' does not have a Release file.
[2021-10-03T13:38:14.172Z] The command '/bin/sh -c apt-get -y update   && apt-get -y install --no-install-recommends libpython2.7 net-tools psmisc vim 2>&1   && groupadd --gid $USER_GID $USERNAME   && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME -G pcap -d /build   && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME   && chmod 0440 /etc/sudoers.d/$USERNAME' returned a non-zero code: 100
Error: Command failed: docker build -f /var/lib/docker/codespacemount/workspace/envoy/.devcontainer/Dockerfile -t vsc-envoy-096e7d00c883c7d75643432988258e64 /var/lib/docker/codespacemount/workspace/envoy/.devcontainer
    at L7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:294:7730)
    at async N7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:294:6033)
    at async zk (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:294:2393)
    at async h7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:288:10387)
    at async vV (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:308:7554)
    at async Vce (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:308:26973)
    at async Gce (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:308:26568)
[2021-10-03T13:38:14.175Z] Stop (123061 ms): Run: docker build -f /var/lib/docker/codespacemount/workspace/envoy/.devcontainer/Dockerfile -t vsc-envoy-096e7d00c883c7d75643432988258e64 /var/lib/docker/codespacemount/workspace/envoy/.devcontainer
Failed to create container.Error: Command failed: docker build -f /var/lib/docker/codespacemount/workspace/envoy/.devcontainer/Dockerfile -t vsc-envoy-096e7d00c883c7d75643432988258e64 /var/lib/docker/codespacemount/workspace/envoy/.devcontainerError Code: 1302Container creation failed.
2021-10-03T13:38:14: Creating recovery container.
2021-10-03T13:38:14: 
```

**Comment by phlax** [comment]
seems like the kitware certs were renewed on 1/10 https://certificatedetails.com/f91af050894905d9939a533aabcb0daa6a195623fb725b99956042f0c1f0b866/apt.kitware.com

not sure if its that cert that is at issue, but hopefully if we give the build image a kick it will update...

**Comment by phlax** [comment]
testing this further i was able to reproduce with the current image (as described)

there is already a newer image in dockerhub and this appears to fix the issue
