### ISSUE TITLE
CI: Verify examples failing

### ISSUE THREAD

**Issue by KBaichoo** [envoyproxy/envoy#20037]
CI: Verify examples failing

*Description*:
See CI runs for the following PRs: [19944](https://dev.azure.com/cncf/envoy/_build/results?buildId=101877&view=results), [19868](https://dev.azure.com/cncf/envoy/_build/results?buildId=101889&view=results), [20017](https://dev.azure.com/cncf/envoy/_build/results?buildId=101918&view=results)

All end with
```
run_examples@ /home/vsts/work/1/s/ci/verify_examples.sh :39 (./locality-load-balancing)
 
 > main@ /home/vsts/work/1/s/ci/verify_examples.sh :44
 
The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.


```

**Comment by phlax** [comment]
appears to be transient pypi issues

```console
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-n_p0nsic/MarkupSafe/
The command '/bin/sh -c pip3 install -q flask' returned a non-zero code: 1
Service 'service' failed to build : Build failed
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=101877&view=logs&j=f1a49366-51c0-540f-0294-f73c2bb311a9&t=7fd036c9-61ec-5b59-3645-e90950dc67a6&l=466

**Comment by phlax** [comment]
hmm, seems more like this version of flask is broken

```
$ pip install Flask==0.11.1
Collecting Flask==0.11.1
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 1.6 MB/s            
Collecting Werkzeug>=0.7
  Downloading Werkzeug-2.0.3-py3-none-any.whl (289 kB)
     |████████████████████████████████| 289 kB 1.2 MB/s            
Collecting itsdangerous>=0.21
  Downloading itsdangerous-2.1.0-py3-none-any.whl (15 kB)
Requirement already satisfied: click>=2.0 in /home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages (from Flask==0.11.1) (8.0.1)
Requirement already satisfied: Jinja2>=2.4 in /home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages (from Flask==0.11.1) (3.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages (from Jinja2>=2.4->Flask==0.11.1) (2.0.1)
Installing collected packages: Werkzeug, itsdangerous, Flask
Successfully installed Flask-0.11.1 Werkzeug-2.0.3 itsdangerous-2.1.0
WARNING: You are using pip version 21.3; however, version 22.0.3 is available.
You should consider upgrading via the '/home/phlax/.virtualenvs/envoydev/bin/python -m pip install --upgrade pip' command.
(envoydev) phlax@iota:~/.virtualenvs/envoydev/envoy/examples$ python
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
Traceback (most recent call last):
  File "/home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages/flask/json.py", line 23, in <module>
    from itsdangerous import simplejson as _json
ImportError: cannot import name 'simplejson' from 'itsdangerous' (/home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages/itsdangerous/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages/flask/app.py", line 27, in <module>
    from . import json, cli
  File "/home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages/flask/json.py", line 25, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/phlax/.virtualenvs/envoydev/lib/python3.9/site-packages/itsdangerous/__init__.py)

```

ill raise a PR to fix
