### ISSUE TITLE
generate compile_commands.json fail with python 3.10.3

### ISSUE THREAD

**Issue by ydzhou** [envoyproxy/envoy#20750]
*Description*:
Run `./tools/gen_compilation_database.py` and getting errors on `importlib.metadata`

* Python version: `pyenv 3.10.3`
* OS: `mac os 12.3`
* Arch: `arm64 M1 Mac`

I searched one issues before and looks like this dependency is not required for `python 3.10+`. But I am getting this error. Any help please?

```
ERROR: /Users/yzhou6/Dev/tmp/envoy-compdb/_bazel_yzhou6/5c85f84c18b6621ee123c3ae6e46d441/external/base_pip3_sphinx/BUILD.bazel:22:11: no such package '@base_pip3_importlib_metadata//': The repository '@base_pip3_importlib_metadata' could not be resolved: Repository '@base_pip3_importlib_metadata' is not defined and referenced by '@base_pip3_sphinx//:pkg'
ERROR: Analysis of target '//tools/docs:sphinx_runner' failed; build aborted: 
INFO: Elapsed time: 6.354s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1043 packages loaded, 35714 targets configured)
    currently loading: @base_pip3_pycodestyle// ... (4 packages)
    Fetching @base_pip3_aiohttp; fetching
    Fetching @com_github_lyft_protoc_gen_star; Restarting.
    Fetching @bazel_gazelle_go_repository_config; Restarting.
    Fetching @bazel_gazelle_go_repository_tools; fetching
    Fetching @local_config_xcode; Fetching SDK information for Xcode 13.3.0.13E113
    Fetching @base_pip3_pynacl; fetching
    Fetching @base_pip3_mccabe; fetching
    Fetching @base_pip3_uritemplate; fetching ... (10 fetches)
Traceback (most recent call last):
  File "/Users/yzhou6/Dev/envoy/./tools/gen_compilation_database.py", line 124, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "/Users/yzhou6/Dev/envoy/./tools/gen_compilation_database.py", line 20, in generate_compilation_database
    subprocess.check_call(["bazel", "build"] + bazel_options + [
  File "/Users/yzhou6/.pyenv/versions/3.10.3/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--config=compdb', '--remote_download_outputs=all', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//source/...', '//test/...', '//tools/...', '//contrib/...']' returned non-zero exit status 1.
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by phlax** [comment]
assuming you are using vscode - i think the problem is that you need to rebuild the container image used by vscode

https://code.visualstudio.com/docs/remote/create-dev-container#_rebuild

**Comment by ydzhou** [comment]
I do not use vscode

**Comment by phlax** [comment]
the problem is that bazel is not using python 3.10 - the importlib-metadata demonstrates that

beneath it says python3.10 because that is what is being invoked with the script, but not by bazel

i also dont use vscode, but i helped debug this for a vscode user - and it seems as tho the reason for them at least was that the container that vscode uses to run ci commands in needed rebuilding

not sure in your environment why this is the case but could you post the results of

```console
$ which python3
$ python3 -V
```

to see what the system thinks it should use for python3

**Comment by ydzhou** [comment]
Interesting... I am using `pyenv` to manage python version.
```
> which python3
/Users/yzhou6/.pyenv/shims/python3
> python -V
Python 3.10.3
```
Also I tried to use homebrew one, still facing the same error:
```
TEST_TMPDIR=~/Dev/tmp/envoy-compdb /opt/homebrew/opt/python@3.10/bin/python3 ./tools/gen_compilation_database.py
```

```

**Comment by phlax** [comment]
so i think the it doesnt see your user install when running bazel - you need to make that the system-wide python3 - not sure beyond that, im also not a mac user

what does root get for python3 ?

**Comment by ydzhou** [comment]
I am not sure if there is a way (or I am allowed) to switch to root in the mac os

**Comment by phlax** [comment]
one option is to use the ci build image (requires docker) 

```console
$ ./ci/run_envoy_docker.sh 'tools/gen_compilation_database.py'
```

we are currently working on adding bazel python toolchains (#20432 ) which should resolve this for bazel more correctly/portably

for now tho - you will need to ensure - one way or other - that when you invoke bazel it sees the correct python3

**Comment by ydzhou** [comment]
Do you have a guidance on how to use CI build image for mac os? I only see the linux or windows options.

I tried to apply your toolchain change and is getting a new error on `Building wheel for multidict (pyproject.toml) did not run successfully`.

Do you happen to have any insight?

**Comment by phlax** [comment]
> Do you have a guidance on how to use CI build image for mac os? I only see the linux or windows options.

the instructions for the linux image should be roughly the same on all platforms (there is separate docs for the windows _image_)

re other error - not sure - not something i have seen before - happy to look further if you post more info

this may be a mac-bazel related issue re toolchains so it would be great to track that down if it was the case

**Comment by phlax** [comment]
re the original issue - the underlying problem is definitely that the version of python3 seen by bazel is not 3.10

**Comment by phlax** [comment]
currently blocked by a windows issue, but as mentioned would be good to know whether it causes any platform issues outside of CI 

im testing locally on linux (and in linux images) and it passes mac CI - but that is a somewhat limited test

**Comment by sergiitk** [comment]
Found the problem, see #21369. Until it's merged, there's an easy workaround, create `user.bazelrc` with the following:

```
build:macos --action_env=PATH=/opt/homebrew/bin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin
build:macos --host_action_env=PATH=/opt/homebrew/bin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin
```

Make sure the first path with `python3`binary points to python3.10. You can verify this with a target like so:

```
genrule(
    name = "which_python3",
    outs = ["which_python3.txt"],
    cmd = "which python3"
)
```
