### ISSUE TITLE
How to debug envoy？

### ISSUE THREAD

**Issue by tuhao1020** [envoyproxy/envoy#21100]
I compiled the envoy binaries using docker image with following command:
```
ENVOY_DOCKER_BUILD_DIR=~/build ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.debug.server_only'
```
but how to debug its code using break points in vscode?

**Comment by lizan** [comment]
Are you using devcontainer for that?

https://github.com/envoyproxy/envoy/tree/main/tools/vscode#generate-debug-config have document for generating debug config for vscode.

**Comment by tuhao1020** [comment]
@lizan  I tried `tools/vscode/refresh_compdb.sh` several times but they all failed, looks like network problem. I'll try again later.

**Comment by tuhao1020** [comment]
```
INFO: Repository com_googlesource_code_re2 instantiated at:
  /workspaces/envoy/WORKSPACE:13:19: in <toplevel>
  /workspaces/envoy/bazel/repositories.bzl:212:9: in envoy_dependencies
  /workspaces/envoy/bazel/repositories.bzl:994:26: in _re2
  /workspaces/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: /workspaces/envoy/tools/docs/BUILD:42:18: //tools/docs:entry_point_sphinx_runner_wrapper depends on @base_pip3_envoy_docs_sphinx_runner//:rules_python_wheel_entry_point_envoy.docs.sphinx_runner in repository @base_pip3_envoy_docs_sphinx_runner which failed to fetch. no such package '@base_pip3_envoy_docs_sphinx_runner//': whl_library base_pip3_envoy_docs_sphinx_runner failed:  (ERROR: Exception:
Traceback (most recent call last):
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/requests/adapters.py", line 193, in proxy_manager_for
    manager = self.proxy_manager[proxy] = proxy_from_url(
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/urllib3/poolmanager.py", line 536, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/urllib3/poolmanager.py", line 480, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
pip._vendor.urllib3.exceptions.ProxySchemeUnknown: Proxy URL had no scheme, should start with http:// or https://

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/commands/wheel.py", line 142, in run
    requirement_set = resolver.resolve(
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/resolvelib/resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/resolvelib/structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
    return any(self)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/resolution/resolvelib/found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/resolution/resolvelib/found_candidates.py", line 30, in _iter_built
    for version, func in infos:
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/resolution/resolvelib/factory.py", line 269, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/index/package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/index/package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/index/package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/index/collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/index/collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/index/collector.py", line 120, in _get_html_response
    resp = session.get(
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_internal/network/session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/pypi__pip/pip/_vendor/requests/adapters.py", line 414, in send
    raise InvalidURL(e, request=request)
pip._vendor.requests.exceptions.InvalidURL: Proxy URL had no scheme, should start with http:// or https://
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__main__.py", line 4, in <module>
    main()
  File "/build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py", line 57, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '--require-hashes', '-r', '/tmp/tmpusbtqrcm']' returned non-zero exit status 2.
)
ERROR: Analysis of target '//tools/docs:entry_point_sphinx_runner_wrapper' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.955s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (642 packages loaded, 1549 targets configured)
    currently loading: @rust_linux_aarch64_toolchains// ... (9 packages)
    Fetching @base_pip3_thrift; fetching
    Fetching @base_pip3_envoy_code_check; fetching
    Fetching @base_pip3_envoy_distribution_verify; fetching
    Fetching @base_pip3_envoy_gpg_sign; fetching
    Fetching https://github.com/cncf/xds/archive/7f1daf1720fc185f3b63f70d25aefaeef83d88d7.tar.gz
    Fetching https://github.com/google/re2/archive/2022-04-01.tar.gz
Traceback (most recent call last):
  File "/workspaces/envoy/tools/gen_compilation_database.py", line 125, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "/workspaces/envoy/tools/gen_compilation_database.py", line 20, in generate_compilation_database
    subprocess.check_call([args.bazel, "build"] + bazel_options + [
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--config=compdb', '--remote_download_outputs=all', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//source/...', '//test/...', '//tools/...', '//contrib/...']' returned non-zero exit status 1.
```

**Comment by daixiang0** [comment]
Are you behind a proxy server? You need to set proxy config for bazel then it can download as expected.

**Comment by tuhao1020** [comment]
@daixiang0 I have set `http_proxy` and `https_proxy`, is there anything else need to set up?

**Comment by daixiang0** [comment]
I set HTTP_PROXY and HTTPS_PROXY, refer to https://github.com/bazelbuild/bazel/issues/587#issuecomment-412531604.

I see you run it in a dev container, can you download it by hand in the container?

You can google for more answers, it is a network issue of bazel, not Envoy itself.

**Comment by tuhao1020** [comment]
@daixiang0 Thx! Maybe there is something wrong with my proxy.

**Comment by tuhao1020** [comment]
@daixiang0 lowercase `http_proxy` and `https_proxy` are ok，in additonal, I set `all_proxy`.

After the proxy problem is solved, the error of missing cpu instruction set appears
```
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Failed
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Failed
-- Performing Test HAVE_AVX512
-- Performing Test HAVE_AVX512 - Failed
-- Building without AVX2 support
-- Building without AVX512 support
CMake Error at cmake/arch.cmake:79 (message):
  A minimum of SSSE3 compiler support is required
```

I'll create a pr to add some content to the document: https://github.com/envoyproxy/envoy/tree/main/tools/vscode#generate-debug-config

**Comment by daixiang0** [comment]
Hyperscan needs SSSE3, do you run contrib static? I think the default one(//source/exe:envoy-static) do not cover it.

**Comment by tuhao1020** [comment]
I use `//source/exe:envoy-static`.
There is no error after I changed the cpu type, building now, no errors yet.
