### ISSUE TITLE
bazel build failure 

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#21523]
I rebase the latest code and the build will fail. Actually it can succeed before the rebase. Should I upgrade the bazel version ?

bazel build   //source/exe:envoy-static --config=docker-clang
INFO: Analyzed target //source/exe:envoy-static (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: Docker sandboxing is disabled, because ProcessUtils.getuid/getgid threw an UnsatisfiedLinkError. This means that you're running a Bazel version that doesn't have JNI libraries - did you build it correctly?
java.lang.UnsatisfiedLinkError: 'int com.google.devtools.build.lib.unix.ProcessUtils.getuid()'
        at com.google.devtools.build.lib.unix.ProcessUtils.getuid(Native Method)
        at com.google.devtools.build.lib.util.ProcessUtils.getuid(ProcessUtils.java:64)
        at com.google.devtools.build.lib.sandbox.DockerSandboxedSpawnRunner.isSupported(DockerSandboxedSpawnRunner.java:98)
        at com.google.devtools.build.lib.sandbox.SandboxModule.setup(SandboxModule.java:314)
        at com.google.devtools.build.lib.sandbox.SandboxModule.registerSpawnStrategies(SandboxModule.java:152)
        at com.google.devtools.build.lib.buildtool.ExecutionTool.<init>(ExecutionTool.java:171)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:254)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:486)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:454)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:103)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:584)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
        at io.grpc.Context$1.run(Context.java:566)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
ERROR: 'docker' was requested for mnemonic Javac but no strategy with that identifier was registered. Valid values are: [processwrapper-sandbox, standalone, remote, worker, sandboxed, local, linux-sandbox]
INFO: Elapsed time: 0.239s
INFO: 0 processes.
FAILED: Build did NOT complete successfully.

**Comment by zhangbo1882** [comment]
[Wed Jun 01 18:32:01][#6# ] (metadata)$bazel --version
bazel 6.0.0-pre.20220421.3

Actually， I have already installed bazelisk.
