### ISSUE TITLE
why would compile envoy download cve data？

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22917]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
why would compile envoy download cve data？
*Description*:
>Describe the issue.
the us gov website can not connected
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
```
ERROR: /root/envoy/tools/dependency/BUILD:62:8: Executing genrule //tools/dependency:cve_data failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aiohttp/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2000, in uvloop.loop.Loop.create_connection
  File "uvloop/handles/tcp.pyx", line 182, in uvloop.loop.TCPTransport.connect
  File "uvloop/handles/tcp.pyx", line 204, in uvloop.loop._TCPConnectRequest.connect
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_envoy_dependency_check/rules_python_wheel_entry_point_envoy.dependency.check.py", line 5, in <module>
    sys.exit(run())
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/base_pip3_envoy_dependency_check/envoy/dependency/check/cmd.py", line 12, in run
    sys.exit(main(*sys.argv[1:]))
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/base_pip3_envoy_dependency_check/envoy/dependency/check/cmd.py", line 8, in main
    return DependencyChecker(*args)()
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aio_run_runner/aio/run/runner/runner.py", line 93, in __call__
    return self.loop.run_until_complete(self.run())
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/base_pip3_envoy_dependency_check/envoy/dependency/check/abstract/checker.py", line 180, in run
    return await self.cves.download_cves(self.download_cves)
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/base_pip3_envoy_dependency_check/envoy/dependency/check/abstract/cves/cves.py", line 193, in download_cves
    response = await self.nist_downloader.download(url)
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aio_api_nist/aio/api/nist/abstract/downloader.py", line 155, in download
    download = await self.session.get(url)
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aiohttp/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aiohttp/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aiohttp/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aiohttp/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aiohttp/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/sandbox/linux-sandbox/5250/execroot/envoy/bazel-out/k8-opt-exec-2B5CBBC6/bin/tools/dependency/cve_download.runfiles/base_pip3_aiohttp/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host nvd.nist.gov:443 ssl:default [Network is unreachable]
```

**Comment by mattklein123** [comment]
cc @phlax

**Comment by phlax** [comment]
that looks more like the command to run dependency checks than to compile - how was it triggered ?

**Comment by 13567436138** [comment]
./bazel-cmakelists //source/exe:envoy-sta

**Comment by 13567436138** [comment]
···
ERROR: /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/com_google_cel_cpp/parser/BUILD:19:11: @com_google_cel_cpp//parser:parser depends on @antlr4_runtimes//:cpp in repository @antlr4_runtimes which failed to fetch. no such package '@antlr4_runtimes//': java.io.IOException: Error downloading [https://github.com/antlr/antlr4/archive/v4.10.1.tar.gz] to /root/.cache/bazel/_bazel_root/4e47b77d977b209382cf04b3ae32963e/external/antlr4_runtimes/temp16383941321034193808/v4.10.1.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: 
INFO: Elapsed time: 11.866s
···

**Comment by phlax** [comment]
that error is unrelated to any CVE checking - it looks like an error pulling from github
