### ISSUE TITLE
envoy failed to compile (clang)

### ISSUE THREAD

**Issue by zonghaishang** [envoyproxy/envoy#23797]
*Description*:

gcc compiles too slowly, and switching to clang compilation does not generate debug symbols
Ubuntu 22.04.1 LTS, arm64 ()

build envoy env:
`export TEST_TMPDIR=/home/yiji/envoy-compdb`
`export BAZEL_BUILD_OPTIONS="--copt=-fno-limit-debug-info"`

 user.bazelrc :
```
yiji@yiji:~/opensource/envoy$ cat user.bazelrc 
build --config=clang
```

```
yiji@yiji:~/opensource/envoy$ tools/vscode/generate_debug_config.py //source/exe:envoy-static --debugger lldb --args "-c envoy-demo.yaml"
$TEST_TMPDIR defined: output root default is '/home/yiji/envoy-compdb' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
WARNING: info command does not support starlark options. Ignoring options: [--@com_googlesource_googleurl//build_config:system_icu=0]
$TEST_TMPDIR defined: output root default is '/home/yiji/envoy-compdb' and max_idle_secs default is '15'.
DEBUG: /home/yiji/envoy-compdb/_bazel_yiji/4cd4e6760b0f6e857d75e4bbc0366d2f/external/rules_python/python/pip.bzl:46:10: pip_install is deprecated. Please switch to pip_parse. pip_install will be removed in a future release.
INFO: Analyzed 2 targets (800 packages loaded, 33961 targets configured).
INFO: Found 2 targets...
ERROR: /home/yiji/opensource/envoy/source/exe/BUILD:23:16: 
CcGenerateIntermediateDwp source/exe/_dwps/source/exe/envoy-static-1.dwp failed:
 (Segmentation fault): dwp failed: error executing command (from target //source/exe:envoy-static) /usr/bin/dwp bazel-out/aarch64-dbg/bin/external/com_google_absl/absl/base/_objs/log_severity/log_severity.pic.dwo ... (remaining 101 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
/usr/bin/dwp: warning: bazel-out/aarch64-dbg/bin/source/exe/_dwps/source/exe/envoy-static-1.dwp: duplicate entry for CU (dwo_id 0x0)
INFO: Elapsed time: 5.849s, Critical Path: 0.24s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/vscode/generate_debug_config.py", line 138, in <module>
    debug_binary = build_binary_with_debug_info(args.target)
  File "tools/vscode/generate_debug_config.py", line 41, in build_binary_with_debug_info
    subprocess.check_call(["bazel", "build", "-c", "dbg"] + BAZEL_OPTIONS + targets)
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'dbg', '--copt=-fno-limit-debug-info', '//source/exe:envoy-static', '//source/exe:envoy-static.dwp']' returned non-zero exit status 1.



```

os:
```
yiji@yiji:~/opensource/envoy$ uname -a
Linux yiji 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:04:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

```

clang++
```
yiji@yiji:~/opensource/envoy$ clang++ --version
clang version 15.0.3 (http://git.linaro.org/toolchain/jenkins-scripts.git 534705216d7a795934be82cc0e38b9e26a3856dc)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/yiji/tools/clang+llvm-15.0.3-aarch64-linux-gnu/bin
```

lldb:
```
yiji@yiji:~/opensource/envoy$ lldb -version
lldb version 15.0.3 (http://git.linaro.org/toolchain/jenkins-scripts.git revision 534705216d7a795934be82cc0e38b9e26a3856dc)
  clang revision 534705216d7a795934be82cc0e38b9e26a3856dc
  llvm revision 534705216d7a795934be82cc0e38b9e26a3856dc
```

```
yiji@yiji:~/opensource/envoy$ arch
aarch64

```

dwp:
```
yiji@yiji:~$ /usr/bin/dwp --version
GNU dwp (GNU Binutils for Ubuntu) 2.38
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by phlax** [comment]
cc @lizan

**Comment by lizan** [comment]
This seems `dwp` command failed with segmentation fault and no error information.

@zonghaishang what if you comment out these two lines? https://github.com/envoyproxy/envoy/blob/main/.bazelrc#L43-L44

**Comment by zonghaishang** [comment]
> This seems `dwp` command failed with segmentation fault and no error information.
> 
> @zonghaishang what if you comment out these two lines? https://github.com/envoyproxy/envoy/blob/main/.bazelrc#L43-L44

Thanks for your reply, I'm trying

**Comment by zonghaishang** [comment]
> This seems `dwp` command failed with segmentation fault and no error information.
> 
> @zonghaishang what if you comment out these two lines? https://github.com/envoyproxy/envoy/blob/main/.bazelrc#L43-L44

It works for me, But the debugging speed in vscode is very slow (lldb), which is very strange


![image](https://user-images.githubusercontent.com/15549777/200480189-5deabca6-fe32-411c-ae50-8e1b268a91d3.png)

**Comment by ivitjuk** [comment]
FYI, building Envoy with Clang 12 does not cause /usr/bin/dwp to crash, while Clang 14 does.

**Comment by Winbobob** [comment]
You could try to replace GNU dwp with llvm-dwp from https://github.com/llvm/llvm-project. The debug image build worked for me with Clang 18

**Comment by phlax** [comment]
all of the tooling is now hermetic and in bazel - the build images dont have the tools any longer
