### ISSUE TITLE
ppc64le CI build always fails

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25090]
Currently we have a build triggered here https://powerci.osuosl.org/job/build-envoy-static-master/

it always fails with:

```console
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Reading rc options for 'build' from /home/alfred/jenkins/workspace/build-envoy-static-master/.bazelrc:
  'build' options: --color=yes --workspace_status_command=bash bazel/get_workspace_status --incompatible_strict_action_env --host_force_python=PY3 --java_runtime_version=remotejdk_11 --tool_java_runtime_version=remotejdk_11 --platform_mappings=bazel/platform_mappings --copt=-DABSL_MIN_LOG_LEVEL=4 --action_env=CC --host_action_env=CC --action_env=CXX --host_action_env=CXX --action_env=LLVM_CONFIG --host_action_env=LLVM_CONFIG --action_env=PATH --host_action_env=PATH --enable_platform_specific_config --test_summary=terse --incompatible_config_setting_private_default_visibility --incompatible_enforce_config_setting_visibility --define absl=1 --@com_googlesource_googleurl//build_config:system_icu=0 --test_env=HEAPCHECK=normal --test_env=PPROF_PATH
ERROR: --host_action_env=CC :: Unrecognized option: --host_action_env=CC
Build step 'Execute shell' marked build as failure
Stopping Docker container after build completion
Finished: FAILURE

```

im guessing a bazel version or similar, but not sure

apart from wasted cycles it means we always have a failing status badge - we should either fix or remove the badge if its not expected to pass and noone intends to fix

**Comment by phlax** [comment]
cc @cmluciano @clnperez

**Comment by phlax** [comment]
as noone seems to be following up on this i will pr to remove the badge - and potentially disable the ci

**Comment by cmluciano** [comment]
Hi @phlax I no longer at the company where I supported the ppc64le builds. I will try to ping the individuals that I handed this work over to but given that it's been failing for a while, it's probably safe to remove.

**Comment by phlax** [comment]
thanks for update @cmluciano i will hold off for a little while in that case and i would be happy to assist if i can getting it working again - but yep, it probs makes sense to remove until it can be fixed

**Comment by clnperez** [comment]
thank you for this! my mailbox has become very overloaded but @cmluciano found me and let me know. i'd definitely like to get this fixed so that these builds remain. i had submitted some bazel fixes years ago to get it working to begin with, so hopefully not too big of a deal to fix.

**Comment by phlax** [comment]
if my reading is correct (may not be!) its using a fixed bazel version that is now not working

if that is the case my recommendation would be to switch to using bazelisk with bazel aliased to it so it respects the repo's bazel version

**Comment by clnperez** [comment]
> if my reading is correct (may not be!) its using a fixed bazel version that is now not working

your reading of what I said? :D or something else?

**Comment by phlax** [comment]
the fail logs

**Comment by clnperez** [comment]
@phlax -- retooling the container this build uses, and will see if i can get bazelisk into this workflow. but first would like to double-check the Java & C++ config. we're using clang, and i do see mention of a `setup_clang.sh` script in the [envoy doc](https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#linux). However, I can't find that script. Is there any other doc wrt the java version required, how to configure clang, etc?

**Comment by phlax** [comment]
so for clang the reference (atm at least) is the build container which serves as an environment to bazel in envoy's CI

probably most relevant bit is here 

https://github.com/envoyproxy/envoy-build-tools/blob/b0452fc4dfb1b02357bd4ce2d55a1056b53e2ffd/build_container/build_container_ubuntu.sh#L90-L107

**Comment by phlax** [comment]
you shouldnt need to worry about java versions or most other things, but if you see what is installed in that container that will cover anything you will need

**Comment by phlax** [comment]
`setup_clang.sh` is in the `ci/` dir

**Comment by clnperez** [comment]
i updated the bazel version to see if that got rid of the error that was being seen, but it looks like maybe now i'll need to go look at the rules_python repo. https://powerci.osuosl.org/job/build-envoy-static-master/8292/console

it doesn't seem to support ppc64le at the moment: ERROR: Error computing the main repository mapping: no such package '@python3_10//': No platform declared for host OS linux on arch ppc64le

but maybe there's a way to use a native python instead

**Comment by phlax** [comment]
they come from here https://github.com/indygreg/python-build-standalone/releases/tag/20230116

it doesnt look very hopeful

**Comment by phlax** [comment]
kinda related https://github.com/bazelbuild/rules_python/issues/877

i think you can work around this (theoretically) by using a custom `py_runtime` but you may need the patch mentioned in that issue

**Comment by clnperez** [comment]
Ah, thanks for that.

Maaaaybe not hopeless! I submitted https://github.com/indygreg/python-build-standalone/pull/165 and I'll try to use that here. They do have s390x support, and they cross-compile everything. Hoping it's simple and that I won't need to chase down too many of these projects. I think I'll have to add a new triple in the `rules_python` repo at the very least.

**Comment by ninehills** [comment]
manually built Python for ppc64le and modified the rules_python package. Currently, it can be built after manual patching. Next, let's work together to push for acceptance of the patch by indygreg/python-build-standalone and bazel/rules_python.

```txt
diff --git a/bazel/repositories_extra.bzl b/bazel/repositories_extra.bzl
index 885b41dec6..e045619946 100644
--- a/bazel/repositories_extra.bzl
+++ b/bazel/repositories_extra.bzl
@@ -5,7 +5,7 @@ load("//bazel/external/cargo:crates.bzl", "raze_fetch_remote_crates")
 load("@aspect_bazel_lib//lib:repositories.bzl", "aspect_bazel_lib_dependencies")
 
 # Python version for `rules_python`
-PYTHON_VERSION = "3.10.2"
+PYTHON_VERSION = "3.10.9"
 
 # Envoy deps that rely on a first stage of dependency loading in envoy_dependencies().
 def envoy_dependencies_extra(python_version = PYTHON_VERSION):
@@ -17,6 +17,7 @@ def envoy_dependencies_extra(python_version = PYTHON_VERSION):
     python_register_toolchains(
         name = "python%s" % ("_".join(python_version.split(".")[:-1])),
         python_version = python_version,
+        ignore_root_user_error = True,
     )
 
     aspect_bazel_lib_dependencies()
diff --git a/bazel/repository_locations.bzl b/bazel/repository_locations.bzl
index 0992ec2559..97a00fe086 100644
--- a/bazel/repository_locations.bzl
+++ b/bazel/repository_locations.bzl
@@ -794,11 +794,11 @@ REPOSITORY_LOCATIONS_SPEC = dict(
         project_name = "Python rules for Bazel",
         project_desc = "Bazel rules for the Python language",
         project_url = "https://github.com/bazelbuild/rules_python",
-        version = "0.9.0",
-        sha256 = "5fa3c738d33acca3b97622a13a741129f67ef43f5fdfcec63b29374cc0574c29",
-        release_date = "2022-06-12",
+        version = "0.19.0-ppc64le-dirty-fix",
+        sha256 = "fbe317ce2b2d35ef0db738f2ad246453d56006c3df17c7728bda9fdd2852c20c",
+        release_date = "2023-03-08",
         strip_prefix = "rules_python-{version}",
-        urls = ["https://github.com/bazelbuild/rules_python/archive/{version}.tar.gz"],
+        urls = ["https://github.com/ninehills/rules_python/archive/{version}.tar.gz"],
         use_category = ["build"],
     ),
     rules_pkg = dict(
```

**Comment by clnperez** [comment]
Still waiting to hear back on the python PR

**Comment by scheruku-in** [comment]
Hi , I am facing the same error while trying to build envoy for ppc64.  Would some one please let me know if there is any work around/fix for the same and how do I get a working envoy binary for ppc64? I have actually followed the documentation mentioned at https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#quick-start-bazel-build-for-developers but stuck with the error.

```
ERROR: An error occurred during the fetch of repository 'python3_10':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/9cb33e04803417c878f91275e3e1bfb1/external/rules_python/python/private/toolchains_repo.bzl", line 88, column 38, in _toolchain_aliases_impl
                host_platform = get_host_platform(os_name, arch)
        File "/root/.cache/bazel/_bazel_root/9cb33e04803417c878f91275e3e1bfb1/external/rules_python/python/private/toolchains_repo.bzl", line 249, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch ppc64le
ERROR: /root/sobha/envoy-proxy/WORKSPACE:17:25: fetching toolchain_aliases rule //external:python3_10: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/9cb33e04803417c878f91275e3e1bfb1/external/rules_python/python/private/toolchains_repo.bzl", line 88, column 38, in _toolchain_aliases_impl
                host_platform = get_host_platform(os_name, arch)
        File "/root/.cache/bazel/_bazel_root/9cb33e04803417c878f91275e3e1bfb1/external/rules_python/python/private/toolchains_repo.bzl", line 249, column 13, in get_host_platform
                fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch ppc64le
ERROR: Error computing the main repository mapping: no such package '@python3_10//': No platform declared for host OS linux on arch ppc64le
```

**Comment by clnperez** [comment]
@scheruku-in The issue is that there just isn't a python build for power yet -- so you have to build your own. You can build the python requirements using the PR linked above, and then you'll need to do what @ninehills posted in the comment above to pull in what you build. When the PR is merged envoy can pick up the power builds like it does for all the other architectures.

**Comment by clnperez** [comment]
There was a new build released and I started putting together a PR to `rules_python` today, but, it looks like there's a problem with that release so I'll have to wait for a new one. Thanks for everyone's patience while we get this back!

**Comment by clnperez** [comment]
making more progress. the version for `rules_python` now has the one that picks up the power PR. but of course there are a couple of other things that also need to change. i did update the CI job, so you can see the newest failure. we do have a patch that fixes the build failure and will submit asap

**Comment by clnperez** [comment]
i also tested the patch via the jenkins ci we have attached ot this project and it passes
https://powerci.osuosl.org/job/build-envoy-static-master/9594/console

@sumitd2 -- have you submitted that patch yet?

**Comment by clnperez** [comment]
Also now there's a new cpu platform type so we'll need to change from `ppc` everywhere to `ppc64le`. When I initially removed the luajit build 5 years ago, I used `pcc` everywhere. IIRC no one was doing much with big endian power and open source.

**Comment by phlax** [comment]
cc @clnperez the webhook for this ci stopped working yesterday, wondering if we should remove it

**Comment by clnperez** [comment]
@phlax sorry missed your comment. the CI was paused a while ago since the builds aren't fixed yet. We've made (I really hope) some good progress in our private endeavors there, but if you want to remove it for now, that's fine. Can you just link to that PR here?

**Comment by clnperez** [comment]
Really great progress made and a PR submitted here: https://github.com/envoyproxy/envoy/pull/38403

**Comment by krinkinmu** [comment]
@clnperez and @Jenkins-J, we interacted a bit in https://github.com/envoyproxy/envoy/issues/37911.

I was looking for some ways to context IBM folks about using other crypto libraries than BoringSSL in Envoy.
I can see that you added support for AWS LC, we in Microsoft, for internal policy reasons, are interested in using OpenSSL in Envoy.

It looks like AWS LC maintains some level of compatibility with OpenSSL and I'm curious, if you considered using OpenSSL instead of AWS LC?

FWIW, if you don't have particular attachement to using AWS LC and would like to consider OpenSSL, we would be happy to collborate with you on adding support (if there is still something missing) and maintaining OpenSSL in Envoy.

During KubeCon EU I talked a bit about it to @yanavlasov and my understanding is that as long as we are ready to support the changes we add to Envoy going forward (e.g., update the dependency, address issues and CVEs, prevent the code from getting bit-rotten and in general being available), there are no fundamental blockers to adding OpenSSL to Envoy as an alternative to Boring SSL.

Yan also mentioned that folks from IBM are working on something similar because BoringSSL does not support PPC, so that's why I decided to reach out to you.

NOTE: I'm aware of https://github.com/envoyproxy/envoy-openssl and that's definitely one option, but I'd like to consider somewhat more robust alternative to the BorginSSL compatibility library that envoy-openssl uses (e.g., probably BoringSSL and OpenSSL will keep diverging more in the future and maintaing an implementation of BoringSSL in terms of OpenSSL is likely to get more difficult and error prone, so I'd like to consider providing a higher level abstraction instead).

Would you be interested in syncing and discussing in more details?

**Comment by phlax** [comment]
cc @ggreenway

**Comment by ggreenway** [comment]
Regarding OpenSSL: it's complicated. It's been discussed in several different contexts (not related to ppc64le). It would probably be better to have it's own issue.

The major problems are subtle API differences, and missing QUIC support, and other major API differences.

QUIC support could be ignored by just not including QUIC in builds with OpenSSL.

We're discussing using a new BoringSSL API in #32793. I don't think OpenSSL has anything similar, so that would be a problem.

Subtle API differences are a big problem. The API (boring or open) is easy to make mistakes with, and we do NOT want to add an additional abstraction layer  to handle those differences because it makes it harder to understand the code, which leads to more chance for bugs. And this is security-critical code.

If you can make a way to add OpenSSL support with basically no changes to the existing TLS code, propose it and we'll evaluate if it's workable.

OpenSSL would NOT be covered by the Envoy security policy. And we probably don't have the resources to make sure it keeps building in our CI.

**Comment by krinkinmu** [comment]
@ggreenway to summarize what you're saying in form of requirements to the potential solution:

1. It's ok to have a separate build that does not include QUIC as a feature
2. No unified crypto API (e.g., no generic crypto API that could be implemented in terms of Boring, Open or any other SSL library) and against conditional implementation (e.g., we cannot just put a bunch of ifdefs in the TLS code to make it work on both OpenSSL and BoringSSL builds)
3. The alternative crypto implementation will not be covered by Envoy security policy, the way I understand it, the existing triage process for the CVEs and private release of the security patches will not cover issues in the OpenSSL itself and integration with Envoy.
4. OpenSSL builds will not be covered by the existing Envoy CI.

Does it capture you concerns?

I think we are ok with skipping QUIC for now.

I'd like the potential OpenSSL implementation to get covered by the standard Envoy security processes eventually, but I'm ok to pushing that discussion down the road when we actually have an implementation with some mileage behind it, so that we can talk in specific terms what applying existing processes to OpenSSL build would mean in practice.

The same applies to the Envoy CI.

If that makes sense to you then we will discuss internally our options and when/if we have a sensible design, I can open a separate bug for that and we can discuss it there.

**Comment by ggreenway** [comment]
Yes, those sound like a good summary of what I'm saying.

> I'd like the potential OpenSSL implementation to get covered by the standard Envoy security processes eventually, but I'm ok to pushing that discussion down the road when we actually have an implementation with some mileage behind it, so that we can talk in specific terms what applying existing processes to OpenSSL build would mean in practice.

OpenSSL has historically had many more CVEs than BoringSSL. I don't think we have an appetite to take on the extra work for that. But if someone/company/organization wants to put forward the resources for that, then it could potentially work.

> The same applies to the Envoy CI.

Running our CI is quite expensive. Someone would need to put up a substantial amount of money every month, or somehow otherwise fund, the running of additional build variants in CI.

As you're thinking about solutions, feel free to ping me, either in a github issue or on slack if you have questions.

**Comment by phlax** [comment]
cc @jwendell
