### ISSUE TITLE
Use a separate `--remote_instance_name` for `main` and release branches

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#25736]
One possible reason that CI can be flakey, and bazel can sometimes refuse to die is that we are sharing the same (action) caches between the branches and this is causing some issues

Theoretically, in an ideally hermetic world with no bazel bugs this should not be a problem, but i suspect especially switching between different bazel versions as the branches do, it is

We could resolve this (if it is indeed an issue) by separating the RBE for `main` and release branches with per version/target branch `--remote_instance_name`

**Comment by phlax** [comment]
this is on 1.22 branch - interesting that it happened on the wasm/emscriptem build - i have said for a while that i think there is a hermeticity problem there 

cc @mpwarres @PiotrSikora

**Comment by phlax** [comment]
meanwhile, over on `main` ...

```console

ERROR: /source/test/extensions/bootstrap/wasm/BUILD:50:24: Linking test/extensions/bootstrap/wasm/wasm_integration_test failed: (Exit 34): Remote Execution Failure:
Failed Precondition: failed to populate working directory: failed to download inputs: blobs not found: rpc error: code = NotFound desc = downloading blobs as part of a batch resulted in 1 missing blobs, including blob hash:"4a7a9b84da433c1966f0b540ceccba2eedac4caff4def072efaa702a7cccfa25" size_bytes:1123376: 
  Unrecognized error detail: type_url: "type.googleapis.com/google.devtools.remotebuildbot.CommandStatus"
value: "\b\""


```

https://dev.azure.com/cncf/envoy/_build/results?buildId=128975&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=266e17e3-d213-54b5-deef-0dcee01da137&l=177

**Comment by phlax** [comment]
i think this is probably related, and seems to provide a bit more info ...

```console
     ^
4 warnings generated.
FATAL: bazel ran out of memory and crashed. Printing stack trace:
java.lang.OutOfMemoryError: Java heap space
	at com.google.devtools.build.lib.remote.merkletree.MerkleTree.lambda$build$2(MerkleTree.java:258)
	at com.google.devtools.build.lib.remote.merkletree.MerkleTree$$Lambda$843/0x0000000100831840.visitDirectory(Unknown Source)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:219)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:213)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:213)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:213)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:213)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:213)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:213)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:213)
	at com.google.devtools.build.lib.remote.merkletree.DirectoryTree.visit(DirectoryTree.java:197)
	at com.google.devtools.build.lib.remote.merkletree.MerkleTree.build(MerkleTree.java:249)
	at com.google.devtools.build.lib.remote.merkletree.MerkleTree.build(MerkleTree.java:218)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.buildInputMerkleTree(RemoteExecutionService.java:406)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.buildRemoteAction(RemoteExecutionService.java:454)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:185)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:245)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:146)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 30 seconds, waiting at most 60)
INFO: Waited 60 seconds for server process (pid=169) to terminate.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 10)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 10)
INFO: Waited 10 seconds for server process (pid=169) to terminate.
FATAL: Attempted to kill stale server process (pid=169) using SIGKILL, but it did not die in a timely fashion.
~/envoy-filter-example/bazel-testlogs ~/envoy-filter-example
cp: cannot stat '': No such file or directory
##[error]Bash exited with code '1'.
Finishing: Run CI script bazel.compile_time_options
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=133889&view=logs&j=e969334a-0e55-5c18-ac96-8b546753391e&t=b5329a9e-93c7-5412-9f4c-6f8d659e1b57&l=4918

im wondering if it could be that having multiple versions of bazel building similar trees is creating over-sized DAGs and causing bazel to crash in this case - may be a clue to other issues that seem to crop up with release ci

either way i think the solution is to one way or another separate out the action caches for the branches as we have (now successfully) for the bazel-remote local cache
