### ISSUE TITLE
test flake: libc++ abi negative duration

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy#26322]
libc++abi: terminating with uncaught exception of type Envoy::EnvoyException: Negative duration passed to durationToTimeval(): -1
AddressSanitizer:DEADLYSIGNAL

==16==ERROR: AddressSanitizer: ABRT on unknown address 0xfffe00000010 (pc 0x7f99a607a00b bp 0x7f999e1f0df0 sp 0x7f999e1f0630 T137)
    #0 0x7f99a607a00b in raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #1 0x7f99a6059858 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x22858) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #2 0x7f99a6293995 in abort_message (/opt/llvm/lib/x86_64-unknown-linux-gnu/libc++abi.so.1+0x2a995)
    #3 0x7f99a6277dde in demangling_terminate_handler() cxa_default_handlers.cpp
    #4 0x7f99a6292c22 in std::__terminate(void (*)()) (/opt/llvm/lib/x86_64-unknown-linux-gnu/libc++abi.so.1+0x29c22)
    #5 0x7f99a6292bc7 in std::terminate() (/opt/llvm/lib/x86_64-unknown-linux-gnu/libc++abi.so.1+0x29bc7)
    #6 0x4bbf14a in __clang_call_terminate extension_discovery_integration_test.cc
    #7 0x97bcb73 in Envoy::Config::TtlManager::ScopedTtlUpdate::~ScopedTtlUpdate() /proc/self/cwd/./source/common/config/ttl.h:35:17
    #8 0x98fe136 in decltype(static_cast<Envoy::Config::TtlManager::TtlManager(std::__1::function<void (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)>, Envoy::Event::Dispatcher&, Envoy::TimeSource&)::$_0&>(fp)()) std::__1::__invoke<Envoy::Config::TtlManager::TtlManager(std::__1::function<void (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)>, Envoy::Event::Dispatcher&, Envoy::TimeSource&)::$_0&>(Envoy::Config::TtlManager::TtlManager(std::__1::function<void (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)>, Envoy::Event::Dispatcher&, Envoy::TimeSource&)::$_0&) /proc/self/cwd/source/common/config/ttl.cc:30:3
    #9 0x98fd953 in std::__1::__function::__func<Envoy::Config::TtlManager::TtlManager(std::__1::function<void (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)>, Envoy::Event::Dispatcher&, Envoy::TimeSource&)::$_0, std::__1::allocator<Envoy::Config::TtlManager::TtlManager(std::__1::function<void (std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)>, Envoy::Event::Dispatcher&, Envoy::TimeSource&)::$_0>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/invoke.h:61:9
    #10 0x4d37d29 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #11 0xb154f87 in decltype(static_cast<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7&>(fp)()) std::__1::__invoke<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7&>(Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #12 0xb154c23 in std::__1::__function::__func<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7, std::__1::allocator<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/invoke.h:61:9
    #13 0x4d37d29 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #14 0xb9314d3 in Envoy::Event::TimerImpl::TimerImpl(Envoy::CSmartPtr<event_base, &(event_base_free)>&, std::__1::function<void ()>, Envoy::Event::Dispatcher&)::$_0::__invoke(int, short, void*) /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #15 0xc4e4a0e in event_process_active_single_queue /b/f/w/external/com_github_libevent_libevent/event.c:1713:4
    #16 0xc4c6002 in event_process_active /b/f/w/external/com_github_libevent_libevent/event.c
    #17 0xc4c6002 in event_base_loop /b/f/w/external/com_github_libevent_libevent/event.c:2047:12
    #18 0xb9289ec in Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/libevent_scheduler.cc:60:3
    #19 0xb146e44 in Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/dispatcher_impl.cc:299:19
    #20 0x6956383 in Envoy::Server::InstanceImpl::run() /proc/self/cwd/source/server/server.cc:927:16
    #21 0x5061ab1 in Envoy::IntegrationTestServerImpl::createAndRunEnvoyServer(Envoy::OptionsImpl&, Envoy::Event::TimeSystem&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::ListenerHooks&, Envoy::Thread::BasicLockable&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Random::RandomGenerator, std::__1::default_delete<Envoy::Random::RandomGenerator> >&&, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>) /proc/self/cwd/test/integration/server.cc:249:12
    #22 0x50608ab in Envoy::IntegrationTestServer::threadRoutine(Envoy::Network::Address::IpVersion, std::__1::optional<unsigned long>, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool) /proc/self/cwd/test/integration/server.cc:206:3
    #23 0x5066466 in decltype(static_cast<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool)::$_2&>(fp)()) std::__1::__invoke<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool)::$_2&>(Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool)::$_2&) /proc/self/cwd/test/integration/server.cc:114:9
    #24 0x5065ec3 in std::__1::__function::__func<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool)::$_2, std::__1::allocator<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool)::$_2>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/invoke.h:61:9

**Comment by kyessenov** [comment]
Captured this while de-flaking another test.
