### ISSUE TITLE
Envoy coredumps with random_sampling enabled.

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#2710]
*Title*: *Envoy core dumps with tracing.random_sampling enabled*

*Description*:
Using latest Envoy proxy with Istio I am using runtime { tracing.random_sampling = 100 } to enable 1% traces sampled. 
The expectation is that if the incoming request is not otherwise traced, 1% 
of the requests would be traced, per runtime_Config 

This is my runtime configuration.
```
root@istio-ingress-cdb9cc587-dhdnk:/etc/istio/proxy# find rt 
rt 
rt/tracing 
rt/tracing/random_sampling 
root@istio-ingress-cdb9cc587-dhdnk:/etc/istio/proxy# cat 
rt/tracing/random_sampling 
# per 10000 of requests that will be randomly traced. 
# This runtime control is specified in the range 0-10000 and defaults to 
10000. 
# Thus, trace sampling can be specified in 0.01% increments. 
100 
```

*Call Stack*:
When I enabled sampling at the edge (istio ingress), I get the following core dump 
```
#0  0x00007f418039e269 in raise (sig=11) at 
../sysdeps/unix/sysv/linux/pt-raise.c:35 
#1  0x0000000000ec280a in Envoy::SignalAction::sigHandler (sig=11, 
info=0x7f417c006430, context=0x7f417c006300) 
     at external/envoy/source/exe/signal_action.cc:39 
#2  <signal handler called> 
#3  0x00000000009fee01 in 
Envoy::Http::ConnectionManagerImpl::ActiveStream::encodeHeaders 
(this=0x29f3e00, filter=0x0, headers=..., end_stream=true) 
     at external/envoy/source/common/http/conn_manager_impl.cc:921 
#4  0x0000000000a009b2 in 
Envoy::Http::ConnectionManagerImpl::ActiveStreamDecoderFilter::encodeHeaders(std::unique_ptr<Envoy::Http::HeaderMap, 
std::default_delete<Envoy::Http::HeaderMap> >&&, bool) (this=0x2a361c0, 
headers=<unknown type in /usr/local/bin/envoy, CU 0x4162ad0, DIE 0x41cd059>, 
     end_stream=true) at 
external/envoy/source/common/http/conn_manager_impl.cc:1289 
```

The issue was the active_span_ member variable is un-initialized. After I 
fixed that error in my fork things moved forward.

**Comment by mandarjog** [comment]
If a request is not being traced, `active_span_` is not initialized in `ConnectionManagerImpl::ActiveStream::traceRequest()`.   This will happen when random sampling is not at `100%`
In `ConnectionManagerImpl::ActiveStream::encodeHeaders()` it is blindly used when trace operation is egress. Since istio uses resp_operation_override, this problem was hit.
