### ISSUE TITLE
`proto_sync` can fail creating diff

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#27147]
Not sure exactly the cause but it seems `proto_sync` is failing creating a diff

```console

INFO: Streaming build results to: https://source.cloud.google.com/results/invocations/fc4663a5-dc44-4373-a52c-954ca0a9f9ab
Traceback (most recent call last):
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/tools/proto_format/proto_sync.runfiles/envoy/tools/proto_format/proto_sync.py", line 149, in <module>
    sync(
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/tools/proto_format/proto_sync.runfiles/envoy/tools/proto_format/proto_sync.py", line 100, in sync
    _diff += git.diff(
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/tools/proto_format/proto_sync.runfiles/envoy/tools/proto_format/proto_sync.py", line 45, in diff
    fhash = self.string_hash(t1)
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/tools/proto_format/proto_sync.runfiles/envoy/tools/proto_format/proto_sync.py", line 42, in string_hash
    return self.blob_hash(io.BytesIO(text.encode("utf-8")), len(text))
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/tools/proto_format/proto_sync.runfiles/envoy/tools/proto_format/proto_sync.py", line 38, in blob_hash
    raise ValueError('%s: expected %u bytes, found %u bytes' % (stream.name, size, nread))
AttributeError: '_io.BytesIO' object has no attribute 'name'
Format check failed, try apply following patch to fix:

```

there have been a lot of changes recently to related code so im guessing this should be fairly easy to resolve

**Comment by phlax** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=135983&view=logs&j=c95d62a5-6bb9-58f0-2a02-7575fd482a15&t=cbf2fcae-fb78-5fe6-095d-49113b477432&l=70

**Comment by Winbobob** [comment]
Thank you @phlax for investigating this!
I tried to run proto sync under different scenarios:
- It worked on the main branch without any changes.
- It did not work on my PR with changed proto.
- It also did not work on my PR after I reverted all proto changes. Not sure whether there are some issues in my PR though.
- When I removed the output of _stream.name_ and ran the tool against my PR, it said that the bytes did not match, has 4 bytes differences IIRC.

**Comment by phlax** [comment]
> It also did not work on my PR after I reverted all proto changes. Not sure whether there are some issues in my PR though.

iiuc the reason for this, you should either do ...

```
export BAZEL_VOLATILE_DIRTY=1
```

or make a commit

the test checks for changes in your repo, and this flag makes it at least more reactive if not totally reactive to every change

**Comment by phlax** [comment]
hmm, actually that is set in the `tools/proto_format/proto_format.sh` so maybe i dont uc

**Comment by phlax** [comment]
ill test against your PR/commit and see if i can figure out what is going wrong
