### ISSUE TITLE
Go filter - 500 error when setting header value from string([]byte )

### ISSUE THREAD

**Issue by akrasic** [envoyproxy/envoy#27719]
*Title*: *500 error status when setting header value from []byte*

*Description*:
I'm writing a filter using Golang filter. 
In the DecodeHeaders stage  I'm sending a query to BoltDB to fetch a K/V based on `:path` header. 
If there is a match, then a local reply is sent.:
```
	f.callbacks.SendLocalReply(301, "", header, -1, "moved-permanently")
```

In the EncodeHeaders section I'm trying to set a `Location` header:

```
	if len(f.location) > 0 {
                // This is failing, returning 500 
                // same if doing string(f.location)
		loc := bytes.NewBuffer([]byte(f.location)).String()

                // This will also fail
                whereTo := []byte("/path/somewhere")
                loc := string(whereTo)
 
                // This passes 
                loc := "/path/to/somewhere"
		header.Set("location", loc)
	}


````

Any input would be greatly appreciated!

Debug logs:

```
[2023-05-31 09:28:39.961][28][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C0] read returns: 123
[2023-05-31 09:28:39.961][28][trace][connection] [source/common/network/raw_buffer_socket.cc:38] [C0] read error: Resource temporarily unavailable
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:639] [C0] parsing 123 bytes
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:581] [C0] message begin
[2023-05-31 09:28:39.961][28][debug][http] [source/common/http/conn_manager_impl.cc:349] [C0] new stream
[2023-05-31 09:28:39.961][28][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x17b73ee1b400 for 300000ms, min is 300000ms
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:538] [C0] completed header: key=Host value=dummy-domain.com
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:538] [C0] completed header: key=User-Agent value=curl/8.0.1
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:538] [C0] completed header: key=Accept value=*/*
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:832] [C0] onHeadersCompleteBase
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:538] [C0] completed header: key=X-Forwarded-For value=93.22.11.1, 8.8.8.8
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:1149] [C0] Server: onHeadersComplete size=4
[2023-05-31 09:28:39.961][28][trace][http] [source/common/http/http1/codec_impl.cc:936] [C0] message complete
[2023-05-31 09:28:39.961][28][debug][http] [source/common/http/conn_manager_impl.cc:1039] [C0][S10556127924364417664] request headers complete (end_stream=true):
':authority', 'dummy-domain.com'
':path', '/redirect-me'
':method', 'HEAD'
'user-agent', 'curl/8.0.1'
'accept', '*/*'
'x-forwarded-for', '93.22.11.1, 8.8.8.8'

[2023-05-31 09:28:39.961][28][debug][http] [source/common/http/conn_manager_impl.cc:1022] [C0][S10556127924364417664] request end stream
[2023-05-31 09:28:39.961][28][debug][connection] [./source/common/network/connection_impl.h:98] [C0] current connecting state: false
[2023-05-31 09:28:39.961][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:45] golang filter decodeHeaders, state: WaitingHeader, phase: DecodeHeader, end_stream: true
[2023-05-31 09:28:39.961][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:237] golang filter doHeaders, state: WaitingHeader, phase: DecodeHeader, end_stream: true
[2023-05-31 09:28:39.961][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:213] golang filter passing data to golang, state: ProcessingHeader, phase: DecodeHeader, end_stream: true
[2023-05-31 09:28:39.961][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:977] golang filter route config list length: 0.
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:1013] golang filter new plugin config, id: 1
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:510] sendLocalReply, response code: 301
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/processor_state.cc:52] golang filter handle header status, state: ProcessingHeader, phase: DecodeHeader, status: 1
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/processor_state.cc:89] golang filter after handle header status, state: ProcessingHeader, phase: DecodeHeader, status: 1
[2023-05-31 09:28:39.962][28][trace][http] [source/common/http/filter_manager.cc:539] [C0][S10556127924364417664] decode headers called: filter=envoy.filters.http.golang status=1
[2023-05-31 09:28:39.962][28][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x17b73ee1b400 for 300000ms, min is 300000ms
[2023-05-31 09:28:39.962][28][trace][http] [source/common/http/http1/codec_impl.cc:689] [C0] parsed 123 bytes
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:473] sendLocalReply Internal, response code: 301
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:487] golang filter drain do data buffer before sendLocalReply
[2023-05-31 09:28:39.962][28][debug][http] [./contrib/golang/filters/http/source/processor_state.h:214] golang filter phase grow to EncodeHeader and state grow to WaitHeader before sendLocalReply
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:36] golang filter onLocalReply, state: WaitingHeader, phase: DecodeHeader, code: 301
[2023-05-31 09:28:39.962][28][debug][http] [source/common/http/filter_manager.cc:996] [C0][S10556127924364417664] Sending local reply with details moved-permanently
[2023-05-31 09:28:39.962][28][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x17b73ee1b400 for 300000ms, min is 300000ms
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:87] golang filter encodeHeaders, state: WaitingHeader, phase: DecodeHeader, end_stream: true
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:99] golang filter enter encodeHeaders early, maybe sendLocalReply or encodeHeaders happened, current state: WaitingHeader, phase: DecodeHeader
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:101] golang filter drain data buffer since enter encodeHeaders early
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:124] golang filter clear do data buffer before continue encodeHeader, since no go code is running
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:237] golang filter doHeaders, state: WaitingHeader, phase: EncodeHeader, end_stream: true
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:213] golang filter passing data to golang, state: ProcessingHeader, phase: EncodeHeader, end_stream: true
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:510] sendLocalReply, response code: 500
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/processor_state.cc:52] golang filter handle header status, state: ProcessingHeader, phase: EncodeHeader, status: 0
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/processor_state.cc:89] golang filter after handle header status, state: ProcessingHeader, phase: EncodeHeader, status: 0
[2023-05-31 09:28:39.962][28][trace][http] [source/common/http/filter_manager.cc:1158] [C0][S10556127924364417664] encode headers called: filter=envoy.filters.http.golang status=1
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:473] sendLocalReply Internal, response code: 500
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:487] golang filter drain do data buffer before sendLocalReply
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:36] golang filter onLocalReply, state: ProcessingHeader, phase: EncodeHeader, code: 500
[2023-05-31 09:28:39.962][28][debug][http] [source/common/http/filter_manager.cc:923] [C0][S10556127924364417664] Sending local reply with details  directly to the encoder
[2023-05-31 09:28:39.962][28][debug][http] [source/common/http/conn_manager_impl.cc:1680] [C0][S10556127924364417664] encoding headers via codec (end_stream=true):
':status', '500'
'content-length', '33'
'content-type', 'text/plain'
'date', 'Wed, 31 May 2023 09:28:39 GMT'
'server', 'lmao.lol.lol1'

[2023-05-31 09:28:39.962][28][trace][connection] [source/common/network/connection_impl.cc:483] [C0] writing 144 bytes, end_stream false
[2023-05-31 09:28:39.962][28][debug][http] [source/common/http/conn_manager_impl.cc:1772] [C0][S10556127924364417664] Codec completed encoding stream.
[2023-05-31 09:28:39.962][28][trace][main] [source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=1)
[2023-05-31 09:28:39.962][28][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:180] golang filter on destroy
[2023-05-31 09:28:39.962][28][trace][main] [source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=2)
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by doujiang24** [comment]
Also, you are recommend to use 1.26.x.

**Comment by akrasic** [comment]
Thank you for a quick reply. I'm using envoyproxy/envoy:contrib-v1.26-latest image and the filter is being complied in go 1.20 docker image ( golang:1.20 ).

**Comment by doujiang24** [comment]
@akrasic I have tried this code, it works:

```
func (f *filter) DecodeHeaders(header api.RequestHeaderMap, endStream bool) api.StatusType {
	f.callbacks.SendLocalReply(301, "", map[string]string{}, -1, "moved-permanently")
	return api.LocalReply
}

func (f *filter) EncodeHeaders(header api.ResponseHeaderMap, endStream bool) api.StatusType {
	whereTo := []byte("/path/somewhere")
	loc := string(whereTo)
	header.Set("location", loc)
	return api.Continue
}
```

```
curl -s -I 'http://localhost:10000/'
HTTP/1.1 301 Moved Permanently
location: /path/somewhere
date: Wed, 31 May 2023 11:20:19 GMT
server: envoy
transfer-encoding: chunked
```

Could you please provide a full & minimal example to reproduce it? Thanks

In 1.26.x, when the envoy Go sdk trigger a 500 status local reply, it will print an error level message, with such keywords: "filter paniced with error details".
Could you confirm if is in the error log? I haven't see it in your pasted log.

**Comment by akrasic** [comment]
Thanks so much for verifying this.  More details below:
I've updated the `envoy-contrib:dev` image and it has pointed out an issue with `config.go` 



I've started from scratch, with using the setup from here - https://github.com/envoyproxy/envoy/tree/34e14ac1332e46f45a4054ee79db64cb51c934bf/examples/golang/simple 

First thing that I got back was:

``` 
./config.go:17:38: cannot use &parser{} (value of type *parser) as api.StreamFilterConfigParser value in argument to http.RegisterHttpFilterConfigParser: *parser does not implement api.StreamFilterConfigParser (wrong type for method Parse)
		have Parse(*anypb.Any) (interface{}, error)
		want Parse(*anypb.Any) interface{}
```

I've edited the Parse method there  and made it so just the `interface{}` is returned. 
When making a request, there is clear message that there `config` is `nil`:


```
[2023-05-31 15:13:39.790][21][debug][http] [contrib/golang/filters/http/source/golang_filter.cc:1158] golang filter new plugin config, id: 1
<nil>
panic: unexpected config type

goroutine 17 [running, locked to thread]:
main.ConfigFactory({0x0?, 0x0?})
	/go/src/go-filter/config.go:69 +0xbc
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.getOrCreateHttpFilterFactory({0xc0000297b8, 0x6}, 0x1)
	/go/pkg/mod/github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go@v0.0.0-20230324062628-466cf15f1790/pkg/http/filtermanager.go:48 +0xb7
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.createRequest(0x347b3ee83630)
	/go/pkg/mod/github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go@v0.0.0-20230324062628-466cf15f1790/pkg/http/shim.go:94 +0xfb
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.envoyGoFilterOnHttpHeader(0x7f9cd9105f98?, 0x1, 0x8, 0x96)
	/go/pkg/mod/github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go@v0.0.0-20230324062628-466cf15f1790/pkg/http/shim.go:110 +0x5e
``` 

envoy.yml http_filter section:

```
          http_filters:
          - name: envoy.filters.http.golang
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
              library_id: simple
              library_path: "/etc/envoy/libsimple.so"
              plugin_name: simple
              plugin_config:
                "@type": type.googleapis.com/xds.type.v3.TypedStruct
                value:
                  prefix_localreply_body: "Configured local reply from go"
```
Whole code is here: https://github.com/akrasic/filter-test/tree/main 


Testing from the envoy main branch example ( code here - https://github.com/akrasic/filter-test/tree/envoy-main-branch  ), while building, it throws:

``` 
./config.go:16:7: undefined: http.RegisterHttpFilterConfigFactoryAndParser

````

Thank you again for your time and effort in helping!

**Comment by akrasic** [comment]
Thank you for checking on this, indeed everything works now with `GODEBUG=cgocheck=0` added. 
Appreciate the help and clarity!
