### ISSUE TITLE
transport_socket_connect_timeout not working in Envoy proxy config

### ISSUE THREAD

**Issue by renuraj18** [envoyproxy/envoy#27921]
transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                  common_tls_context:
                    alpn_protocols: ["h2,http/1.1"]
                    tls_certificates:
                      - certificate_chain:
                          filename: "/etc/certs/server.crt"
                        private_key:
                          filename: "/etc/certs/server.key"
              transport_socket_connect_timeout: 30s

Error:
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed while performing TLS negotiation
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:542)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:468)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:432)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:465)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
      at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:

**Comment by renuraj18** [comment]
Envoy error:
[2023-06-12 08:58:48.864][1][critical][main] [source/server/server.cc:101] error initializing configuration '/etc/envoy/envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0]) transport_socket_connect_timeout: Cannot find field.) has unknown fields
[2023-06-12 08:58:48.864][1][info][main] [source/server/server.cc:704] exiting
[2023-06-12 08:58:48.864][1][debug][main] [source/common/access_log/access_log_manager_impl.cc:19] destroyed access loggers
[2023-06-12 08:58:48.864][1][debug][init] [source/common/init/watcher_impl.cc:27] init manager Server destroyed
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0]) transport_socket_connect_timeout: Cannot find field.) has unknown fields

**Comment by KBaichoo** [comment]
ISTM the YAML is not indented correctly for the field: `          transport_socket_connect_timeout: 30s`
e.g. it's not under the transport socket config as it should be.
