### ISSUE TITLE
vscode  devcontainer   envoy  occur   error

### ISSUE THREAD

**Issue by jason9015** [envoyproxy/envoy#28895]
```console
Skipping proto_format.sh due to no API change
$TEST_TMPDIR defined: output root default is '/build/envoy-compdb' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
DEBUG: /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/rules_python/python/pip.bzl:47:10: pip_install is deprecated. Please switch to pip_parse. pip_install will be removed in a future release.
WARNING: /workspaces/envoy/test/proto/BUILD:30:23: in genrule rule //test/proto:bookstore_proto_descriptor: target '//test/proto:bookstore_proto_descriptor' depends on deprecated target '@com_google_protobuf//:well_known_protos': Prefer :well_known_type_protos instead.
ERROR: /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: in cc_toolchain_suite rule @envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain: cc_toolchain_suite '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' does not contain a toolchain for cpu 'aarch64'
ERROR: /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_build_tools/toolchains/configs/linux/clang/cc/BUILD:47:19: Analysis of target '@envoy_build_tools//toolchains/configs/linux/clang/cc:toolchain' failed
INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:45:6: in <toplevel>
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/jdk/remote_java_repository.bzl:48:17: in remote_java_repository
Repository rule http_archive defined at:
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository kafka_server_binary instantiated at:
  /workspaces/envoy/WORKSPACE:13:19: in <toplevel>
  /workspaces/envoy/bazel/repositories.bzl:283:16: in envoy_dependencies
  /workspaces/envoy/bazel/repositories.bzl:1280:26: in _kafka_deps
  /workspaces/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository com_github_fdio_vpp_vcl instantiated at:
  /workspaces/envoy/WORKSPACE:13:19: in <toplevel>
  /workspaces/envoy/bazel/repositories.bzl:275:29: in envoy_dependencies
  /workspaces/envoy/bazel/repositories.bzl:1293:26: in _com_github_fdio_vpp_vcl
  /workspaces/envoy/bazel/repositories.bzl:30:23: in external_http_archive
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive
Repository rule http_archive defined at:
  /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: Analysis of target '//test/integration/filters:test_network_filter_proto_cc_proto_cc_proto' failed; build aborted: 
INFO: Elapsed time: 7.847s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (864 packages loaded, 5983 targets configured)
    currently loading: @base_pip3_jinja2// ... (3 packages)
    Fetching repository @org_golang_google_protobuf; Restarting.
    Fetching repository @bazel_gazelle_go_repository_config; Restarting.
    Fetching repository @com_github_cncf_xds_go; Restarting.
    Fetching repository @bazel_gazelle_go_repository_tools; Restarting.
    Fetching https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-linux_x64.tar.gz
    Fetching https://archive.apache.org/dist/kafka/3.4.0/kafka_2.13-3.4.0.tgz
Traceback (most recent call last):
  File "/workspaces/envoy/tools/gen_compilation_database.py", line 127, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "/workspaces/envoy/tools/gen_compilation_database.py", line 24, in generate_compilation_database
    subprocess.check_call([args.bazel, "build"] + bazel_options + [
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--config=compdb', '--remote_download_outputs=all', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//source/...', '//test/...', '//contrib/...']' returned non-zero exit status 1.
```

**Comment by phlax** [comment]
@jason9015 can you confirm which version/branch you are trying to build

im noticing here:

```console
DEBUG: /build/envoy-compdb/_bazel_vscode/2d35de14639eaad1ac7060a4dd7e3351/external/rules_python/python/pip.bzl:47:10: pip_install is deprecated. Please switch to pip_parse. pip_install will be removed in a future release.
```

that this is not current `main`

**Comment by jason9015** [comment]
I use    realease/v1.25  and use vscode     devcontainer

**Comment by jason9015** [comment]
<img width="1378" alt="image" src="https://github.com/envoyproxy/envoy/assets/22276078/f99b95c8-7fb1-4685-b3fb-121c9731a5ee">

**Comment by jason9015** [comment]
who can help me?

**Comment by phlax** [comment]
@jason9015 posting screenshots is not so helpful - also please focus on one issue rather than opening several

i think the problem relates to you using arm64 architecture

i dont have an arm machine immediately available to test, but im guessing it may be possible to workaround - not sure

**Comment by phlax** [comment]
im running some tests in our ci to get an idea of current status of running this in x86/arm

once i have an idea of that i will test on the 1.25 branch also

i dont use vscode so this is not necessarily an accurate test - but im already seeing some issues so will investigate further

**Comment by jason9015** [comment]
think you

**Comment by PatrikValo** [comment]
Hello, I have the same issue and I found a workaround.

I think the problematic part is https://github.com/envoyproxy/envoy/blob/a6792927ff71015069326490af5306ad56d769c9/.devcontainer/setup.sh#L8
I changed the ~/.bazelrc line to
```bash
build --config=clang-libc++
```
and it seems like compile_commands.json is generated and so far it looks like jumping to definitions, references in cpp files works.
