### ISSUE TITLE
Coverage may have gotten even slower

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#29031]
In #28802 we switched to using the upstream collect coverage script as that would appear to now provide the necessary functionality

When testing this it tended to be very slow the first time it was run after any signifcant change, running it subsequently it would run faster than what we were using

Since this has landed it seems as tho coverage has slowed down significantly - one indication of this is that it can again timeout after 4 hours (we recently reduced the limit)

debugging a machine while its running - the whole thing seems very very suboptimally designed - llvm-cov is repeatedly called with a huge number of args - some of the args seem like they should not be checked for coverage (external, mock files etc)

in addition to this the same files seem to be getting checked on each invokation

**Comment by phlax** [comment]
related to https://github.com/bazelbuild/bazel/issues/8178

**Comment by phlax** [comment]
also there are some related errors, eg:

```console
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.io.IOException: Error while uploading artifact with digest '7e5af8a42dbe5e371169999a35f82dec632e8252858c9c6be498c7ddc1826426/2718'
		at com.google.devtools.build.lib.remote.ByteStreamUploader.lambda$uploadBlobAsync$0(ByteStreamUploader.java:171)
		at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:203)
		at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:190)
		at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:133)
		... 73 more
	Caused by: io.grpc.StatusRuntimeException: UNKNOWN
		at io.grpc.Status.asRuntimeException(Status.java:535)
		... 10 more
	Caused by: java.lang.OutOfMemoryError: Direct buffer memory
		at java.base/java.nio.Bits.reserveMemory(Unknown Source)
		at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
		at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
```
https://dev.azure.com/cncf/envoy/_build/results?buildId=146149&view=logs&j=bbe4b42d-86e6-5e9c-8a0b-fea01d818a24&t=00ade0d6-ffae-5af0-b5e0-e33b1813c8bc&l=4222
