### ISSUE TITLE
integration test may crash when thread local is shutting down

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#29054]
This issue was found when developing the iouring

When the integration test ends, the thread local is shutdown, and at same time the fake xds upstream closed also. When the xds subscription's grpc stream notified the remote close, it will trigger a retry, the retry will try to access the thread local cluster, but the thread local cluster already shutdown, then leads to a crash.

```
[ RUN      ] IpVersionsClientType/ExtensionDiscoveryIntegrationTest.BasicSuccessWithTtl/2
[2023-08-16 09:12:59.291][128][critical][assert] [./envoy/thread_local/thread_local.h:47] assert failure: std::dynamic_pointer_cast<T>(get()) != nullptr.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==12==ERROR: AddressSanitizer: ABRT on unknown address 0x03f00000000c (pc 0x7fcb16399e87 bp 0x7fcb04866690 sp 0x7fcb048661f0 T111)
/usr/bin/addr2line: Dwarf Error: Invalid or unhandled FORM value: 0x25.
/usr/bin/addr2line: Dwarf Error: found dwarf version '1', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '10752', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '512', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '12', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '770', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '1226', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '25858', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '30720', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '1024', this reader only handles version 2, 3, 4 and 5 information.
    #0 0x7fcb16399e87 in gsignal ??:?
    #1 0x7fcb1639b7f0 in abort ??:?
    #2 0x639e72e in Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl& Envoy::ThreadLocal::Slot::getTyped<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>() ??:?
    #3 0x633f9bf in Envoy::ThreadLocal::TypedSlot<Envoy::Upstream::ClusterManagerImpl::ThreadLocalClusterManagerImpl>::operator*() ??:?
    #4 0x62fb30a in Envoy::Upstream::ClusterManagerImpl::getThreadLocalCluster(std::__1::basic_string_view<char, std::__1::char_traits<char> >) ??:?
    #5 0x735efb7 in Envoy::Grpc::AsyncStreamImpl::initialize(bool) ??:?
    #6 0x735e1dc in Envoy::Grpc::AsyncClientImpl::startRaw(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, Envoy::Grpc::RawAsyncStreamCallbacks&, Envoy::Http::AsyncClient::StreamOptions const&) ??:?
    #7 0x736803a in Envoy::Grpc::Internal::startUntyped(Envoy::Grpc::RawAsyncClient*, google::protobuf::MethodDescriptor const&, Envoy::Grpc::RawAsyncStreamCallbacks&, Envoy::Http::AsyncClient::StreamOptions const&) ??:?
    #8 0x49f9fdf in Envoy::Grpc::AsyncClient<envoy::service::discovery::v3::DiscoveryRequest, envoy::service::discovery::v3::DiscoveryResponse>::start(google::protobuf::MethodDescriptor const&, Envoy::Grpc::AsyncStreamCallbacks<envoy::service::discovery::v3::DiscoveryResponse>&, Envoy::Http::AsyncClient::StreamOptions const&) ??:?
    #9 0x49eea6c in Envoy::Config::GrpcStream<envoy::service::discovery::v3::DiscoveryRequest, envoy::service::discovery::v3::DiscoveryResponse>::establishNewStream() ??:?
    #10 0x4a107eb in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Config::GrpcStream<envoy::service::discovery::v3::DiscoveryRequest, envoy::service::discovery::v3::DiscoveryResponse>::GrpcStream(Envoy::Config::GrpcStreamCallbacks<envoy::service::discovery::v3::DiscoveryResponse>*, std::__1::unique_ptr<Envoy::Grpc::RawAsyncClient, std::__1::default_delete<Envoy::Grpc::RawAsyncClient> >, google::protobuf::MethodDescriptor const&, Envoy::Event::Dispatcher&, Envoy::Stats::Scope&, std::__1::unique_ptr<Envoy::BackOffStrategy, std::__1::default_delete<Envoy::BackOffStrategy> >, Envoy::Config::RateLimitSettings const&)::{lambda()#1}&>(Envoy::Config::GrpcStream<envoy::service::discovery::v3::DiscoveryRequest, envoy::service::discovery::v3::DiscoveryResponse>::GrpcStream(Envoy::Config::GrpcStreamCallbacks<envoy::service::discovery::v3::DiscoveryResponse>*, std::__1::unique_ptr<Envoy::Grpc::RawAsyncClient, std::__1::default_delete<Envoy::Grpc::RawAsyncClient> >, google::protobuf::MethodDescriptor const&, Envoy::Event::Dispatcher&, Envoy::Stats::Scope&, std::__1::unique_ptr<Envoy::BackOffStrategy, std::__1::default_delete<Envoy::BackOffStrategy> >, Envoy::Config::RateLimitSettings const&)::{lambda()#1}&) ??:?
    #11 0x4a107c8 in std::__1::__function::__alloc_func<Envoy::Config::GrpcStream<envoy::service::discovery::v3::DiscoveryRequest, envoy::service::discovery::v3::DiscoveryResponse>::GrpcStream(Envoy::Config::GrpcStreamCallbacks<envoy::service::discovery::v3::DiscoveryResponse>*, std::__1::unique_ptr<Envoy::Grpc::RawAsyncClient, std::__1::default_delete<Envoy::Grpc::RawAsyncClient> >, google::protobuf::MethodDescriptor const&, Envoy::Event::Dispatcher&, Envoy::Stats::Scope&, std::__1::unique_ptr<Envoy::BackOffStrategy, std::__1::default_delete<Envoy::BackOffStrategy> >, Envoy::Config::RateLimitSettings const&)::{lambda()#1}, std::__1::allocator<{lambda()#1}>, void ()>::operator()() grpc_mux_impl.cc:?
    #12 0x4a1002c in std::__1::__function::__func<Envoy::Config::GrpcStream<envoy::service::discovery::v3::DiscoveryRequest, envoy::service::discovery::v3::DiscoveryResponse>::GrpcStream(Envoy::Config::GrpcStreamCallbacks<envoy::service::discovery::v3::DiscoveryResponse>*, std::__1::unique_ptr<Envoy::Grpc::RawAsyncClient, std::__1::default_delete<Envoy::Grpc::RawAsyncClient> >, google::protobuf::MethodDescriptor const&, Envoy::Event::Dispatcher&, Envoy::Stats::Scope&, std::__1::unique_ptr<Envoy::BackOffStrategy, std::__1::default_delete<Envoy::BackOffStrategy> >, Envoy::Config::RateLimitSettings const&)::{lambda()#1}, std::__1::allocator<{lambda()#1}>, void ()>::operator()() ??:?
    #13 0x48476b1 in std::__1::__function::__value_func<void ()>::operator()() const http_integration.cc:?
    #14 0x9793151 in std::__1::__function::__func<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7, std::__1::allocator<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7>, void ()>::operator()() dispatcher_impl.cc:?
    #15 0x48476b1 in std::__1::__function::__value_func<void ()>::operator()() const http_integration.cc:?
    #16 0x9e01736 in Envoy::Event::TimerImpl::TimerImpl(Envoy::CSmartPtr<event_base, &event_base_free>&, std::__1::function<void ()>, Envoy::Event::Dispatcher&)::$_0::__invoke(int, short, void*) timer_impl.cc:?
    #17 0xb1a160e in event_process_active_single_queue event.c:?
    #18 0xb182c02 in event_base_loop ??:?
    #19 0x9dfb27e in Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) ??:?
    #20 0x978a522 in Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) ??:?
    #21 0x9e258a2 in Envoy::Io::IoUringWorkerImpl::~IoUringWorkerImpl() ??:?
    #22 0x9e1fd6c in std::__1::__shared_ptr_emplace<Envoy::Io::IoUringWorkerImpl, std::__1::allocator<Envoy::Io::IoUringWorkerImpl> >::__on_zero_shared() ??:?
    #23 0x47393c9 in std::__1::__shared_weak_count::__release_shared() extension_discovery_integration_test.cc:?
    #24 0x5177c0d in std::__1::shared_ptr<Envoy::ThreadLocal::ThreadLocalObject>::~shared_ptr() mocks.cc:?
    #25 0x6072d3c in Envoy::ThreadLocal::InstanceImpl::shutdownThread() ??:?
    #26 0x610ddb1 in Envoy::Server::InstanceImpl::terminate() ??:?
    #27 0x611a85c in Envoy::Server::InstanceImpl::run() ??:?
    #28 0x4ca0b91 in Envoy::IntegrationTestServerImpl::createAndRunEnvoyServer(Envoy::OptionsImpl&, Envoy::Event::TimeSystem&, std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::ListenerHooks&, Envoy::Thread::BasicLockable&, Envoy::Server::ComponentFactory&, std::__1::unique_ptr<Envoy::Random::RandomGenerator, std::__1::default_delete<Envoy::Random::RandomGenerator> >&&, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>) ??:?
    #29 0x4c9fe91 in Envoy::IntegrationTestServer::threadRoutine(Envoy::Network::Address::IpVersion, std::__1::optional<unsigned long>, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool) ??:?
    #30 0x4ca2ec1 in std::__1::__function::__func<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool)::$_2, std::__1::allocator<Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool)::$_2>, void ()>::operator()() server.cc:?
    #31 0x48476b1 in std::__1::__function::__value_func<void ()>::operator()() const http_integration.cc:?
    #32 0xb1439a8 in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&)::{lambda(void*)#1}::__invoke(void*) ??:?
    #33 0x7fcb1696b6da in start_thread ??:?
    #34 0x7fcb1647c61e in clone ??:?

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT ??:? in gsignal
Thread T111 created by T0 here:
/usr/bin/addr2line: Dwarf Error: found dwarf version '2593', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '30724', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '3584', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '26882', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '3840', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '4101', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '27138', this reader only handles version 2, 3, 4 and 5 information.
/usr/bin/addr2line: Dwarf Error: found dwarf version '58880', this reader only handles version 2, 3, 4 and 5 information.
    #0 0x469bd4c in __interceptor_pthread_create ??:?
    #1 0xb140ee8 in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&) ??:?
    #2 0xb1407ea in std::__1::__unique_if<Envoy::Thread::ThreadImplPosix>::__unique_single std::__1::make_unique<Envoy::Thread::ThreadImplPosix, std::__1::function<void ()>&, std::__1::optional<Envoy::Thread::Options> const&>(std::__1::function<void ()>&, std::__1::optional<Envoy::Thread::Options> const&) thread_impl.cc:?
    #3 0xb140618 in Envoy::Thread::ThreadFactoryImplPosix::createThread(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&) ??:?
    #4 0x4c9cbca in Envoy::IntegrationTestServer::start(Envoy::Network::Address::IpVersion, std::__1::function<void ()>, std::__1::optional<unsigned long>, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool) ??:?
    #5 0x4c9bfc3 in Envoy::IntegrationTestServer::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Envoy::Network::Address::IpVersion, std::__1::function<void (Envoy::IntegrationTestServer&)>, std::__1::function<void ()>, std::__1::optional<unsigned long>, Envoy::Event::TestTimeSystem&, Envoy::Api::Api&, bool, std::__1::optional<std::__1::reference_wrapper<Envoy::ProcessObject> >, Envoy::Server::FieldValidationConfig, unsigned int, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> >, Envoy::Server::DrainStrategy, std::__1::shared_ptr<Envoy::Buffer::WatermarkFactory>, bool, bool) ??:?
    #6 0x48be7d6 in Envoy::BaseIntegrationTest::createGeneratedApiTestServer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, Envoy::Server::FieldValidationConfig, bool, std::__1::unique_ptr<Envoy::IntegrationTestServer, std::__1::default_delete<Envoy::IntegrationTestServer> >&) ??:?
    #7 0x48b880f in Envoy::BaseIntegrationTest::createGeneratedApiTestServer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, Envoy::Server::FieldValidationConfig, bool) ??:?
    #8 0x48b8249 in Envoy::BaseIntegrationTest::createEnvoy() ??:?
    #9 0x48b2125 in Envoy::BaseIntegrationTest::initialize() ??:?
    #10 0x47efbef in Envoy::HttpIntegrationTest::initialize() ??:?
    #11 0x46f142d in Envoy::(anonymous namespace)::ExtensionDiscoveryIntegrationTest::initialize() extension_discovery_integration_test.cc:?
    #12 0x46fbee8 in Envoy::(anonymous namespace)::ExtensionDiscoveryIntegrationTest_BasicSuccessWithTtl_Test::TestBody() extension_discovery_integration_test.cc:?
    #13 0x46ffe9c in non-virtual thunk to Envoy::(anonymous namespace)::ExtensionDiscoveryIntegrationTest_BasicSuccessWithTtl_Test::TestBody() extension_discovery_integration_test.cc:?
    #14 0xbd84247 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ??:?
    #15 0xbd5aaeb in testing::Test::Run() ??:?
    #16 0xbd5c120 in testing::TestInfo::Run() ??:?
    #17 0xbd5d73a in testing::TestSuite::Run() ??:?
    #18 0xbd7693b in testing::internal::UnitTestImpl::RunAllTests() ??:?
    #19 0xbd877f7 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ??:?
    #20 0xbd75eed in testing::UnitTest::Run() ??:?
    #21 0x95cfcfc in Envoy::TestRunner::RunTests(int, char**) ??:?
    #22 0x95cc0da in main ??:?
    #23 0x7fcb1637cc86 in __libc_start_main ??:?

==12==ABORTING
```

**Comment by soulxu** [comment]
After digging more, this won't happened on the default socket. It is only happened on iouring. Since the IoUring will run the dispatcher when destruct the IoUringWorker, that gives chances to run some timer when the thread local has already shut down.

Maybe I shouldn't fix all those code to access the thread local, I should avoid the IoUringWorker running the dispatcher when shutdown.
