### ISSUE TITLE
m/tsan flake with quic_protocol_integration_test

### ISSUE THREAD

**Issue by RyanTheOptimist** [envoyproxy/envoy#29191]
There is a pretty consistent a/msan flake with quic_protocol_integration_test. Recent examples can be found here [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=146745&view=logs&j=1439b9f7-a348-5b50-b5fe-ea612ea91241&t=177d5b9a-f5c6-5873-3da2-bad8ffe4f4c2&l=1601) and [here](https://dev.azure.com/cncf/envoy/_build/results?buildId=146575&view=logs&j=4e2e4662-2d21-5726-b4bc-9ff5cd6a179b&t=393ef8cf-9eb2-5a8a-e529-cceb42dc347e&l=1548).

Here's the output for posterity:

```
==17==ERROR: AddressSanitizer: ABRT on unknown address 0xfffe00000011 (pc 0x7f7dd2df300b bp 0x7f7d5a104a10 sp 0x7f7d5a1045f0 T2118)
    #0 0x7f7dd2df300b in raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #1 0x7f7dd2dd2858 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x22858) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #2 0x55193fc in Envoy::InjectableSingleton<Envoy::Network::SocketInterface>::get() /proc/self/cwd/./source/common/singleton/threadsafe_singleton.h:56:5
    #3 0xc3260ac in Envoy::Network::Address::Ipv6Instance::Ipv6Instance(absl::Status&, sockaddr_in6 const&, bool, Envoy::Network::SocketInterface const*) /proc/self/cwd/source/common/network/address_impl.cc:32:39
    #4 0xc32a9c1 in absl::StatusOr<std::__1::shared_ptr<Envoy::Network::Address::Instance const> > Envoy::Network::Address::InstanceFactory::createInstancePtr<Envoy::Network::Address::Ipv6Instance, sockaddr_in6 const&, bool&>(sockaddr_in6 const&, bool&) /proc/self/cwd/./source/common/network/address_impl.h:87:48
    #5 0xc31adaf in Envoy::Network::Address::addressFromSockAddr(sockaddr_storage const&, unsigned int, bool) /proc/self/cwd/source/common/network/address_impl.cc:92:14
    #6 0xc31d08c in Envoy::Network::Address::addressFromSockAddrOrDie(sockaddr_storage const&, unsigned int, int, bool) /proc/self/cwd/source/common/network/address_impl.cc:129:7
    #7 0xb0d3c94 in Envoy::Quic::quicAddressToEnvoyAddressInstance(quic::QuicSocketAddress const&) /proc/self/cwd/source/common/quic/envoy_quic_utils.cc:20:16
    #8 0xae379f6 in Envoy::Quic::EnvoyQuicPacketWriter::GetNextWriteLocation(quiche::QuicheIpAddress const&, quic::QuicSocketAddress const&) /proc/self/cwd/source/common/quic/envoy_quic_packet_writer.cc:64:7
    #9 0xb4b30b4 in quic::QuicConnection::GetPacketBuffer() /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_connection.cc:3823:19
    #10 0xb4b32e1 in non-virtual thunk to quic::QuicConnection::GetPacketBuffer() /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_connection.cc
    #11 0xb54a6fe in quic::QuicPacketCreator::FlushCurrentPacket() /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_packet_creator.cc:447:52
    #12 0xb565864 in quic::QuicPacketCreator::ConsumeCryptoData(quic::EncryptionLevel, unsigned long, unsigned long) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_packet_creator.cc:1475:5
    #13 0xb4815f5 in quic::QuicConnection::SendCryptoData(quic::EncryptionLevel, unsigned long, unsigned long) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_connection.cc:2372:26
    #14 0xb2d09b2 in quic::QuicSession::SendCryptoData(quic::EncryptionLevel, unsigned long, unsigned long, quic::TransmissionType) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_session.cc:859:20
    #15 0xb2d127c in non-virtual thunk to quic::QuicSession::SendCryptoData(quic::EncryptionLevel, unsigned long, unsigned long, quic::TransmissionType) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_session.cc
    #16 0xb29c6d6 in quic::QuicCryptoStream::RetransmitData(quic::QuicCryptoFrame*, quic::TransmissionType) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_crypto_stream.cc:428:48
    #17 0xb2fc34c in quic::QuicSession::RetransmitFrames(absl::InlinedVector<quic::QuicFrame, 1ul, std::__1::allocator<quic::QuicFrame> > const&, quic::TransmissionType) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_session.cc:2348:38
    #18 0xb2fccac in non-virtual thunk to quic::QuicSession::RetransmitFrames(absl::InlinedVector<quic::QuicFrame, 1ul, std::__1::allocator<quic::QuicFrame> > const&, quic::TransmissionType) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_session.cc
    #19 0xb63ee96 in quic::QuicUnackedPacketMap::RetransmitFrames(absl::InlinedVector<quic::QuicFrame, 1ul, std::__1::allocator<quic::QuicFrame> > const&, quic::TransmissionType) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_unacked_packet_map.cc:477:29
    #20 0xb599bec in quic::QuicSentPacketManager::MarkForRetransmission(quic::QuicPacketNumber, quic::TransmissionType) /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_sent_packet_manager.cc:509:27
    #21 0xb5a4c69 in quic::QuicSentPacketManager::MaybeSendProbePacket() /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_sent_packet_manager.cc:864:5
    #22 0xb4b95b7 in quic::QuicConnection::OnRetransmissionTimeout() /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_connection.cc:4130:24
    #23 0xb4f5183 in quic::(anonymous namespace)::RetransmissionAlarmDelegate::OnAlarm() /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_connection.cc:117:18
    #24 0xb58f13e in quic::QuicAlarm::Fire() /proc/self/cwd/external/com_github_google_quiche/quiche/quic/core/quic_alarm.cc:89:16
    #25 0xadcca90 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Quic::EnvoyQuicAlarm::EnvoyQuicAlarm(Envoy::Event::Dispatcher&, quic::QuicClock const&, quic::QuicArenaScopedPtr<quic::QuicAlarm::Delegate>)::$_0&>(Envoy::Quic::EnvoyQuicAlarm::EnvoyQuicAlarm(Envoy::Event::Dispatcher&, quic::QuicClock const&, quic::QuicArenaScopedPtr<quic::QuicAlarm::Delegate>)::$_0&) /proc/self/cwd/source/common/quic/envoy_quic_alarm.cc:11:49
    #26 0xadcc7d3 in std::__1::__function::__func<Envoy::Quic::EnvoyQuicAlarm::EnvoyQuicAlarm(Envoy::Event::Dispatcher&, quic::QuicClock const&, quic::QuicArenaScopedPtr<quic::QuicAlarm::Delegate>)::$_0, std::__1::allocator<Envoy::Quic::EnvoyQuicAlarm::EnvoyQuicAlarm(Envoy::Event::Dispatcher&, quic::QuicClock const&, quic::QuicArenaScopedPtr<quic::QuicAlarm::Delegate>)::$_0>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16
    #27 0x57de709 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #28 0xbaa93e7 in decltype(static_cast<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7&>(fp)()) std::__1::__invoke<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7&>(Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #29 0xbaa9083 in std::__1::__function::__func<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7, std::__1::allocator<Envoy::Event::DispatcherImpl::createTimerInternal(std::__1::function<void ()>)::$_7>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/invoke.h:61:9
    #30 0x57de709 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #31 0xc2998a3 in Envoy::Event::TimerImpl::TimerImpl(Envoy::CSmartPtr<event_base, &(event_base_free)>&, std::__1::function<void ()>, Envoy::Event::Dispatcher&)::$_0::__invoke(int, short, void*) /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #32 0xdea4d0e in event_process_active_single_queue /b/f/w/external/com_github_libevent_libevent/event.c:1713:4
    #33 0xde86302 in event_process_active /b/f/w/external/com_github_libevent_libevent/event.c
    #34 0xde86302 in event_base_loop /b/f/w/external/com_github_libevent_libevent/event.c:2047:12
    #35 0xc290a6c in Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/libevent_scheduler.cc:60:3
    #36 0xba9bd74 in Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/dispatcher_impl.cc:300:19
    #37 0x5de2708 in Envoy::FakeUpstream::threadRoutine() /proc/self/cwd/test/integration/fake_upstream.cc:712:16
    #38 0x5e054a7 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::FakeUpstream::initializeServer()::$_24&>(Envoy::FakeUpstream::initializeServer()::$_24&) /proc/self/cwd/test/integration/fake_upstream.cc:663:67
    #39 0x5e051f3 in std::__1::__function::__func<Envoy::FakeUpstream::initializeServer()::$_24, std::__1::allocator<Envoy::FakeUpstream::initializeServer()::$_24>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16
    #40 0x57de709 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #41 0xde3e45c in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::operator()(void*) const /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #42 0xde3e3d3 in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/source/common/common/posix/thread_impl.cc:48:9
    #43 0x7f7dd2fc7608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #44 0x7f7dd2ecf132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x4300b) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee) in raise
Thread T2118 created by T0 here:
    #0 0x54c2a8c in pthread_create /local/mnt/workspace/bcain_clang_hu-bcain-lv_22036/final/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:208:3
    #1 0xde3a41e in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:46:20
    #2 0xde39d02 in std::__1::__unique_if<Envoy::Thread::ThreadImplPosix>::__unique_single std::__1::make_unique<Envoy::Thread::ThreadImplPosix, std::__1::function<void ()>&, std::__1::optional<Envoy::Thread::Options> const&>(std::__1::function<void ()>&, std::__1::optional<Envoy::Thread::Options> const&) /opt/llvm/bin/../include/c++/v1/__memory/unique_ptr.h:725:32
    #3 0xde39b28 in Envoy::Thread::ThreadFactoryImplPosix::createThread(std::__1::function<void ()>, std::__1::optional<Envoy::Thread::Options> const&) /proc/self/cwd/source/common/common/posix/thread_impl.cc:117:10
    #4 0x5ddf081 in Envoy::FakeUpstream::initializeServer() /proc/self/cwd/test/integration/fake_upstream.cc:663:35
    #5 0x5ddd526 in Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::DownstreamTransportSocketFactory, std::__1::default_delete<Envoy::Network::DownstreamTransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeUpstreamConfig const&, bool) /proc/self/cwd/test/integration/fake_upstream.cc:646:5
    #6 0x5dde75e in Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::DownstreamTransportSocketFactory, std::__1::default_delete<Envoy::Network::DownstreamTransportSocketFactory> >&&, std::__1::shared_ptr<Envoy::Network::Address::Instance const> const&, Envoy::FakeUpstreamConfig const&) /proc/self/cwd/test/integration/fake_upstream.cc:613:7
    #7 0x59c881d in Envoy::BaseIntegrationTest::createUpstream(std::__1::shared_ptr<Envoy::Network::Address::Instance const>, Envoy::FakeUpstreamConfig&) /proc/self/cwd/test/integration/base_integration_test.cc:186:38
    #8 0x59c8371 in Envoy::BaseIntegrationTest::createUpstreams() /proc/self/cwd/test/integration/base_integration_test.cc:174:5
    #9 0x59c0cef in Envoy::BaseIntegrationTest::initialize() /proc/self/cwd/test/integration/base_integration_test.cc:122:3
    #10 0x590ffb5 in Envoy::HttpIntegrationTest::initialize() /proc/self/cwd/test/integration/http_integration.cc:354:33
    #11 0x56a76b9 in Envoy::ProtocolIntegrationTest_HandleUpstreamSocketFail_Test::TestBody() /proc/self/cwd/test/integration/protocol_integration_test.cc:4318:3
    #12 0xeca1874 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2580:10
    #13 0xec69552 in testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2655:5
    #14 0xec6b0b7 in testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2832:11
    #15 0xec6d454 in testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2986:28
    #16 0xec8f80a in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5697:44
    #17 0xeca5863 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2580:10
    #18 0xec8e516 in testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5280:10
    #19 0xb81c6fa in Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2485:46
    #20 0xb817ae6 in main /proc/self/cwd/test/main.cc:34:10
    #21 0x7f7dd2dd4082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

==17==ABORTING
```

```
[2023-08-20 19:14:57.860][2161][critical][assert] [./source/common/singleton/threadsafe_singleton.h:56] assert failure: loader_ != nullptr. Details: InjectableSingleton used prior to initialization
[2023-08-20 19:14:57.860][2161][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0xfffe00000013
[2023-08-20 19:14:57.860][2161][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2023-08-20 19:14:57.860][2161][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 0/1.28.0-dev/test/DEBUG/BoringSSL
[2023-08-20 19:14:57.868][2161][critical][backtrace] [./source/server/backtrace.h:96] #0: SignalAction() [0x1477429]
[2023-08-20 19:14:57.869][2161][critical][backtrace] [./source/server/backtrace.h:96] #1: __restore_rt [0x7f3320b51420]
[2023-08-20 19:14:57.877][2161][critical][backtrace] [./source/server/backtrace.h:96] #2: Envoy::Network::Address::Ipv4Instance::Ipv4Instance() [0x804729b]
[2023-08-20 19:14:57.885][2161][critical][backtrace] [./source/server/backtrace.h:96] #3: Envoy::Network::Address::InstanceFactory::createInstancePtr<>() [0x8051655]
[2023-08-20 19:14:57.892][2161][critical][backtrace] [./source/server/backtrace.h:96] #4: Envoy::Network::Address::addressFromSockAddr() [0x803fffd]
[2023-08-20 19:14:57.900][2161][critical][backtrace] [./source/server/backtrace.h:96] #5: Envoy::Network::Address::addressFromSockAddrOrDie() [0x8043e09]
[2023-08-20 19:14:57.908][2161][critical][backtrace] [./source/server/backtrace.h:96] #6: Envoy::Quic::quicAddressToEnvoyAddressInstance() [0x6ece450]
[2023-08-20 19:14:57.916][2161][critical][backtrace] [./source/server/backtrace.h:96] #7: Envoy::Quic::EnvoyQuicPacketWriter::GetNextWriteLocation() [0x6c7283d]
[2023-08-20 19:14:57.924][2161][critical][backtrace] [./source/server/backtrace.h:96] #8: quic::QuicConnection::GetPacketBuffer() [0x72a50b0]
[2023-08-20 19:14:57.931][2161][critical][backtrace] [./source/server/backtrace.h:96] #9: quic::QuicPacketCreator::FlushCurrentPacket() [0x731eb84]
[2023-08-20 19:14:57.939][2161][critical][backtrace] [./source/server/backtrace.h:96] #10: quic::QuicPacketCreator::ConsumeCryptoData() [0x733c4ed]
[2023-08-20 19:14:57.947][2161][critical][backtrace] [./source/server/backtrace.h:96] #11: quic::QuicConnection::SendCryptoData() [0x727b221]
[2023-08-20 19:14:57.955][2161][critical][backtrace] [./source/server/backtrace.h:96] #12: quic::QuicSession::SendCryptoData() [0x70dc16a]
[2023-08-20 19:14:57.963][2161][critical][backtrace] [./source/server/backtrace.h:96] #13: quic::QuicSession::SendCryptoData() [0x70dcafc]
[2023-08-20 19:14:57.970][2161][critical][backtrace] [./source/server/backtrace.h:96] #14: quic::QuicCryptoStream::RetransmitData() [0x70afddc]
[2023-08-20 19:14:57.978][2161][critical][backtrace] [./source/server/backtrace.h:96] #15: quic::QuicSession::RetransmitFrames() [0x70fe10c]
[2023-08-20 19:14:57.986][2161][critical][backtrace] [./source/server/backtrace.h:96] #16: quic::QuicSession::RetransmitFrames() [0x70fe518]
[2023-08-20 19:14:57.994][2161][critical][backtrace] [./source/server/backtrace.h:96] #17: quic::QuicUnackedPacketMap::RetransmitFrames() [0x73eafd6]
[2023-08-20 19:14:58.002][2161][critical][backtrace] [./source/server/backtrace.h:96] #18: quic::QuicSentPacketManager::MarkForRetransmission() [0x736843b]
[2023-08-20 19:14:58.010][2161][critical][backtrace] [./source/server/backtrace.h:96] #19: quic::QuicSentPacketManager::MaybeSendProbePacket() [0x7370183]
[2023-08-20 19:14:58.018][2161][critical][backtrace] [./source/server/backtrace.h:96] #20: quic::QuicConnection::OnRetransmissionTimeout() [0x72a8e4c]
[2023-08-20 19:14:58.025][2161][critical][backtrace] [./source/server/backtrace.h:96] #21: quic::(anonymous namespace)::RetransmissionAlarmDelegate::OnAlarm() [0x72d4832]
[2023-08-20 19:14:58.033][2161][critical][backtrace] [./source/server/backtrace.h:96] #22: quic::QuicAlarm::Fire() [0x7360c87]
[2023-08-20 19:14:58.041][2161][critical][backtrace] [./source/server/backtrace.h:96] #23: std::__1::__function::__func<>::operator()() [0x6c075fd]
[2023-08-20 19:14:58.049][2161][critical][backtrace] [./source/server/backtrace.h:96] #24: std::__1::__function::__func<>::operator()() [0x781ad83]
[2023-08-20 19:14:58.057][2161][critical][backtrace] [./source/server/backtrace.h:96] #25: Envoy::Event::TimerImpl::TimerImpl()::$_0::__invoke() [0x7fd8ef7]
[2023-08-20 19:14:58.065][2161][critical][backtrace] [./source/server/backtrace.h:96] #26: event_process_active_single_queue [0x979f9b3]
[2023-08-20 19:14:58.073][2161][critical][backtrace] [./source/server/backtrace.h:96] #27: event_base_loop [0x978d0a2]
[2023-08-20 19:14:58.081][2161][critical][backtrace] [./source/server/backtrace.h:96] #28: Envoy::Event::LibeventScheduler::run() [0x7fd1f4e]
[2023-08-20 19:14:58.090][2161][critical][backtrace] [./source/server/backtrace.h:96] #29: Envoy::Event::DispatcherImpl::run() [0x7809b51]
[2023-08-20 19:14:58.109][2161][critical][backtrace] [./source/server/backtrace.h:96] #30: Envoy::FakeUpstream::threadRoutine() [0x1e31bb3]
[2023-08-20 19:14:58.129][2161][critical][backtrace] [./source/server/backtrace.h:96] #31: std::__1::__function::__func<>::operator()() [0x1e5248d]
[2023-08-20 19:14:58.143][2161][critical][backtrace] [./source/server/backtrace.h:96] #32: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::__invoke() [0x974ea9c]
[2023-08-20 19:14:58.143][2161][critical][backtrace] [./source/server/backtrace.h:96] #33: start_thread [0x7f3320b45609]
```

**Comment by RyanTheOptimist** [comment]
/assign @danzh2010 
Dan, can you take a look at this?

**Comment by phlax** [comment]
this test is now flaking pretty regularly across CI cc @danzh2010 (seeing a lot in presubmit also)

another fail: https://dev.azure.com/cncf/envoy/_build/results?buildId=147758&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=8a34f9ed-4946-5fcf-7cd6-99c93070884d&l=3329

**Comment by danzh2010** [comment]
looking now

**Comment by phlax** [comment]
reopening this as we are still hitting flakes

not sure if its the same issue/s exactly

heres an example of tsan failing postsubmit https://dev.azure.com/cncf/envoy/_build/results?buildId=147910&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=f1bd857c-4611-5620-0b5a-d15324470098&l=421

**Comment by phlax** [comment]
and again https://dev.azure.com/cncf/envoy/_build/results?buildId=147911&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=f1bd857c-4611-5620-0b5a-d15324470098&l=423

**Comment by danzh2010** [comment]
It's a different failure in DownstreamProtocolIntegrationTest.ManyLargeRequestHeadersAccepte with HTTP/3 upstream. I can't reproduce with 200 runs with TSAN, but maybe the same issue as https://github.com/envoyproxy/envoy/pull/20931.
