### ISSUE TITLE
Envoy crashes while using HTTP Filter with Golang extension

### ISSUE THREAD

**Issue by ardikabs** [envoyproxy/envoy#29973]
*Title*: Envoy instance crashes while using HTTP Filter with Golang extension.

*Description*:
Got a panicked error at Envoy runtime while enabling HTTP Filter with Golang extension.

*Repro steps*:
I have no idea how to reproduce this issue, but the error intermittently happens for moderate HTTP traffic in the range of 24 hours.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
```
panic: get config failed, plugin: <filter_name>, configId: 2209

goroutine 35 [running, locked to thread]:
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.getOrCreateHttpFilterFactory({0xc0003ce730, 0xf}, 0x8a1)
        /app/vendor/github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http/filtermanager.go:47 +0x168
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.createRequest(0x1453be617950)
        /app/vendor/github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http/shim.go:95 +0xda
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.envoyGoFilterOnHttpHeader(0x7c4ad7b93ff8?, 0x1, 0x15, 0x3db)
        /app/vendor/github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http/shim.go:111 +0x5e
[2023-10-04 09:30:05.026][20][critical][backtrace] [./source/server/backtrace.h:104] Caught Aborted, suspect faulting address 0x1
[2023-10-04 09:30:05.026][20][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2023-10-04 09:30:05.026][20][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: 7bba38b743bb3bca22dffb4a21c38ccc155fbef8/1.27.0/Clean/RELEASE/BoringSSL
[2023-10-04 09:30:05.026][20][critical][backtrace] [./source/server/backtrace.h:96] #0: __restore_rt [0x7c4adb9dd420]
[2023-10-04 09:30:05.026][20][critical][backtrace] [./source/server/backtrace.h:96] #1: runtime.fatalpanic [0x7c4ad7bc2c8d]
[2023-10-04 09:30:05.027][20][critical][backtrace] [./source/server/backtrace.h:96] #2: runtime.gopanic [0x7c4ad7bc237b]
[2023-10-04 09:30:05.027][20][critical][backtrace] [./source/server/backtrace.h:96] #3: github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.getOrCreateHttpFilterFactory [0x7c4ad7d7a428]
[2023-10-04 09:30:05.028][20][critical][backtrace] [./source/server/backtrace.h:96] #4: github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.createRequest [0x7c4ad7d83c7a]
[2023-10-04 09:30:05.028][20][critical][backtrace] [./source/server/backtrace.h:96] #5: github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.envoyGoFilterOnHttpHeader [0x7c4ad7d83e1e]
[2023-10-04 09:30:05.028][20][critical][backtrace] [./source/server/backtrace.h:96] #6: _cgoexp_57f89ac20a93_envoyGoFilterOnHttpHeader [0x7c4ad7d849f0]
[2023-10-04 09:30:05.029][20][critical][backtrace] [./source/server/backtrace.h:96] #7: runtime.cgocallbackg1 [0x7c4ad7b91bf1]
[2023-10-04 09:30:05.029][20][critical][backtrace] [./source/server/backtrace.h:96] #8: runtime.cgocallbackg [0x7c4ad7b918a9]
[2023-10-04 09:30:05.029][20][critical][backtrace] [./source/server/backtrace.h:96] #9: runtime.cgocallbackg.abi0 [0x7c4ad7bf6e51]
[2023-10-04 09:30:05.030][20][critical][backtrace] [./source/server/backtrace.h:96] #10: runtime.cgocallback.abi0 [0x7c4ad7bf4593]
```

**Comment by doujiang24** [comment]
@ardikabs Thanks for your report.

As we discussed in [Slack](https://envoyproxy.slack.com/archives/C04QNSXC7U0/p1696480315939159?thread_ts=1696412727.137949&cid=C04QNSXC7U0)
Here might be a race while generating merged config, we will fix it soon.
https://github.com/envoyproxy/envoy/blob/v1.27.0/contrib/golang/filters/http/source/golang_filter.cc#L1354-L1376
