### ISSUE TITLE
Verify/examples in CI is broken

### ISSUE THREAD

**Issue by botengyao** [envoyproxy/envoy#30195]
Looks like [Verify/examples](https://github.com/envoyproxy/envoy/actions/runs/6507233090/job/17674260591) is failing.

[Another PR Verify/examples](https://github.com/envoyproxy/envoy/actions/runs/6501571455)

```
INFO: Running command line: bazel-bin/external/envoy_repo/publish publish /source '--publish-commitish=0fb10f1e4dc967bc669219e5aeb6e9a7071caa63' --publish-commit-message '--publish-assets=/build/release.signed/release.signed.tar.zst' --dry-run
Traceback (most recent call last):
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_envoy_base_utils/rules_python_wheel_entry_point_envoy.project.py", line 5, in <module>
    sys.exit(project_cmd())
             ^^^^^^^^^^^^^
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_envoy_base_utils/site-packages/envoy/base/utils/project_cmd.py", line 12, in project_cmd
    sys.exit(main(*sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_envoy_base_utils/site-packages/envoy/base/utils/project_cmd.py", line 8, in main
    return ProjectRunner(*args)()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_aio_run_runner/site-packages/aio/run/runner/runner.py", line 93, in __call__
    return self.loop.run_until_complete(self.run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_aio_run_runner/site-packages/aio/run/runner/decorators.py", line 77, in async_wrapped
    return await fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_aio_run_runner/site-packages/aio/run/runner/decorators.py", line 41, in async_wrapped
    return await fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_envoy_base_utils/site-packages/envoy/base/utils/project_runner.py", line 1[96](https://github.com/envoyproxy/envoy/actions/runs/6507233090/job/17674260591#step:11:98), in run
    change = await self.handle_action()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_envoy_base_utils/site-packages/envoy/base/utils/project_runner.py", line 153, in handle_action
    publish=await self.run_publish(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_envoy_base_utils/site-packages/envoy/base/utils/project_runner.py", line 214, in run_publish
    async for result in self.project.publish(**kwargs):
  File "/build/bazel_root/base/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy_repo/publish.runfiles/base_pip3_envoy_base_utils/site-packages/envoy/base/utils/abstract/project/project.py", line 260, in publish
    commit_message = commit.data[0]["commit"]["message"]
                     ~~~~~~~~~~~^^^
KeyError: 0
```

**Comment by botengyao** [comment]
cc @phlax

**Comment by phlax** [comment]
should be fixed if you merge `main` - closing

**Comment by phlax** [comment]
(apologies for disruptions)

**Comment by botengyao** [comment]
Thank you!
