### ISSUE TITLE
Http2TestServerTest::testGetRequestWithPlatformCertValidatorSuccess always fails on Linux

### ISSUE THREAD

**Issue by fredyw** [envoyproxy/envoy#30191]
[Http2TestServerTest::testGetRequestWithPlatformCertValidatorSuccess](https://github.com/envoyproxy/envoy/blob/1a9e559e6f12475fa6de6c6bb220d71c4155b300/mobile/test/java/org/chromium/net/testing/Http2TestServerTest.java#L110-L113) always fails on Linux.

To reproduce:

```
cd mobile
bazel test --config=test-android --define=signal_trace=disabled //test/java/org/chromium/net/testing:http2_test_server_test
```

Error:
```
1) testGetRequestWithPlatformCertValidatorSuccess(org.chromium.net.testing.Http2TestServerTest)
java.lang.NullPointerException
        at org.chromium.net.testing.Http2TestServerTest.getSchemeIsHttps(Http2TestServerTest.java:99)
        at org.chromium.net.testing.Http2TestServerTest.testGetRequestWithPlatformCertValidatorSuccess(Http2TestServerTest.java:112)
```

Digging the issue a little bit, this is the actual error. I suspect this is because the lack of a platform cert verifier on Linux.

```
upstream_reset_before_response_started{local_connection_failure,TLS_error:_268435581:SSL_routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED}
```

**Comment by fredyw** [comment]
Not stale.
