### ISSUE TITLE
Filesystem xDS on Windows triggers permission errors in the updater

### ISSUE THREAD

**Issue by dimo414** [envoyproxy/envoy#30378]
*Description*:

I have observed inconsistent but reproducible errors while updating xDS files on Windows (using Python's `os.replace()`, but I expect any atomic overwrite would hit a similar error):

```
Traceback (most recent call last):
  .......
  File "envoy_config.py", line 230, in replace_config_file
    os.replace(source, dest)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Dev\\AppData\\Local\\Temp\\envoy-config-258r5e6p\\tmpzdckoqi_' -> 'C:\\Users\\Dev\\AppData\\Local\\Temp\\envoy-config-258r5e6p\\tmpgkg8r9ni-cds.yaml'
```

If I am not mistaken this error happens when the xDS file is updated while Envoy is still reading the file from a previous update, during which time Envoy effectively holds a lock on the file. I _believe_ this could be [avoided](https://stackoverflow.com/q/5891053/113632) by configuring [file sharing](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileshare), but I have not tested this.

Although this error arises in the separate updater process I feel this is an Envoy bug because there is no reasonable way for the updater process to know when it is safe to initiate an update. Workarounds involve retrying and/or sleeping, neither of which are ideal.

Notably, nothing in the Envoy documentation mentions this limitation, so if this _is_ considered WAI the documentation should be updated to clarify how well-behaved updaters should be implemented.

*Repro steps*:
1. Run a filesystem-backed xDS config on Windows 
2. In a tight loop update the xDS files repeatedly using Python's `os.replace()` or similar
3. Observe permission errors in the process updating the xDS files

Here is an example triggering this error without Envoy, just to demonstrate that holding a file reference open is sufficient:

```
PS> python3.8.exe
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import tempfile
>>> dest=tempfile.NamedTemporaryFile(suffix="-dest", delete=False).name
>>> os.replace(tempfile.NamedTemporaryFile(suffix="-tmp", delete=False).name, dest)
>>> f = open(dest)
>>> os.replace(tempfile.NamedTemporaryFile(suffix="-tmp", delete=False).name, dest)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [WinError 5] Access is denied: 'tmpuau8nzjn-tmp' -> 'tmpq3lqearn-dest'
```

**Comment by alyssawilk** [comment]
cc @adisuissa @htuch

**Comment by adisuissa** [comment]
I don't have a way to test this on windows.
IIUC [this](https://github.com/envoyproxy/envoy/blob/69f1e43a8158347ab2430531b284d837544a7f50/source/common/filesystem/win32/filesystem_impl.cc#L284) is the function that is being used to read the config file. If you have a way to test the args and ensure it works, please let me know.

**Comment by dimo414** [comment]
Thanks for the pointer and the quick response. It sounds like this issue was at least [observed in the past](https://github.com/envoyproxy/envoy/pull/14447) but the changes in that PR appear to be insufficient to fully address it. I'm afraid I too don't have a way to test this (or enough Windows knowledge to do so effectively). @davinci26 do you have any insights?

**Comment by dimo414** [comment]
I do not believe this issue should be closed just because no one has commented on it. As mentioned in https://github.com/envoyproxy/envoy/issues/30016#issuecomment-1807469072 I understand if this issue cannot be resolved immediately, but this stalebot behavior is actively harmful.
