### ISSUE TITLE
flaky in QuicHttpIntegrationTests/QuicHttpIntegrationTest.MultipleQuicConnectionsNoBPF/IPv4

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#31226]
https://dev.azure.com/cncf/envoy/_build/results?buildId=157225&view=logs&j=1439b9f7-a348-5b50-b5fe-ea612ea91241&t=1002ac43-da84-5fae-70b2-98833b702d09&l=129

```
source/common/http/http1/codec_impl.cc:1065:9: runtime error: member call on address 0x61c0001a2880 which does not point to an object of type 'Envoy::Http::Http1::ServerConnectionImpl'
0x61c0001a2880: note: object has invalid vptr
 bb 00 00 00  7d 3e 0d 00 00 00 00 00  be be be be be be be be  40 13 85 0f 00 00 00 00  20 97 d4 0f
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0xa8193e6 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5&, Envoy::Buffer::OwnedBufferFragmentImpl const*>(Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5&, Envoy::Buffer::OwnedBufferFragmentImpl const*&&) /proc/self/cwd/source/common/http/http1/codec_impl.cc:1065:9
    #1 0xa8190fa in std::__1::__function::__func<Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5, std::__1::allocator<Envoy::Http::Http1::ServerConnectionImpl::ServerConnectionImpl(Envoy::Network::Connection&, Envoy::Http::Http1::CodecStats&, Envoy::Http::ServerConnectionCallbacks&, Envoy::Http::Http1Settings const&, unsigned int, unsigned int, envoy::config::core::v3::HttpProtocolOptions_HeadersWithUnderscoresAction, Envoy::Server::OverloadManager&)::$_5>, void (Envoy::Buffer::OwnedBufferFragmentImpl const*)>::operator()(Envoy::Buffer::OwnedBufferFragmentImpl const*&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16
    #2 0xa826490 in std::__1::__function::__value_func<void (Envoy::Buffer::OwnedBufferFragmentImpl const*)>::operator()(Envoy::Buffer::OwnedBufferFragmentImpl const*&&) const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #3 0xa82604d in Envoy::Buffer::OwnedBufferFragmentImpl::done() /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #4 0xe8c48a8 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'()&>(Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'()&) /proc/self/cwd/./source/common/buffer/buffer_impl.h:93:42
    #5 0xe8c47f8 in std::__1::__function::__alloc_func<Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'(), std::__1::allocator<Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'()>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/function.h:180:16
    #6 0xe8c3f93 in std::__1::__function::__func<Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'(), std::__1::allocator<Envoy::Buffer::Slice::Slice(Envoy::Buffer::BufferFragment&)::'lambda'()>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/__functional/function.h:354:12
    #7 0x5bff699 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/__functional/function.h:507:16
    #8 0xa948924 in Envoy::Buffer::Slice::operator=(Envoy::Buffer::Slice&&) /opt/llvm/bin/../include/c++/v1/__functional/function.h:1184:12
    #9 0xe8bc1e0 in Envoy::Buffer::SliceDeque::pop_front() /proc/self/cwd/./source/common/buffer/buffer_impl.h:504:13
    #10 0xe8aa5d3 in Envoy::Buffer::OwnedImpl::drainImpl(unsigned long) /proc/self/cwd/source/common/buffer/buffer_impl.cc:181:13
    #11 0xe8aa136 in Envoy::Buffer::OwnedImpl::drain(unsigned long) /proc/self/cwd/source/common/buffer/buffer_impl.cc:160:40
    #12 0xc5b7d0a in Envoy::Buffer::WatermarkBuffer::drain(unsigned long) /proc/self/cwd/source/common/buffer/watermark_buffer.cc:56:14
    #13 0xccbfc18 in Envoy::Network::IoSocketHandleImpl::write(Envoy::Buffer::Instance&) /proc/self/cwd/source/common/network/io_socket_handle_impl.cc:140:12
    #14 0xc7f6d7d in Envoy::Network::RawBufferSocket::doWrite(Envoy::Buffer::Instance&, bool) /proc/self/cwd/source/common/network/raw_buffer_socket.cc:67:61
    #15 0xc575104 in Envoy::Network::ConnectionImpl::onWriteReady() /proc/self/cwd/source/common/network/connection_impl.cc:763:40
    #16 0xc571310 in Envoy::Network::ConnectionImpl::onFileEvent(unsigned int) /proc/self/cwd/source/common/network/connection_impl.cc:642:5

```

**Comment by soulxu** [comment]
cc @RyanTheOptimist @danzh2010

**Comment by danzh2010** [comment]
The crash stack has HTTP/1 server codec. This test runs HTTP/3 downstream and HTTP/1 upstream. It looks like a life time issue with the upstream HTTP/1 codec.

**Comment by danzh2010** [comment]
@yanavlasov who owns HTTP/1 codec today?
