### ISSUE TITLE
asan build failure due to transient network download

### ISSUE THREAD

**Issue by ravenblackx** [envoyproxy/envoy#31968]
Connection timed out.

```
WARNING: Download from https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'cmake-3.23.2-linux-x86_64':
   Traceback (most recent call last):
	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz] to /build/bazel_root/base/external/cmake-3.23.2-linux-x86_64/temp14121619752627832591/cmake-3.23.2-linux-x86_64.tar.gz: connect timed out
ERROR: /source/WORKSPACE:25:25: fetching http_archive rule //external:cmake-3.23.2-linux-x86_64: Traceback (most recent call last):
	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz] to /build/bazel_root/base/external/cmake-3.23.2-linux-x86_64/temp14121619752627832591/cmake-3.23.2-linux-x86_64.tar.gz: connect timed out
ERROR: /build/bazel_root/base/external/envoy/bazel/foreign_cc/BUILD:314:12: @envoy//bazel/foreign_cc:event depends on @cmake-3.23.2-linux-x86_64//:cmake_tool in repository @cmake-3.23.2-linux-x86_64 which failed to fetch. no such package '@cmake-3.23.2-linux-x86_64//': java.io.IOException: Error downloading [https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz] to /build/bazel_root/base/external/cmake-3.23.2-linux-x86_64/temp14121619752627832591/cmake-3.23.2-linux-x86_64.tar.gz: connect timed out
ERROR: Analysis of target '//test/tools/schema_validator/test:schema_validator_test' failed; build aborted: 
INFO: Elapsed time: 74.950s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests
```

**Comment by phlax** [comment]
transient
