### ISSUE TITLE
panic when use golang filter decode http2 connect tunnel data

### ISSUE THREAD

**Issue by userlxd** [envoyproxy/envoy#32033]
1. envoy config use [h2 connect tunnel config from example](https://github.com/envoyproxy/envoy/blob/4f0965e9c61f8daa3519dc0298d4833cf8730307/configs/terminate_http2_connect.yaml)

2. envoy use golang filter _envoy.filters.http.golang_，code is
```golang
func (f *filter) DecodeData(buffer api.BufferInstance, endStream bool) api.StatusType {
	api.LogInfof("body len: %d", buffer.Len())
	api.LogInfof("body: %s", string(buffer.Bytes()))

	return api.Continue
}
```

3. when request arrived, then buffer.Len() run success, but buffer.Bytes() will got panic, error is
```
2024-01-25 14:17:29.816][608832][error][golang] [contrib/golang/common/log/cgo.cc:24] http: panic serving: not proccessing Go
goroutine 17 [running, locked to thread]:
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.(*httpRequest).RecoverPanic(0xc00007e690)
	/usr/local/go/path/pkg/mod/github.com/envoyproxy/envoy@v1.28.0/contrib/golang/filters/http/source/go/pkg/http/filter.go:83 +0x6b
panic({0x7fa388a77840, 0xc000073820})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.handleCApiStatus(...)
	/usr/local/go/path/pkg/mod/github.com/envoyproxy/envoy@v1.28.0/contrib/golang/filters/http/source/go/pkg/http/capi_impl.go:82
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.(*httpCApiImpl).HttpGetBuffer(0x7fa388ab3bc0?, 0xa388864d96?, 0x7fa387f27388?, 0x4f)
	/usr/local/go/path/pkg/mod/github.com/envoyproxy/envoy@v1.28.0/contrib/golang/filters/http/source/go/pkg/http/capi_impl.go:208 +0xd5
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.(*httpBuffer).Bytes(0xc000025fb0)
	/usr/local/go/path/pkg/mod/github.com/envoyproxy/envoy@v1.28.0/contrib/golang/filters/http/source/go/pkg/http/type.go:368 +0x43
main.(*filter).DecodeData(0xc0000125d0?, {0x7fa388ae1478?, 0xc000025fb0?}, 0x8?)
	/code/sdp/internal/gateway/envoy/go-hook/main.go:62 +0x27
github.com/envoyproxy/envoy/contrib/golang/filters/http/source/go/pkg/http.envoyGoFilterOnHttpData(0x277cbf2469b0, 0x0, 0x277cbfd50300, 0x4f)
	/usr/local/go/path/pkg/mod/github.com/envoyproxy/envoy@v1.28.0/contrib/golang/filters/http/source/go/pkg/http/shim.go:197 +0x122
```

**Comment by zuercher** [comment]
cc @doujiang24 @wangfakang

**Comment by doujiang24** [comment]
@userlxd Thanks for your reporting, it's reproducable on my side, I'll take a deeper look soon~

**Comment by doujiang24** [comment]
Oh, sorry, the current implementation do not support handling request data of full-duplex http requests, neither CONNECT nor WebSocket.
I'll figure a way to support it, may need some time. Thanks again~

**Comment by userlxd** [comment]
In my case, I need inject the tls.conn over tunnel to control https token header.
Wasm go plugin could be work when read tunnel data, but go native tls.conn.handshake use goroutine.
So the lowest cost way is to wait for go plugin to support it, Thank you for your contribution @doujiang24

**Comment by doujiang24** [comment]
not stale, I'll fix it in the near future.
