### ISSUE TITLE
flaky hotrestart_handoff_test test

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#33251]
https://dev.azure.com/cncf/envoy/_build/results?buildId=166595&view=logs&j=d1f76054-8f79-554b-6f4a-11d6a63b8e00&t=33c64725-b304-5065-9740-0ce244fa1a25&l=415

ERROR: test_connection_handoffs (__main__.IntegrationTest.test_connection_handoffs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/python3_11_x86_64-unknown-linux-gnu/lib/python3.11/unittest/async_case.py", line 90, in _callTestMethod
    if self._callMaybeAsync(method) is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/python3_11_x86_64-unknown-linux-gnu/lib/python3.11/unittest/async_case.py", line 112, in _callMaybeAsync
    return self._asyncioRunner.run(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/python3_11_x86_64-unknown-linux-gnu/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/python3_11_x86_64-unknown-linux-gnu/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/envoy/test/integration/python/hotrestart_handoff_test.py", line 382, in test_connection_handoffs
    await _wait_for_envoy_epoch(1)
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/envoy/test/integration/python/hotrestart_handoff_test.py", line 299, in _wait_for_envoy_epoch
    response = await _full_http_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/envoy/test/integration/python/hotrestart_handoff_test.py", line 202, in _full_http_request_task
    async with session.get(url) as response:
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/base_pip3_aiohttp/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/base_pip3_aiohttp/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/base_pip3_aiohttp/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/b/f/w/bazel-out/k8-dbg/bin/test/integration/python/hotrestart_handoff_test.runfiles/base_pip3_aiohttp/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

**Comment by soulxu** [comment]
cc @ravenblackx

**Comment by ravenblackx** [comment]
Made a change that I *think* will help with this. If it doesn't then skipping this test for tsan+msan would be the next thing I would try (because they're also useless for this test), but that's a big bazel rewiring thing so I hope not to have to.

Closing the issue for now, but it is 100% appropriate to reopen if the same flake occurs again.
