### ISSUE TITLE
mobile/ios builds are permafailing

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#33396]
currently any runs of mobile/ios are failing (altho in many ci runs this ci does not run)

afaict the earliest instance of this particular issue is here https://github.com/envoyproxy/envoy/pull/33378

as this PR did not land i think the issue is in some way infra/external - it was just the first time the ci had run since it broke

error is:

```console
ERROR: /Users/runner/work/envoy/envoy/mobile/examples/swift/hello_world/BUILD:16:16: Linking examples/swift/hello_world/app_bin failed: (Exit 34): Remote Execution Failure:
Internal: ChB5XT9glm5IzZ7bdFDRnM46EgdkZWZhdWx0GiUKICROHZwOSi4HTK9KRIBcprRKFbhM-OouLOlbbD407mSYEKMB: timeout for : engflow/z-2024-03-08/cas/685c/685cfb1ceeef635df8568a5870743ae064f6dd4d552056a8293d6a46e6497e16
---- cut here ---8<--------8<--------8<--------8<--- cut here ----
com.engflow.storage.s3.S3ClientV2$SyncTimeOutException: timeout for : engflow/z-2024-03-08/cas/685c/685cfb1ceeef635df8568a5870743ae064f6dd4d552056a8293d6a46e6497e16
	at com.engflow.storage.s3.S3ClientV2.asSyncCall(S3ClientV2.java:211)
	at com.engflow.storage.s3.S3ClientV2.upload(S3ClientV2.java:681)
	at com.engflow.re.storage.EpochExternalStorage.lambda$putCasBlob$10(EpochExternalStorage.java:1079)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at com.engflow.re.monitoring.MetricReportingExecutorService$InstrumentedRunnable.run(MetricReportingExecutorService.java:378)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	<abbreviated>


java.io.IOException: com.google.devtools.build.lib.remote.ExecutionStatusException: INTERNAL: ChB5XT9glm5IzZ7bdFDRnM46EgdkZWZhdWx0GiUKICROHZwOSi4HTK9KRIBcprRKFbhM-OouLOlbbD407mSYEKMB: timeout for : engflow/z-2024-03-08/cas/685c/685cfb1ceeef635df8568a5870743ae064f6dd4d552056a8293d6a46e6497e16
---- cut here ---8<--------8<--------8<--------8<--- cut here ----
com.engflow.storage.s3.S3ClientV2$SyncTimeOutException: timeout for : engflow/z-2024-03-08/cas/685c/685cfb1ceeef635df8568a5870743ae064f6dd4d552056a8293d6a46e6497e16
	at com.engflow.storage.s3.S3ClientV2.asSyncCall(S3ClientV2.java:211)
	at com.engflow.storage.s3.S3ClientV2.upload(S3ClientV2.java:681)
	at com.engflow.re.storage.EpochExternalStorage.lambda$putCasBlob$10(EpochExternalStorage.java:1079)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at com.engflow.re.monitoring.MetricReportingExecutorService$InstrumentedRunnable.run(MetricReportingExecutorService.java:378)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	<abbreviated>

	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:244)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.executeRemotely(RemoteExecutionService.java:1536)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.lambda$exec$2(RemoteSpawnRunner.java:286)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:245)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:127)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:261)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:301)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:152)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:112)
	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:64)
	at com.google.devtools.build.lib.rules.cpp.CppLinkAction.beginExecution(CppLinkAction.java:285)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:961)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1128)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1086)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:160)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:93)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:519)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:827)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:323)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:161)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:562)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: com.google.devtools.build.lib.remote.ExecutionStatusException: INTERNAL: ChB5XT9glm5IzZ7bdFDRnM46EgdkZWZhdWx0GiUKICROHZwOSi4HTK9KRIBcprRKFbhM-OouLOlbbD407mSYEKMB: timeout for : engflow/z-2024-03-08/cas/685c/685cfb1ceeef635df8568a5870743ae064f6dd4d552056a8293d6a46e6497e16
---- cut here ---8<--------8<--------8<--------8<--- cut here ----
com.engflow.storage.s3.S3ClientV2$SyncTimeOutException: timeout for : engflow/z-2024-03-08/cas/685c/685cfb1ceeef635df8568a5870743ae064f6dd4d552056a8293d6a46e6497e16
	at com.engflow.storage.s3.S3ClientV2.asSyncCall(S3ClientV2.java:211)
	at com.engflow.storage.s3.S3ClientV2.upload(S3ClientV2.java:681)
	at com.engflow.re.storage.EpochExternalStorage.lambda$putCasBlob$10(EpochExternalStorage.java:1079)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at com.engflow.re.monitoring.MetricReportingExecutorService$InstrumentedRunnable.run(MetricReportingExecutorService.java:378)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	<abbreviated>

	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.handleStatus(GrpcRemoteExecutor.java:75)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.getOperationResponse(GrpcRemoteExecutor.java:87)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$2(GrpcRemoteExecutor.java:203)
	at com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:245)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:127)
	at com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:116)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.lambda$executeRemotely$3(GrpcRemoteExecutor.java:149)
	at com.google.devtools.build.lib.remote.util.Utils.refreshIfUnauthenticated(Utils.java:523)
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:147)
	... 30 more
Target //examples/swift/hello_world:app failed to build
INFO: Elapsed time: 235.208s, Critical Path: 128.54s
INFO: 2 processes: 2 internal.
ERROR: Build failed. Not running target
```

https://github.com/envoyproxy/envoy/actions/runs/8590744639/job/23538741119#step:8:1213

**Comment by phlax** [comment]
last successful run appears to be https://github.com/envoyproxy/envoy/actions/runs/8579030829

**Comment by phlax** [comment]
this was a infra (RBE) issue and appears to have been fixed
