### ISSUE TITLE
Unable to build 1.30.4 on rhel 8 using the tar package

### ISSUE THREAD

**Issue by nikita96** [envoyproxy/envoy#35091]
*Description*:
Getting error while building envoy 1.30.4 version using bazel on rhel 8.4

user.bazelrc contains : build --config=libc++
Using LLVM : clang+llvm-15.0.0-x86_64-linux-gnu-rhel-8.4

```console
$ bazel build -c opt envoy
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository pkgconfig_src instantiated at:
  /root/envoy/nbenvoy/WORKSPACE:25:25: in <toplevel>
  /root/envoy/nbenvoy/bazel/dependency_imports.bzl:28:34: in envoy_dependency_imports
  /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/rules_foreign_cc/foreign_cc/repositories.bzl:73:25: in rules_foreign_cc_dependencies
  /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/rules_foreign_cc/toolchains/built_toolchains.bzl:55:29: in built_toolchains
  /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/rules_foreign_cc/toolchains/built_toolchains.bzl:265:14: in _pkgconfig_toolchain
  /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz failed: class javax.net.ssl.SSLException Connection reset
ERROR: An error occurred during the fetch of repository 'pkgconfig_src':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz] to /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/pkgconfig_src/temp8819864825272073237/pkg-config-0.29.2.tar.gz: Connection reset
ERROR: /root/envoy/nbenvoy/WORKSPACE:25:25: fetching http_archive rule //external:pkgconfig_src: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz] to /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/pkgconfig_src/temp8819864825272073237/pkg-config-0.29.2.tar.gz: Connection reset
ERROR: /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/rules_foreign_cc/toolchains/BUILD.bazel:317:15: @rules_foreign_cc//toolchains:pkgconfig_tool_default depends on @pkgconfig_src//:all_srcs in repository @pkgconfig_src which failed to fetch. no such package '@pkgconfig_src//': java.io.IOException: Error downloading [https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz] to /root/.cache/bazel/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/pkgconfig_src/temp8819864825272073237/pkg-config-0.29.2.tar.gz: Connection reset
ERROR: Analysis of target '//:envoy' failed; build aborted:
INFO: Elapsed time: 50.580s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (960 packages loaded, 42008 targets configured)
    Fetching repository @remotejdk11_linux; starting 15s
    Fetching repository @com_github_lyft_protoc_gen_star_v2; Restarting. 10s
    Fetching repository @bazel_gazelle_go_repository_config; Restarting. 10s
    Fetching repository @org_golang_google_protobuf; Restarting. 10s
    Fetching repository @bazel_gazelle_go_repository_tools; starting 10s
    Fetching ...el/_bazel_root/87d6ffa924b66ef6624a8f0c8d480ff4/external/remotejdk11_linux; Extracting zulu11.56.19-ca-jdk11.0.15-linux_x64.tar.gz
```

Is this a known issue? If yes, please suggest how to resolve this.

**Comment by nezdolik** [comment]
cc @phlax @keith

**Comment by phlax** [comment]
at first glance this looks like a transient network issue while downloading a dependency - it may be something else though
