### ISSUE TITLE
Error while building envoy image with source code using envoy-build-ubuntu base image

### ISSUE THREAD

**Issue by VishalDamgude** [envoyproxy/envoy#35943]
*Title*: *Error while building envoy image with source code using envoy-build-ubuntu base image*

*Description*:
>We are building a docker image of envoy with custom filter added as a contrib extension. We have a  Dockerfile, and we are running the docker build command on linux ARM machine (aws/codebuild/amazonlinux2-aarch64-standard:2.0).

Dockerfile

```
ARG ENVOY_BASE_IMAGE_TAG
ARG BRANCH
FROM envoyproxy/envoy-build-ubuntu:${ENVOY_BASE_IMAGE_TAG} as envoy

WORKDIR /src
RUN git clone -b <branch> --single-branch https://github.com/<forked repo in our org>

RUN cd /src/envoy && bazel build -c opt --define=no_debug_info=1 --define tcmalloc=gperftools --strip=always //contrib/exe:envoy-static
```

We are using latest tag of envoyproxy/envoy-build-ubuntu:[75238004b0fcfd8a7f71d380d7a774dda5c39622](https://hub.docker.com/layers/envoyproxy/envoy-build-ubuntu/75238004b0fcfd8a7f71d380d7a774dda5c39622/images/sha256-dd843b7cd1f332b96b2083cec894d4794b06bfe8b674614024e522473c577ada?context=explore) as base image.

We want to upgrade our envoy code to 1.30.4. Hence we have updated our branch with code from 1.30.4 tag. And trying to build it.
Earlier we have been able to successfully build the image this way (for both ARM and AMD archs) using an old base image tag(818d28832abf2a7c0cb2bff00435be231729a0bf).

But now getting below error.

```
ERROR:/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/external/rules_foreign_cc/toolchains/BUILD.bazel:214:11: BootstrapNinjaBuild external/rules_foreign_cc/toolchains/ninja [for tool] failed: (Exit 1): bash failed: error executing command (from target @rules_foreign_cc//toolchains:ninja_tool) /bin/bash -c bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/wrapper_build_script.sh
--
466 | #13 44.85
467 | #13 44.85 Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
468 | #13 44.85 rules_foreign_cc: Build failed!
469 | #13 44.85 rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
470 | #13 44.85 rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
471 | #13 44.85 rules_foreign_cc: Printing build logs:
472 | #13 44.85 _____ BEGIN BUILD LOGS _____
473 | #13 44.85 + /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/196/execroot/envoy/external/python3_11_aarch64-unknown-linux-gnu/bin/python3 ./configure.py --bootstrap
474 | #13 44.85 /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/196/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
475 | #13 44.85   import pipes
476 | #13 44.85 /bin/sh: 1: c++: not found
477 | #13 44.85 bootstrapping ninja...
478 | #13 44.85 when running:  c++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3"' -O2 -DNDEBUG -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o
479 | #13 44.85 Traceback (most recent call last):
480 | #13 44.85   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/196/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 470, in <module>
481 | #13 44.85     objs += cxx('browse', order_only=built('browse_py.h'))
482 | #13 44.85             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
483 | #13 44.85   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/196/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 287, in cxx
484 | #13 44.85     return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
485 | #13 44.85            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
486 | #13 44.85   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/196/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 169, in build
487 | #13 44.85     self._run_command(self._expand(cmd, local_vars))
488 | #13 44.85   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/196/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 194, in _run_command
489 | #13 44.85     subprocess.check_call(cmdline, shell=True)
490 | #13 44.85   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/execroot/envoy/external/python3_11_aarch64-unknown-linux-gnu/lib/python3.11/subprocess.py", line 413, in check_call
491 | #13 44.85     raise CalledProcessError(retcode, cmd)
492 | #13 44.85 subprocess.CalledProcessError: Command 'c++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3"' -O2 -DNDEBUG -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o' returned non-zero exit status 127.
493 | #13 44.85 _____ END BUILD LOGS _____
494 | #13 44.85 rules_foreign_cc: Build wrapper script location: bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/wrapper_build_script.sh
495 | #13 44.85 rules_foreign_cc: Build script location: bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/build_script.sh
496 | #13 44.85 rules_foreign_cc: Build log location: bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/BootstrapNinjaBuild.log
497 | #13 44.85
498 | #13 45.01 Target //contrib/exe:envoy-static failed to build
499 | #13 45.01 Use --verbose_failures to see the command lines of failed build steps.
500 | #13 45.04 INFO: Elapsed time: 42.006s, Critical Path: 6.55s
501 | #13 45.04 INFO: 382 processes: 174 internal, 208 processwrapper-sandbox.
502 | #13 45.04 FAILED: Build did NOT complete successfully
503 | #13 45.05

```

I believe, the envoy-build-ubuntu base image comes prepackaged with all the dependencies to build the source code.
Can someone please help with this?

**Comment by phlax** [comment]
hi @VishalDamgude im not sure the current "latest" image works - our build pipeline kinda requires us to publish the image for testing, so the latest on dockerhub is not necessarily the correct one to use

if you check in `.github/config.yml` you will see the correct image to use with that envoy version

in the case of the `release/v1.30` branch that is https://hub.docker.com/layers/envoyproxy/envoy-build-ubuntu/f94a38f62220a2b017878b790b6ea98a0f6c5f9c/images/sha256-f68fce1ddc457b22218ca91138fa198a3087191a359b665b7fef730bff0dbb90?context=explore

**Comment by VishalDamgude** [comment]
Thanks @phlax for responding.

We used the same base image tag that you mentioned - f94a38f62220a2b017878b790b6ea98a0f6c5f9c
But still we are getting the same error.

**Comment by phlax** [comment]
im trying to understand if its an issue with latest envoy code or related to the build image

the error is that it cant find the `c++` binary - which i dont think the image has as such

was it present in previous container images?

**Comment by VishalDamgude** [comment]
No, previously we were using same Dockerfile that I shared, without installing any additional packages inside Dockerfile.

**Comment by phlax** [comment]
i see - thats a very old image - but it _does_ have a `c++` bin on path ...

```console
$ docker run --rm -ti envoyproxy/envoy-build-ubuntu:818d28832abf2a7c0cb2bff00435be231729a0bf which c++
/usr/bin/c++
```

which resolves to `g++`

probably you just need to link c++ to g++ (or use `update-alternatives`)

**Comment by phlax** [comment]
just realized that the current image also doesnt have g++ installed

i think this is related to us removing cmake in favor of using the cmake via bazel (ie hermetic etc)

this was the PR that removed cmake from the build image https://github.com/envoyproxy/envoy-build-tools/pull/209

so most likely undoing that (in your custom image) would pull g++ in as a dep and restore previous situation

**Comment by phlax** [comment]
hmm actually to be precise - we do have g++ installed - but its version installed so not there as `g++` - its there as eg `g++-11`

**Comment by VishalDamgude** [comment]
We installed cmake and ninja-build in dockerfile


 RUN apt update
 RUN apt install -y cmake cmake-data ninja-build
 
 got this error: gcc: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'
 
 ```
 
Writing script external/envoy/bazel/foreign_cc/gperftools_build_foreign_cc/wrapper_build_script.sh
--
675 | #18 78.56 ERROR: /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/external/com_google_absl/absl/base/BUILD.bazel:53:11: Compiling absl/base/log_severity.cc failed: (Exit 1): gcc failed: error executing command (from target @com_google_absl//absl/base:log_severity) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 43 arguments skipped)
676 | #18 78.56
677 | #18 78.56 Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
678 | #18 78.56 gcc: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'?
```


Next we removed above cmake installation steps

And just set the symlink between g++-9 and c++ like this:

RUN ln -sf /usr/bin/g++-9 /usr/bin/c++

But this waym ninja build issue resurfaced>

```

14 589.5 ERROR: /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/external/rules_foreign_cc/toolchains/BUILD.bazel:214:11: BootstrapNinjaBuild external/rules_foreign_cc/toolchains/ninja [for tool] failed: (Exit 1): bash failed: error executing command (from target @rules_foreign_cc//toolchains:ninja_tool) /bin/bash -c bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/wrapper_build_script.sh
--
1953 | #14 589.5
1954 | #14 589.5 Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
1955 | #14 589.5 rules_foreign_cc: Build failed!
1956 | #14 589.5 rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
1957 | #14 589.5 rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
1958 | #14 589.5 rules_foreign_cc: Printing build logs:
1959 | #14 589.5 _____ BEGIN BUILD LOGS _____
1960 | #14 589.5 + /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/1358/execroot/envoy/external/python3_11_aarch64-unknown-linux-gnu/bin/python3 ./configure.py --bootstrap
1961 | #14 589.5 /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/1358/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
1962 | #14 589.5   import pipes
1963 | #14 589.5 /bin/sh: 1: c++: not found
1964 | #14 589.5 bootstrapping ninja...
1965 | #14 589.5 when running:  c++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3"' -O2 -DNDEBUG -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o
1966 | #14 589.5 Traceback (most recent call last):
1967 | #14 589.5   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/1358/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 470, in <module>
1968 | #14 589.5     objs += cxx('browse', order_only=built('browse_py.h'))
1969 | #14 589.5             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1970 | #14 589.5   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/1358/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 287, in cxx
1971 | #14 589.5     return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
1972 | #14 589.5            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1973 | #14 589.5   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/1358/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 169, in build
1974 | #14 589.5     self._run_command(self._expand(cmd, local_vars))
1975 | #14 589.5   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/sandbox/processwrapper-sandbox/1358/execroot/envoy/bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 194, in _run_command
1976 | #14 589.5     subprocess.check_call(cmdline, shell=True)
1977 | #14 589.5   File "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/execroot/envoy/external/python3_11_aarch64-unknown-linux-gnu/lib/python3.11/subprocess.py", line 413, in check_call
1978 | #14 589.5     raise CalledProcessError(retcode, cmd)
1979 | #14 589.5 subprocess.CalledProcessError: Command 'c++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3"' -O2 -DNDEBUG -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o' returned non-zero exit status 127.
1980 | #14 589.5 _____ END BUILD LOGS _____
1981 | #14 589.5 rules_foreign_cc: Build wrapper script location: bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/wrapper_build_script.sh
1982 | #14 589.5 rules_foreign_cc: Build script location: bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/build_script.sh
1983 | #14 589.5 rules_foreign_cc: Build log location: bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/BootstrapNinjaBuild.log
1984 | #14 589.5
1985 | #14 589.6 Target //contrib/exe:envoy-static failed to build

```

@phlax

**Comment by phlax** [comment]
i think my (offline) suggestion was 

```dockerfile
RUN ln -sf /usr/bin/g++-11 /usr/bin/c++
```

and not 

```dockerfile
RUN ln -sf /usr/bin/g++-9 /usr/bin/c++
```

i assume that is why it still cant find c++ in PATH

**Comment by VishalDamgude** [comment]
Actually I used /usr/bin/g++-9 because this is  the version present inside docker container started using [f94a38f62220a2b017878b790b6ea98a0f6c5f9c](https://hub.docker.com/layers/envoyproxy/envoy-build-ubuntu/f94a38f62220a2b017878b790b6ea98a0f6c5f9c/images/sha256-f68fce1ddc457b22218ca91138fa198a3087191a359b665b7fef730bff0dbb90?context=explore))

```
g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

But latest docker image [75238004b0fcfd8a7f71d380d7a774dda5c39622](https://hub.docker.com/layers/envoyproxy/envoy-build-ubuntu/75238004b0fcfd8a7f71d380d7a774dda5c39622/images/sha256-dd843b7cd1f332b96b2083cec894d4794b06bfe8b674614024e522473c577ada?context=explore)

Has g++-11 version.
We will try using latest image once.

But yes, for the image that we used, this did not help

**Comment by VishalDamgude** [comment]
Build is running for good 30-40 minutes but getting this error afterwards:


```ERROR: /root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/external/upb/upbc/BUILD:267:10: Compiling upbc/protoc-gen-upbdefs.cc [for tool] failed: (Exit 1): gcc failed: error executing command (from target @upb//upbc:protoc-gen-upbdefs) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 45 arguments skipped)
848.7 
848.7 Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
848.7 In file included from /usr/include/string.h:495,
848.7                  from external/upb/upb/base/string_view.h:31,
848.7                  from external/upb/upb/collections/message_value.h:34,
848.7                  from external/upb/upb/collections/array.h:32,
848.7                  from external/upb/upb/generated_code_support.h:32,
848.7                  from bazel-out/aarch64-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/src/google/protobuf/descriptor.upb.h:12,
848.7                  from external/upb/upbc/protoc-gen-upbdefs.cc:28:
848.7 In function 'void* memcpy(void*, const void*, size_t)',
848.7     inlined from 'void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)' at external/upb/upb/message/accessors_internal.h:170:13,
848.7     inlined from 'void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)' at external/upb/upb/message/accessors_internal.h:259:33,
848.7     inlined from 'const upb_Array* upb_Message_GetArray(const upb_Message*, const upb_MiniTableField*)' at external/upb/upb/message/accessors.h:320:36:
848.7 /usr/include/aarch64-linux-gnu/bits/string_fortified.h:34:33: error: 'void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)' writing 16 bytes into a region of size 8 overflows the destination [-Werror=stringop-overflow=]
848.7    34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
848.7       |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
848.7 In function 'void* memcpy(void*, const void*, size_t)',
848.7     inlined from 'void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)' at external/upb/upb/message/accessors_internal.h:170:13,
848.7     inlined from 'void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)' at external/upb/upb/message/accessors_internal.h:262:31,
848.7     inlined from 'const upb_Array* upb_Message_GetArray(const upb_Message*, const upb_MiniTableField*)' at external/upb/upb/message/accessors.h:320:36:
848.7 /usr/include/aarch64-linux-gnu/bits/string_fortified.h:34:33: error: 'void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)' writing 16 bytes into a region of size 8 overflows the destination [-Werror=stringop-overflow=]
848.7    34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
848.7       |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
848.7 cc1plus: all warnings being treated as errors
849.4 [2,914 / 6,646] Compiling base/types/map_type.cc; 65s processwrapper-sandbox ... (7 actions running)
850.0 Target //contrib/exe:envoy-static failed to build
850.0 Use --verbose_failures to see the command lines of failed build steps.

```

**Comment by phlax** [comment]
not sure - seems original issue is resolved tho

error looks like this https://github.com/grpc/grpc/issues/35052

**Comment by phlax** [comment]
fwiw our ci is also throwing these warnings - altho would appear not to `-Werror` - is it possible you have some non-standard setting for that ?

**Comment by VishalDamgude** [comment]
We solved this issue by downgrading gcc to version 10

This is how our Dockerfile looks now.

RUN apt update
RUN apt install -y g++-10 gcc-10

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

ENV CC=/usr/bin/gcc-10 CXX=/usr/bin/g++-10


<bazel build command> 

@phlax

**Comment by phlax** [comment]
i guess this works due to gcc 10 being less strict about something

would be good to resolve the actual issue - which looks like a protobuf one to me

**Comment by VishalDamgude** [comment]
Caveat: Even though we used gcc-10, we had to remove "-Werror" from posix_options in bazel/envoy_internal.bzl file

also excluded additional warnings being treated as errors in the same file
repository + "//bazel:gcc_build": ["-Wno-maybe-uninitialized", "-Wno-error=uninitialized", "-Wno-error=stringop-overflow"],

Also, on our AWS codebuild machine, we were getting error regarding non-root user.
So made  ignore_root_user_error= True 

def envoy_dependencies_extra(
        python_version = PYTHON_VERSION,
        ignore_root_user_error = True):
        
        
in bazel/repositories_extra.bzl file

**Comment by phlax** [comment]
with above changes, does not build with gcc-11 - which is what we use

not sure why you are needing to make changes to error handling given it works correctly in our CI

i think the underlying issue is related to protobuf not testing their code on gcc - it throws a **lot** of warnings, some of which we surpress

tbh protobuf code tends to throw a lot of warnings with any compiler, its just a lot worse with gcc

**Comment by VishalDamgude** [comment]
With above changes, code does not build with gcc-11, warnings still get treated as errors.

**Comment by VishalDamgude** [comment]
@phlax ,

We used latest tag v1.31.2 to build our source code and docker image. We were able to compile our code using gcc-11.
Note: I see protobuf version has been upgraded to 26.1 from 25.3 in latest version.

With below config, we were able to compile using gcc-11:
remove "-Werror" from posix_options in bazel/envoy_internal.bzl

set below flags in Dockerfile:
ENV CC=/usr/bin/gcc-11 CXX=/usr/bin/g++-11 BAZEL_COMPILER=/usr/bin/gcc-11

**Comment by phlax** [comment]
good to hear you got it building - still a bit surprised that you need to change anything - we build/test with gcc (11) in our ci
