### ISSUE TITLE
flake: //test/extensions/geoip_providers/maxmind:geoip_provider_test 

### ISSUE THREAD

**Issue by jmarantz** [envoyproxy/envoy#36024]
Leak in ASAN test in CI:
```
=================================================================
==16==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x32402fe in __interceptor_malloc ??:?
    #1 0xa58e994 in operator new(unsigned long) ??:?
    #2 0x334a344 in void std::__1::vector<std::__1::function<absl::lts_20230802::Status (unsigned int)>, std::__1::allocator<std::__1::function<absl::lts_20230802::Status (unsigned int)> > >::__emplace_back_slow_path<std::__1::function<absl::lts_20230802::Status (unsigned int)> >(std::__1::function<absl::lts_20230802::Status (unsigned int)>&&) ??:?
    #3 0x3349ec3 in std::__1::function<absl::lts_20230802::Status (unsigned int)>& std::__1::vector<std::__1::function<absl::lts_20230802::Status (unsigned int)>, std::__1::allocator<std::__1::function<absl::lts_20230802::Status (unsigned int)> > >::emplace_back<std::__1::function<absl::lts_20230802::Status (unsigned int)> >(std::__1::function<absl::lts_20230802::Status (unsigned int)>&&) ??:?
    #4 0x3349b94 in Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}::operator()(std::__1::basic_string_view, unsigned int, absl::lts_20230802::Status (unsigned int)) const ??:?
    #5 0x334994e in decltype ((static_cast<Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}&>({parm#1}))(static_cast<std::__1::basic_string_view>({parm#2}), static_cast<unsigned int>({parm#2}), static_cast<absl::lts_20230802::Status std::__1::__invoke<Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}&, std::__1::basic_string_view, unsigned int, absl::lts_20230802::Status (unsigned int)>(Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}&&, (Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}&)...)(unsigned int)>({parm#2}))) geoip_provider_test.cc:?
    #6 0x3349805 in absl::lts_20230802::Status std::__1::__invoke_void_return_wrapper<absl::lts_20230802::Status, false>::__call<Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}&, std::__1::basic_string_view, unsigned int, absl::lts_20230802::Status (unsigned int)>(Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}&, std::__1::basic_string_view&&, unsigned int&&, absl::lts_20230802::Status (&&)(unsigned int)) ??:?
    #7 0x33497dd in std::__1::__function::__alloc_func<Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}, std::__1::allocator<std::__1::function<absl::lts_20230802::Status (unsigned int)> >, absl::lts_20230802 (std::__1::basic_string_view, unsigned int, absl::lts_20230802::Status (unsigned int))>::operator()(std::__1::basic_string_view&&, unsigned int&&, absl::lts_20230802::Status (&&)(unsigned int)) geoip_provider_test.cc:?
    #8 0x3348fd3 in std::__1::__function::__func<Envoy::Extensions::GeoipProviders::Maxmind::GeoipProviderTestBase::initializeProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<Envoy::ConditionalInitializer>&)::{lambda()#1}::operator()() const::{lambda(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)#1}, std::__1::allocator<std::__1::function<absl::lts_20230802::Status (unsigned int)> >, absl::lts_20230802 (std::__1::basic_string_view, unsigned int, absl::lts_20230802::Status (unsigned int))>::operator()(std::__1::basic_string_view&&, unsigned int&&, absl::lts_20230802::Status (&&)(unsigned int)) ??:?
    #9 0x717a0ed in std::__1::__function::__value_func<absl::lts_20230802::Status (std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)>::operator()(std::__1::basic_string_view<char, std::__1::char_traits<char> >&&, unsigned int&&, std::__1::function<absl::lts_20230802::Status (unsigned int)>&&) const mocks.cc:?
    #10 0x7179f48 in std::__1::function<absl::lts_20230802::Status (std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)>::operator()(std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>) const ??:?
    #11 0x7179cf8 in _ZN7testing8internal9ApplyImplIRKNSt3__18functionIFN4absl12lts_202308026StatusENS2_17basic_string_viewIcNS2_11char_traitsIcEEEEjNS3_IFS6_jEEEEEENS2_5tupleIJSA_jSC_EEEJLm0ELm1ELm2EEEEDTclclsr3stdE7forwardIT_Efp_Espclsr3stdE3getIXT1_EEclsr3stdE7forwardIT0_Efp0_EEEEOSJ_OSK_NS0_13IndexSequenceIJXspT1_EEEE ??:?
    #12 0x7179ba5 in _ZN7testing8internal5ApplyIRKNSt3__18functionIFN4absl12lts_202308026StatusENS2_17basic_string_viewIcNS2_11char_traitsIcEEEEjNS3_IFS6_jEEEEEENS2_5tupleIJSA_jSC_EEEEEDTcl9ApplyImplclsr3stdE7forwardIT_Efp_Eclsr3stdE7forwardIT0_Efp0_EcvNS0_17MakeIndexSequenceIXsr3std10tuple_sizeINS2_16remove_referenceISK_E4typeEEE5valueEEE_EEEOSJ_OSK_ ??:?
    #13 0x7179557 in testing::Action<absl::lts_20230802::Status (std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)>::Perform(std::__1::tuple<std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)> >) const ??:?
    #14 0x717a30d in testing::internal::ActionResultHolder<absl::lts_20230802::Status>* testing::internal::ActionResultHolder<absl::lts_20230802::Status>::PerformAction<absl::lts_20230802::Status (std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)>(testing::Action<absl::lts_20230802::Status (std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)> const&, testing::internal::Function<absl::lts_20230802::Status (std::__1::basic_string_view<char, std::__1::char_traits<char> >, unsigned int, std::__1::function<absl::lts_20230802::Status (unsigned int)>)>::ArgumentTuple&&) ??:?
    #15 0x7177e61 in testing::internal::FunctionMocker<absl::FAIL: //test/extensions/geoip_providers/maxmind:geoip_provider_test (see /build/bazel_root/base/execroot/envoy/bazel-out/k8-dbg/testlogs/test/extensions/geoip_providers/maxmind/geoip_provider_test/test.log)
INFO: From Testing //test/extensions/geoip_providers/maxmind:geoip_provider_test:
```

**Comment by phlax** [comment]
dupe of https://github.com/envoyproxy/envoy/issues/35829
