### ISSUE TITLE
Missing com_googlesource_googleurl dependency

### ISSUE THREAD

**Issue by Pranish-Pantha** [envoyproxy/envoy#36517]
Tried building envoy v1.24.4, build failed due to expected dependency, com_googlesource_googleurl, not found at GCP bucket URL.

`WARNING: Download from https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'com_googlesource_googleurl':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /root/.cache/bazel/_bazel_root/b570b5ccd0454dc9af9f65ab1833764d/external/com_googlesource_googleurl/temp7441268159276836060/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: GET returned 404 Not Found
ERROR: /source/WORKSPACE:23:19: fetching http_archive rule //external:com_googlesource_googleurl: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/b570b5ccd0454dc9af9f65ab1833764d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /root/.cache/bazel/_bazel_root/b570b5ccd04[54](https://github.rbx.com/Roblox/rbx-redis-proxy/actions/runs/12072732/job/36705561#step:5:55)dc9af9f65ab1833764d/external/com_googlesource_googleurl/temp7441268159276836060/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: GET returned 404 Not Found
ERROR: @com_googlesource_googleurl//build_config:system_icu :: Error loading option @com_googlesource_googleurl//build_config:system_icu: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /root/.cache/bazel/_bazel_root/b570b5ccd0454dc9af9f65ab1833764d/external/com_googlesource_googleurl/temp7441268159276836060/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: GET returned 404 Not Found`

**Comment by Pranish-Pantha** [comment]
Looks like #36516  has same issue, so I'll mark this as duplicate
