### ISSUE TITLE
Envoy 1.28.5 Image building failed

### ISSUE THREAD

**Issue by satroutr** [envoyproxy/envoy#36650]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Envoy 1.28.5 Image building failed*

*Description*:
>What issue is being seen? Describe what should be happening instead of
Unable to build envoy image because of its failing to pull the images from google

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs

#16 12.33   /envoy/WORKSPACE:13:19: in <toplevel>

#16 12.33   /envoy/bazel/repositories.bzl:310:32: in envoy_dependencies

#16 12.33   /envoy/bazel/repositories.bzl:1060:26: in _com_googlesource_googleurl

#16 12.33   /envoy/bazel/repositories.bzl:37:23: in external_http_archive

#16 12.33   /build/bazel_root/base/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive

#16 12.33 Repository rule http_archive defined at:

#16 12.33   /build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>

#16 12.36 WARNING: Download from https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.36 ERROR: An error occurred during the fetch of repository 'com_googlesource_googleurl':

#16 12.36    Traceback (most recent call last):

#16 12.36 	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl

#16 12.36 		download_info = ctx.download_and_extract(

#16 12.36 Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp10425872286601993441/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.36 ERROR: /envoy/WORKSPACE:13:19: fetching http_archive rule //external:com_googlesource_googleurl: Traceback (most recent call last):

#16 12.36 	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl

#16 12.36 		download_info = ctx.download_and_extract(

#16 12.36 Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp10425872286601993441/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.36 ERROR: @com_googlesource_googleurl//build_config:system_icu :: Error loading option @com_googlesource_googleurl//build_config:system_icu: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp10425872286601993441/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.38 

#16 ERROR: process "/bin/sh -c ./ci/do_ci.sh bazel.release.server_only.binary" did not complete successfully: exit code: 2

------

 > [envoy_builder 7/7] RUN ./ci/do_ci.sh bazel.release.server_only.binary:

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:

#16 12.33   /envoy/WORKSPACE:13:19: in <toplevel>

#16 12.33   /envoy/bazel/repositories.bzl:310:32: in envoy_dependencies

#16 12.33   /envoy/bazel/repositories.bzl:1060:26: in _com_googlesource_googleurl

#16 12.33   /envoy/bazel/repositories.bzl:37:23: in external_http_archive

#16 12.33   /build/bazel_root/base/external/envoy_api/bazel/envoy_http_archive.bzl:16:17: in envoy_http_archive

#16 12.33 Repository rule http_archive defined at:

#16 12.33   /build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>

#16 12.36 WARNING: Download from https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.36 ERROR: An error occurred during the fetch of repository 'com_googlesource_googleurl':

#16 12.36    Traceback (most recent call last):

#16 12.36 	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl

#16 12.36 		download_info = ctx.download_and_extract(

#16 12.36 Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp10425872286601993441/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.36 ERROR: /envoy/WORKSPACE:13:19: fetching http_archive rule //external:com_googlesource_googleurl: Traceback (most recent call last):

#16 12.36 	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl

#16 12.36 		download_info = ctx.download_and_extract(

#16 12.36 Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp10425872286601993441/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.36 ERROR: @com_googlesource_googleurl//build_config:system_icu :: Error loading option @com_googlesource_googleurl//build_config:system_icu: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp10425872286601993441/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51

#16 12.38 

#16 ERROR: process "/bin/sh -c ./ci/do_ci.sh bazel.release.server_only.binary" did not complete successfully: exit code: 2

------

 > [envoy_builder 7/7] RUN ./ci/do_ci.sh bazel.release.server_only.binary:

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by phlax** [comment]
update to the latest commit on the `release/v1.28` branch - that should resolve your issue/s

1.28 is about to EOL so we are unlikely to cut another release for it

**Comment by satroutr** [comment]
Thanks @phlax 
i have taken the release tag 1.28.7 still i am seeing the same issue
```
#16 12.54   /build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
#16 12.57 WARNING: Download from https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
#16 12.57 ERROR: An error occurred during the fetch of repository 'com_googlesource_googleurl':
#16 12.57    Traceback (most recent call last):
#16 12.57 	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
#16 12.57 		download_info = ctx.download_and_extract(
#16 12.57 Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp13815936647425249279/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
#16 12.57 ERROR: /envoy/WORKSPACE:13:19: fetching http_archive rule //external:com_googlesource_googleurl: Traceback (most recent call last):
#16 12.57 	File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
#16 12.57 		download_info = ctx.download_and_extract(
#16 12.57 Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp13815936647425249279/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
#16 12.58 ERROR: @com_googlesource_googleurl//build_config:system_icu :: Error loading option @com_googlesource_googleurl//build_config:system_icu: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp13815936647425249279/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
#16 12.59 
#16 ERROR: process "/bin/sh -c ./ci/do_ci.sh bazel.release.server_only.binary" did not complete successfully: exit code: 2
```

**Comment by phlax** [comment]
> update to **the latest commit** on the release/v1.28 branch ...

**Comment by zetaab** [comment]
I am trying to compile latest main and getting same error

```
WARNING: Download from https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
ERROR: An error occurred during the fetch of repository 'com_googlesource_googleurl':
   Traceback (most recent call last):
        File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp652063547292919850/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
ERROR: /source/WORKSPACE:13:19: fetching http_archive rule //external:com_googlesource_googleurl: Traceback (most recent call last):
        File "/build/bazel_root/base/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp652063547292919850/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
ERROR: @com_googlesource_googleurl//build_config:system_icu :: Error loading option @com_googlesource_googleurl//build_config:system_icu: java.io.IOException: Error downloading [https://storage.googleapis.com/quiche-envoy-integration/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz] to /build/bazel_root/base/external/com_googlesource_googleurl/temp652063547292919850/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz: Checksum was fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325 but wanted 59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51
```

**Comment by phlax** [comment]
the solution is the same - use the **latest commit** from the `release/v1.28` branch - there will be no further releases of that branch, but the fix is there

**Comment by zetaab** [comment]
@phlax I am using `main` branch and the issue is same.

fixed it now by modifying

```
git diff
diff --git a/bazel/repository_locations.bzl b/bazel/repository_locations.bzl
index 8619e3376f..ad63c5a193 100644
--- a/bazel/repository_locations.bzl
+++ b/bazel/repository_locations.bzl
@@ -1208,7 +1208,7 @@ REPOSITORY_LOCATIONS_SPEC = dict(
         project_url = "https://quiche.googlesource.com/googleurl",
         # Static snapshot of https://quiche.googlesource.com/googleurl/+archive/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz
         version = "dd4080fec0b443296c0ed0036e1e776df8813aa7",
-        sha256 = "59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51",
+        sha256 = "fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325",
         urls = ["https://storage.googleapis.com/quiche-envoy-integration/{version}.tar.gz"],
         use_category = ["controlplane", "dataplane_core"],
         extensions = [],
```

**Comment by congrab** [comment]
Is there any updates on this? I have the same problem with v1.31.2. I tried with later tags but didn't work as well.
I manually downloaded this link https://quiche.googlesource.com/googleurl/+archive/dd4080fec0b443296c0ed0036e1e776df8813aa7.tar.gz

that get the hash `fc694942e8a7491dcc1dde1bddf48a31370a1f46fef862bc17acf07c34dc6325` instead of `59f14d4fb373083b9dc8d389f16bbb817b5f936d1d436aa67e16eb6936028a51`

**Comment by phlax** [comment]
@congrab 

> update to **the latest commit** 

on whichever branch you are trying to build

we are ~imminently going to cut a set of patch releases for unrelated reasons, but **all** supported branches are now fixed at their latest HEAD - as is the now EOL `release/v1.28` branch
