### ISSUE TITLE
Build failed on newest master

### ISSUE THREAD

**Issue by xiaoma2100** [envoyproxy/envoy#3925]
I cloned the newest master on my Ubuntu17.04, and I did ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
it is seems downloaded a docker image, and after that, it is build fail, my env is behind a proxy.
the log is below:
`root@ubuntu:/home/mark/envoy# ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
ENVOY_SRCDIR=/source
HEAD is now at 3e5b733... cleanup: match NOT_IMPLEMENTED_GCOVR_EXCL_LINE change (#53)
building using 4 CPUs
clang-5.0/clang++-5.0 toolchain configured
bazel fastbuild build with tests...
Building...
$TEST_TMPDIR defined: output root default is '/build/tmp' and max_idle_secs default is '15'.
WARNING: ignoring http_proxy in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /build/tmp/_bazel_bazel/436badd4919a15958fa3800a4e21074a/external/io_bazel_rules_go/proto/def.bzl:138:3: You no longer need to call proto_register_toolchains(), it does nothing
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@com_github_fmtlib_fmt' (requested by nodes 'REPOSITORY:@com_github_fmtlib_fmt')
INFO: Elapsed time: 3.204s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (68 packages loaded)
    currently loading: @envoy//ci/prebuilt ... (2 packages)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@com_github_fmtlib_fmt' (requested by nodes 'REPOSITORY:@com_github_fmtlib_fmt')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.sun.security.ntlm.Client.type3(Client.java:161)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.buildType3Msg(NTLMAuthentication.java:250)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.setHeaders(NTLMAuthentication.java:225)
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2114)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:113)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.establishConnection(HttpConnectorMultiplexer.java:301)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:126)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:221)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:131)
        at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:81)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:382)
        ... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@com_github_fmtlib_fmt' (requested by nodes 'REPOSITORY:@com_github_fmtlib_fmt')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.sun.security.ntlm.Client.type3(Client.java:161)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.buildType3Msg(NTLMAuthentication.java:250)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.setHeaders(NTLMAuthentication.java:225)
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2114)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:113)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.establishConnection(HttpConnectorMultiplexer.java:301)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:126)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:221)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:131)
        at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:81)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:382)
        ... 4 more
Remote logging disabled for testing, forcing abrupt shutdown.
com.google.devtools.build.lib.util.LoggingUtil#logToRemote: bazel crashed with args: build --startup_time=9 --binary_path=/usr/bin/bazel --rc_source=client --default_override=0:common=--isatty=1 --default_override=0:common=--terminal_columns=207 --rc_source=/source/ci/tools/bazel.rc --rc_source=/etc/bazel.bazelrc --default_override=1:build:clang-msan=--define --default_override=1:build:clang-msan=ENVOY_CONFIG_MSAN=1 --default_override=1:build:clang-msan=--copt --default_override=1:build:clang-msan=-fsanitize=memory --default_override=1:build:clang-msan=--linkopt --default_override=1:build:clang-msan=-fsanitize=memory --default_override=1:build:clang-msan=--define --default_override=1:build:clang-msan=tcmalloc=disabled --default_override=1:build:clang-msan=--copt --default_override=1:build:clang-msan=-fsanitize-memory-track-origins=2 --default_override=1:test=--test_env=HEAPCHECK=normal --default_override=1:test=--test_env=PPROF_PATH --default_override=1:build:clang-asan=--define --default_override=1:build:clang-asan=ENVOY_CONFIG_ASAN=1 --default_override=1:build:clang-asan=--copt --default_override=1:build:clang-asan=-D__SANITIZE_ADDRESS__ --default_override=1:build:clang-asan=--copt --default_override=1:build:clang-asan=-fsanitize=address,undefined --default_override=1:build:clang-asan=--linkopt --default_override=1:build:clang-asan=-fsanitize=address,undefined --default_override=1:build:clang-asan=--copt --default_override=1:build:clang-asan=-fno-sanitize=vptr --default_override=1:build:clang-asan=--linkopt --default_override=1:build:clang-asan=-fno-sanitize=vptr --default_override=1:build:clang-asan=--copt --default_override=1:build:clang-asan=-fno-sanitize-recover=all --default_override=1:build:clang-asan=--linkopt --default_override=1:build:clang-asan=-ldl --default_override=1:build:clang-asan=--define --default_override=1:build:clang-asan=tcmalloc=disabled --default_override=1:build:clang-asan=--build_tag_filters=-no_asan --default_override=1:build:clang-asan=--test_tag_filters=-no_asan --default_override=1:build:clang-asan=--define --default_override=1:build:clang-asan=signal_trace=disabled --default_override=1:build:clang-asan=--copt --default_override=1:build:clang-asan=-DADDRESS_SANITIZER=1 --default_override=1:build:clang-asan=--test_env=ASAN_SYMBOLIZER_PATH --default_override=1:build:clang-tsan=--define --default_override=1:build:clang-tsan=ENVOY_CONFIG_TSAN=1 --default_override=1:build:clang-tsan=--copt --default_override=1:build:clang-tsan=-fsanitize=thread --default_override=1:build:clang-tsan=--linkopt --default_override=1:build:clang-tsan=-fsanitize=thread --default_override=1:build:clang-tsan=--define --default_override=1:build:clang-tsan=tcmalloc=disabled --default_override=1:build:asan=--define --default_override=1:build:asan=ENVOY_CONFIG_ASAN=1 --default_override=1:build:asan=--copt --default_override=1:build:asan=-fsanitize=address,undefined --default_override=1:build:asan=--linkopt --default_override=1:build:asan=-fsanitize=address,undefined --default_override=1:build:asan=--copt --default_override=1:build:asan=-fno-sanitize=vptr --default_override=1:build:asan=--linkopt --default_override=1:build:asan=-fno-sanitize=vptr --default_override=1:build:asan=--linkopt --default_override=1:build:asan=-ldl --default_override=1:build:asan=--define --default_override=1:build:asan=tcmalloc=disabled --default_override=1:build:asan=--build_tag_filters=-no_asan --default_override=1:build:asan=--test_tag_filters=-no_asan --default_override=1:build:asan=--define --default_override=1:build:asan=signal_trace=disabled --default_override=1:build:asan=--copt --default_override=1:build:asan=-DADDRESS_SANITIZER=1 --default_override=1:build=--workspace_status_command=bazel/get_workspace_status --client_cwd=/source/ci --strategy=Genrule=standalone --spawn_strategy=standalone --verbose_failures --package_path %workspace%:/source --action_env=HOME --action_env=PYTHONUSERBASE --jobs=4 --show_task_finish -c fastbuild //source/exe:envoy-static
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@com_github_fmtlib_fmt' (requested by nodes 'REPOSITORY:@com_github_fmtlib_fmt')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:460)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.sun.security.ntlm.Client.type3(Client.java:161)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.buildType3Msg(NTLMAuthentication.java:250)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.setHeaders(NTLMAuthentication.java:225)
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2114)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:113)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.establishConnection(HttpConnectorMultiplexer.java:301)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:126)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:221)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:131)
        at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:81)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:382)
        ... 4 more
root@ubuntu:/home/mark/envoy# `

the evn:
`root@ubuntu:/home/mark/envoy# uname -a
Linux ubuntu 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`root@ubuntu:/home/mark/envoy# docker --version
Docker version 1.6.2, build 7c8fca2`

**Comment by xiaoma2100** [comment]
I solved this issue, it is because proxy issue.
closed.
