### ISSUE TITLE
envoy proxy grpc server over domain not work

### ISSUE THREAD

**Issue by inetkiller** [envoyproxy/envoy#4358]
*Title*: *envoy proxy grpc server over domain not work*

*Description*:
I use envoy to proxy multi backend grpc services, so i want to use different domain to distinguish different backend grpc service. when change domain from "*" to "grpc.service.com", It seems that envoy is not working properly, my grpc client get error like this:
```shell
Exception in thread "main" io.grpc.StatusRuntimeException: UNIMPLEMENTED
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
        at com.connect.generate.TimedTaskExecutorGrpc$TimedTaskExecutorBlockingStub.execTimedTask(TimedTaskExecutorGrpc.java:150)
        at com.connect.TimeClient.createTimeTask(TimeClient.java:81)
        at com.connect.TimeClient.main(TimeClient.java:132)
```

here is my envoy config file:
```shell static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "grpc.service.com"
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: content-type
                    exact_match: application/grpc
                route:
                  cluster: local_service_grpc
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: local_service_grpc
    connect_timeout: 25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: 192.168.201.99
        port_value: 50052
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901 ```

**Comment by lizan** [comment]
Try use domains with port number, i.e. `grpc.service.com:10000`, gRPC Java is always adding port number to `:authority` header. Or you can use `overrideAuthority` when building channel in your gRPC client.

**Comment by inetkiller** [comment]
@lizan yes, it works. It's releated #886.  thx
