### ISSUE TITLE
http/1.1: make HTTP_MAX_HEADER_SIZE configurable

### ISSUE THREAD

**Issue by javiervazquezh** [envoyproxy/envoy#5626]
*Title*: *http/1.1: make HTTP_MAX_HEADER_SIZE configurable*

*Description*:
>http_parser v2.9.0 supports changing the the max header size at runtime. It'd be great to make this value configurable so it can be increased/decreased without having to fork the library. 

[optional *Relevant Links*:]
> https://github.com/nodejs/http-parser/commit/0ae8d93f7335c0279f37b5ca5c26ea881ac17586

**Comment by alyssawilk** [comment]
Conveniently Auni was about to start working on this, so I'm assigning it his way :-)

**Comment by auni53** [comment]
Just started on this today, you're in luck. 

TODO, apply option to...
- [ ] envoy check in conn_manager
- [ ] nghttp2
- [ ] http_parser

**Comment by auni53** [comment]
@alyssawilk @mattklein123, cc @AndresGuedez 

Need some help debugging a weird case. This is a little bit convoluted so let me try and be thorough.

The current nghttp2 max header limit is 64K, as set by "NGHTTP2_MAX_HEADERSLEN". I confirmed that sending a request whose size exceeds 64K does indeed trigger that check, and closes the stream with error code 0x07 (NGHTTP2_REFUSED_STREAM). I confirmed that sending a request with ~62K of headers does not trigger any errors and the request is decoded.

HOWEVER, sending a request with a byte size of ~63K fails and resets the stream, with a different error. Instead of getting 0x07, I get 0x02 (NGHTTP2_INTERNAL_ERROR). Through trial and error, I determined this internal error is caused by the check at nghttp2_session.c:6036, with this weird-as-hell NGHTTP2_ERR_TEMPORAL_CALLBACK that I don't understand. This occurs with both a single 63K header, as well as with 63 separate 1K headers.

Furthermore, when I disable the correct max header blocks length check (which returns 0x07) and send a 64K request, I expect the codec to correctly process it. Instead, it exhibits the same behaviour as the 63K check with a 0x02 error and the temporal callback stuff.

Sooooo basically, there's some other check that's being triggered by requests that are under the indicated max request headers limit. The call stack in nghttp2 isn't trivially interpretable so I'm very confused with respect to diagnosing where this error is coming from. Andres also suggests that it could be an issue with how Envoy is invoking the nghttp2 library, and not the library itself.

Thoughts?

**Comment by mattklein123** [comment]
@auni53 sorry would need to debug to see what is going on. I don't think it's failing at nghttp2_session.c:6036 as that is in the push promise handling code which we aren't using. Can you potentially provide a callstack of the failure?

**Comment by auni53** [comment]
Test I added to http2/codec_impl_test.cc:
```
TEST_P(Http2CodecImplTest, TestLargeRequestSingleLargeHeaderUnderLimitAccepted) {
  initialize();                                                                  
                                                                                 
  TestHeaderMapImpl request_headers;                                             
  HttpTestUtility::addDefaultHeaders(request_headers);                           
  std::string long_string = std::string(63 * 1024, 'q');                         
  request_headers.addCopy("big", long_string);                                   
                                                                                 
  EXPECT_CALL(server_stream_callbacks_, onResetStream(_)).Times(0);              
  request_encoder_->encodeHeaders(request_headers, true);                        
}                                                                                
```

(call stack and test output coming up)

**Comment by auni53** [comment]
Test invocation: ```

> bt //third_party/envoy/src/test/common/http/http2:codec_impl_test  --test_filter="*Default*LargeRequestSingle*UnderLimitAccepted*/0" --test_output=streamed --test_arg="-l trace"
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Streaming results to http://sponge/4cd00081-0613-47f1-a6d0-bb03b438c284
INFO: Build option --test_filter has changed, discarding analysis cache.
INFO: Analysed target //third_party/envoy/src/test/common/http/http2:codec_impl_test (0 packages loaded, 19587 targets configured).
INFO: Found 1 test target...
Note: Google Test filter = *Default*LargeRequestSingle*UnderLimitAccepted*/0
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Http2CodecImplTestDefaultSettings/Http2CodecImplTest
[ RUN      ] Http2CodecImplTestDefaultSettings/Http2CodecImplTest.TestLargeRequestSingleLargeHeaderUnderLimitAccepted/0
[2019-01-24 17:09:31.830][073786][debug][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:721] [C1] setting stream-level initial window size to 268435456
[2019-01-24 17:09:31.830][073786][debug][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:743] [C1] updating connection-level initial window size to 268435456
[2019-01-24 17:09:31.830][073786][debug][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:721] [C2] setting stream-level initial window size to 268435456
[2019-01-24 17:09:31.830][073786][debug][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:743] [C2] updating connection-level initial window size to 268435456
[2019-01-24 17:09:31.833][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=24
[2019-01-24 17:09:31.833][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:340] [C2] dispatching 24 bytes
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:355] [C2] dispatched 24 bytes
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C2] send data: bytes=15
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:340] [C1] dispatching 15 bytes
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:398] [C1] recv frame type=4
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:355] [C1] dispatched 15 bytes
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=21
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C1] sent frame type=4
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=9
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C1] sent frame type=4
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=13
[2019-01-24 17:09:31.834][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C1] sent frame type=8
[2019-01-24 17:09:31.835][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=16393
[2019-01-24 17:09:31.835][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=16393
[2019-01-24 17:09:31.835][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=16393
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C1] send data: bytes=7322
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C1] sent frame type=1
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C2] sent frame type=4
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C2] send data: bytes=13
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:340] [C1] dispatching 13 bytes
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:398] [C1] recv frame type=8
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:355] [C1] dispatched 13 bytes
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C2] sent frame type=8
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:340] [C2] dispatching 56544 bytes
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:398] [C2] recv frame type=4
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:398] [C2] recv frame type=4
[2019-01-24 17:09:31.836][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:398] [C2] recv frame type=8
temporal callback failure?
temporal callback failure?
temporal callback failure?
temporal callback failure?
temporal callback failure?
temporal callback failure?
it's more likely than u think
temporal callback failure?
[2019-01-24 17:09:31.837][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:355] [C2] dispatched 56544 bytes
[2019-01-24 17:09:31.837][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C2] send data: bytes=9
[2019-01-24 17:09:31.837][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:340] [C1] dispatching 9 bytes
[2019-01-24 17:09:31.837][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:398] [C1] recv frame type=4
[2019-01-24 17:09:31.837][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:355] [C1] dispatched 9 bytes
[2019-01-24 17:09:31.838][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C2] sent frame type=4
[2019-01-24 17:09:31.838][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:554] [C2] send data: bytes=13
[2019-01-24 17:09:31.838][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:340] [C1] dispatching 13 bytes
[2019-01-24 17:09:31.838][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:398] [C1] recv frame type=3
[2019-01-24 17:09:31.838][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:494] [C1] remote reset: 2
[2019-01-24 17:09:31.838][073786][debug][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:563] [C1] stream closed: 2
[2019-01-24 17:09:31.838][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:355] [C1] dispatched 13 bytes
[2019-01-24 17:09:31.838][073786][trace][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:508] [C2] sent frame type=3
[2019-01-24 17:09:31.838][073786][debug][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:518] [C2] sent reset code=2
[2019-01-24 17:09:31.838][073786][debug][http2] [third_party/envoy/src/source/common/http/http2/codec_impl.cc:563] [C2] stream closed: 2
third_party/envoy/src/test/common/http/http2/codec_impl_test.cc:929: Failure
Mock function called more times than expected - returning directly.
    Function call: onResetStream(4-byte object <02-00 00-00>)
         Expected: to be never called
           Actual: called once - over-saturated and active
[  FAILED  ] Http2CodecImplTestDefaultSettings/Http2CodecImplTest.TestLargeRequestSingleLargeHeaderUnderLimitAccepted/0, where GetParam() = ((4096, 2147483647, 268435456, 268435456), (4096, 2147483647, 268435456, 268435456)) (14 ms)
[----------] 1 test from Http2CodecImplTestDefaultSettings/Http2CodecImplTest (14 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (15 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Http2CodecImplTestDefaultSettings/Http2CodecImplTest.TestLargeRequestSingleLargeHeaderUnderLimitAccepted/0, where GetParam() = ((4096, 2147483647, 268435456, 268435456),
```

**Comment by mattklein123** [comment]
Anyway I think you are hitting this logic block: https://github.com/envoyproxy/envoy/blob/master/source/common/http/http2/codec_impl.cc#L647, and we are failing during receiving a header frame.

**Comment by auni53** [comment]
with a break point at onResetStream, here's part of the back trace
```
gdb$ bt
#0  Envoy::Http::MockStreamCallbacks::onResetStream (this=0x555557aa8138, gmock_a1=Envoy::Http::StreamResetReason::RemoteReset) at test/mocks/http/mocks.h:67
#1  0x0000555555c4378e in Envoy::Http::StreamCallbackHelper::runResetCallbacks (this=0x55555775ac28, reason=Envoy::Http::StreamResetReason::RemoteReset) at bazel-out/k8-dbg/bin/source/common/http/_virtual_includes/codec_helper_lib/common/http/codec_helper.h:49
#2  0x0000555555c4cf1a in Envoy::Http::Http2::ConnectionImpl::onStreamClose (this=0x555557762f08, stream_id=0x1, error_code=0x2) at source/common/http/http2/codec_impl.cc:580
#3  0x0000555555c4e96a in Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::<lambda(nghttp2_session*, int32_t, uint32_t, void*)>::operator()(nghttp2_session *, int32_t, uint32_t, void *) const (__closure=0x0, stream_id=0x1, error_code=0x2, user_data=0x555557762f08) at source/common/http/http2/codec_impl.cc:800
#4  0x0000555555c4e9a0 in Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::<lambda(nghttp2_session*, int32_t, uint32_t, void*)>::_FUN(nghttp2_session *, int32_t, uint32_t, void *) () at source/common/http/http2/codec_impl.cc:801
#5  0x0000555555c61636 in nghttp2_session_close_stream (session=session@entry=0x555557ac0a00, stream_id=0x1, error_code=0x2) at ../lib/nghttp2_session.c:1185
#6  0x0000555555c63852 in session_after_frame_sent1 (session=session@entry=0x555557ac0a00) at ../lib/nghttp2_session.c:2698
#7  0x0000555555c6492a in nghttp2_session_mem_send_internal (session=session@entry=0x555557ac0a00, data_ptr=data_ptr@entry=0x7fffffffb098, fast_cb=fast_cb@entry=0x0) at ../lib/nghttp2_session.c:3088
#8  0x0000555555c658fd in nghttp2_session_send (session=0x555557ac0a00) at ../lib/nghttp2_session.c:3239
#9  0x0000555555c4d61d in Envoy::Http::Http2::ConnectionImpl::sendPendingFrames (this=0x555557762f08) at source/common/http/http2/codec_impl.cc:658
#10 0x0000555555c4bba4 in Envoy::Http::Http2::ConnectionImpl::dispatch (this=0x555557762f08, data=...) at source/common/http/http2/codec_impl.cc:359
#11 0x00005555556c046c in Envoy::Http::Http2::Http2CodecImplTest::ConnectionWrapper::dispatch (this=0x555557aa7e28, data=..., connection=...) at test/common/http/http2/codec_impl_test.cc:62
```

**Comment by javiervazquezh** [comment]
By reading #5654 it seems like there is a possibility to cap the header size to 64Kb. 

Our use case requires to up the limit to 100Kb, it'd be great to not limit the header size to 64Kb. Is it possible to set the knob default value to 64KB and leave it to the user decide the actual max size?

**Comment by auni53** [comment]
The limit is constrained by the codec limits, so it wouldn't work correctly even if the user bumped it up. I'm working on bumping up the codec limits after this though, so you'll be able to bump it pass past 100kb once i'm done with all of my work.

**Comment by auni53** [comment]
TODO(me): pass the configured limits onto the individual codec checks.
