### ISSUE TITLE
Crash in access logging of TLS info

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#7179]
```(gdb) bt
#0  0x000000000089f2f7 in OPENSSL_malloc () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#1  0x000000000082c214 in ASN1_STRING_type_new () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#2  0x000000000082d03a in asn1_ex_c2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#3  0x000000000082d761 in asn1_d2i_ex_primitive () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#4  0x000000000082cb9e in asn1_item_ex_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#5  0x000000000082dcfc in asn1_template_noexp_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#6  0x000000000082d1a9 in asn1_template_ex_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#7  0x000000000082cad7 in asn1_item_ex_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#8  0x000000000082dc81 in asn1_template_noexp_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#9  0x000000000082d1a9 in asn1_template_ex_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#10 0x000000000082c54f in asn1_item_ex_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#11 0x000000000082c323 in ASN1_item_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#12 0x00000000008d8c90 in X509V3_get_d2i () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#13 0x0000000000673316 in Envoy::Extensions::TransportSockets::Tls::Utility::getSubjectAltNames (cert=..., type=6) at external/envoy/source/extensions/transport_sockets/tls/utility.cc:48
#14 0x0000000000478ef7 in non-virtual thunk to Envoy::Extensions::TransportSockets::Tls::SslSocket::uriSanLocalCertificate() const ()
    at external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:261
#15 0x0000000000481948 in Envoy::Extensions::AccessLoggers::HttpGrpc::HttpGrpcAccessLog::log (this=0x35bec50, request_headers=0x248b0280, response_headers=0x2f12db80, 
    response_trailers=0x11bdd90 <Envoy::Extensions::AccessLoggers::HttpGrpc::HttpGrpcAccessLog::log(Envoy::Http::HeaderMap const*, Envoy::Http::HeaderMap const*, Envoy::Http::HeaderMap const*, Envoy::StreamInfo::StreamInfo const&)::empty_headers>, stream_info=...) at external/envoy/source/extensions/access_loggers/http_grpc/grpc_access_log_impl.cc:208
#16 0x00000000007c3a6a in Envoy::Http::ConnectionManagerImpl::ActiveStream::~ActiveStream (this=0x27d30e00) at external/envoy/source/common/http/conn_manager_impl.cc:457
#17 0x00000000007c412e in Envoy::Http::ConnectionManagerImpl::ActiveStream::~ActiveStream (this=0x27d30e00) at external/envoy/source/common/http/conn_manager_impl.cc:446
#18 0x00000000006797e7 in operator() (__ptr=0x2ddd680, this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/unique_ptr.h:78
#19 reset (__p=0x2ddd680, this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/unique_ptr.h:376
#20 Envoy::Event::DispatcherImpl::clearDeferredDeleteList (this=0x3619e00) at external/envoy/source/common/event/dispatcher_impl.cc:80
#21 0x0000000000983c11 in event_process_active_single_queue () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#22 0x00000000009826f0 in event_base_loop () at external/com_github_gabime_spdlog/include/spdlog/details/os.h:344
#23 0x000000000067a0ad in Envoy::Event::DispatcherImpl::run (this=<optimized out>, type=Envoy::Event::Dispatcher::Block) at external/envoy/source/common/event/dispatcher_impl.cc:178
#24 0x0000000000674712 in Envoy::Server::WorkerImpl::threadRoutine (this=0x49f6800, guard_dog=...) at external/envoy/source/server/worker_impl.cc:104
#25 0x0000000000b20575 in operator() (this=0x2ddd680) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/std_function.h:706
#26 operator() (this=<optimized out>, arg=0xf27660 <vtable for envoy::api::v2::core::Address+16>) at external/envoy/source/common/common/posix/thread_impl.cc:39
#27 Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::function<void ()>)::$_0::__invoke(void*) (arg=0xf27660 <vtable for envoy::api::v2::core::Address+16>)
    at external/envoy/source/common/common/posix/thread_impl.cc:38
#28 0x0000000000c924b4 in start_thread (arg=0x7f3737475700) at pthread_create.c:312
#29 0x0000000000d44d39 in clone ()
```

Still taking a look at this but I think the transport socket/connection is potentially getting destructed before the stream deferred deletion. cc @lizan @PiotrSikora

**Comment by mattklein123** [comment]
I'm not seeing any way the transport socket can be deleted before the streams, so not sure what is going on here. I will get things compiled with symbols so can get a better trace of what is going on.

**Comment by mattklein123** [comment]
I get a better stack trace of this with ggdb3 and this is actually heap corruption I think due to some of the other issues I have fixed. I'm going to close this for now and will reopen if there are more bugs.

**Comment by mattklein123** [comment]
This is still broken on relatively recent master. There is some heap corruption here, I think somehow related to the fault filter. I will poke around and see if I can figure out what is going on.

**Comment by mattklein123** [comment]
I spotted an issue in the fault filter, will fix that.

**Comment by mattklein123** [comment]
I believe this is fixed via https://github.com/envoyproxy/envoy/pull/7327
