### ISSUE TITLE
Connection reset without sending close header

### ISSUE THREAD

**Issue by jyotima** [envoyproxy/envoy#7228]
*Title*: *Connection reset without sending close header*

*Description*:
In a normal scenario, envoy sends the connection close header to H1 clients to gracefully shutdown the connection and retry.Due to a race condition somewhere in envoy, when the client tries at the exact time of idle and drain timeout, envoy stops accepting new connections completely and does not send the connection close header at all.

*Repro steps*:
Create a flask service `service.py`
```
from flask import Flask
from flask import request
import os
import requests
import socket
import sys

app = Flask(__name__)

TRACE_HEADERS_TO_PROPAGATE = [
    'X-Ot-Span-Context',
    'X-Request-Id',

    # Zipkin headers
    'X-B3-TraceId',
    'X-B3-SpanId',
    'X-B3-ParentSpanId',
    'X-B3-Sampled',
    'X-B3-Flags',
]


@app.route('/service/<service_number>')
def hello(service_number, methods = ['GET', 'POST', 'DELETE']):
  return ('Hello')
if __name__ == "__main__":
  app.run(host='127.0.0.1', port=8080, debug=True)

```
Run the server `python3 service.py`.
Change [this example](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/service-envoy.yaml) in envoy side car to add idle_timeout and drain_timeout : 
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          idle_timeout: 5s
          drain_timeout: 5s
          stat_prefix: ingress_http
``` 
start the envoy side car :
```
envoy-static --component-log-level http:trace,client:trace,connection:trace --log-path ~/tmp/var/log/envoy.log -c service-envoy.yaml --service-cluster service1
```

Create a client that tries making a connection every 10s.(5s idle_timeout + 5s drain_timeout) to the envoy sidecar.

```
import time
import logging
import requests.adapters

logging.basicConfig(
    format='%(asctime)s %(levelname)-8s %(message)s',
    level=logging.DEBUG,
    datefmt='%Y-%m-%d %H:%M:%S',
)

adapter = requests.adapters.HTTPAdapter(
    pool_connections=1,
    pool_maxsize=1,
)
session = requests.Session()
session.mount('http://', adapter)

url = "http://127.0.0.1:80/service/1"
data = '{"ride_id": 1277204843219855626}'
headers = {
    'Host': 'service1',
    'Connection': 'keep-alive',
}

while True:
    try:
        session.get(url, data=data, headers=headers)
    except Exception:
        logging.getLogger('').info('exception')
        raise
    time.sleep(10)
```

The client fails with this exception:
```
➜  tmp python test.py
2019-06-10 16:55:33 DEBUG    Starting new HTTP connection (1): 127.0.0.1:80
2019-06-10 16:55:33 DEBUG    http://127.0.0.1:80 "GET /service/1 HTTP/1.1" 200 5
2019-06-10 16:55:44 INFO     exception
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    session.get(url, data=data, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed
```

This issue happens only when the client tries at the exact juncture of idle_timeout+drain_timeout.
I imagine there is a race condition which is causing this.

*Config*:
Used the [example](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/service-envoy.yaml) config.

*Logs*:
Envoy logs
```
2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:223] initializing epoch 0 (hot restart version=disabled)
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:225] statically linked extensions:
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:227]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:230]   filters.http: envoy.buffer,envoy.cors,envoy.csrf,envoy.ext_authz,envoy.fault,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.original_src,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:233]   filters.listener: envoy.listener.original_dst,envoy.listener.original_src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:236]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.filters.network.zookeeper_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:238]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:240]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.tracers.opencensus,envoy.zipkin
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:243]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:246]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
[2019-06-10 16:55:25.502][5893933][info][main] [source/server/server.cc:252] buffer implementation: old (libevent)
[2019-06-10 16:55:25.525][5893933][info][main] [source/server/server.cc:297] admin address: 0.0.0.0:8081
[2019-06-10 16:55:25.531][5893933][info][main] [source/server/server.cc:404] runtime: layers:
  - static_layer:
      {}
  - admin_layer:
      {}
[2019-06-10 16:55:25.532][5893933][info][config] [source/server/configuration_impl.cc:61] loading 0 static secret(s)
[2019-06-10 16:55:25.532][5893933][info][config] [source/server/configuration_impl.cc:67] loading 1 cluster(s)
[2019-06-10 16:55:25.543][5893933][info][upstream] [source/common/upstream/cluster_manager_impl.cc:147] cm init: all clusters initialized
[2019-06-10 16:55:25.543][5893933][info][config] [source/server/configuration_impl.cc:71] loading 1 listener(s)
[2019-06-10 16:55:25.554][5893933][info][config] [source/server/configuration_impl.cc:96] loading tracing configuration
[2019-06-10 16:55:25.554][5893933][info][config] [source/server/configuration_impl.cc:116] loading stats sink configuration
[2019-06-10 16:55:25.554][5893933][info][main] [source/server/server.cc:471] all clusters initialized. initializing init manager
[2019-06-10 16:55:25.554][5893933][info][config] [source/server/listener_manager_impl.cc:825] all dependencies initialized. starting workers
[2019-06-10 16:55:25.554][5893933][info][main] [source/server/server.cc:487] starting main dispatch loop
[2019-06-10 16:55:33.914][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C0] socket event: 3
[2019-06-10 16:55:33.914][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C0] write ready
[2019-06-10 16:55:33.914][5893960][trace][connection] [source/common/network/connection_impl.cc:494] [C0] read ready
[2019-06-10 16:55:33.914][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:23] [C0] read returns: 200
[2019-06-10 16:55:33.914][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:37] [C0] read error: Resource temporarily unavailable
[2019-06-10 16:55:33.914][5893960][trace][http] [source/common/http/http1/codec_impl.cc:366] [C0] parsing 200 bytes
[2019-06-10 16:55:33.914][5893960][trace][http] [source/common/http/http1/codec_impl.cc:479] [C0] message begin
[2019-06-10 16:55:33.914][5893960][debug][http] [source/common/http/conn_manager_impl.cc:243] [C0] new stream
[2019-06-10 16:55:33.914][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C0] completed header: key=Connection value=keep-alive
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C0] completed header: key=Accept-Encoding value=gzip, deflate
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C0] completed header: key=Accept value=*/*
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C0] completed header: key=User-Agent value=python-requests/2.20.1
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C0] completed header: key=Host value=service1
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:445] [C0] headers complete
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C0] completed header: key=Content-Length value=32
[2019-06-10 16:55:33.917][5893960][debug][http] [source/common/http/conn_manager_impl.cc:583] [C0][S3058139063139669374] request headers complete (end_stream=false):
':authority', 'service1'
':path', '/service/1'
':method', 'GET'
'connection', 'keep-alive'
'accept-encoding', 'gzip, deflate'
'accept', '*/*'
'user-agent', 'python-requests/2.20.1'
'content-length', '32'

[2019-06-10 16:55:33.917][5893960][debug][client] [source/common/http/codec_client.cc:26] [C1] connecting
[2019-06-10 16:55:33.917][5893960][debug][connection] [source/common/network/connection_impl.cc:702] [C1] connecting to 127.0.0.1:8080
[2019-06-10 16:55:33.917][5893960][debug][connection] [source/common/network/connection_impl.cc:711] [C1] connection in progress
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/conn_manager_impl.cc:840] [C0][S3058139063139669374] decode headers called: filter=0xd4b35e0 status=1
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:610] [C0] body size=32
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/conn_manager_impl.cc:961] [C0][S3058139063139669374] decode data called: filter=0xd4b35e0 status=3
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:466] [C0] message complete
[2019-06-10 16:55:33.917][5893960][debug][http] [source/common/http/conn_manager_impl.cc:1069] [C0][S3058139063139669374] request end stream
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/conn_manager_impl.cc:961] [C0][S3058139063139669374] decode data called: filter=0xd4b35e0 status=3
[2019-06-10 16:55:33.917][5893960][trace][http] [source/common/http/http1/codec_impl.cc:387] [C0] parsed 200 bytes
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:288] [C0] readDisable: enabled=true disable=true
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C1] socket event: 2
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C1] write ready
[2019-06-10 16:55:33.917][5893960][debug][connection] [source/common/network/connection_impl.cc:550] [C1] connected
[2019-06-10 16:55:33.917][5893960][debug][client] [source/common/http/codec_client.cc:64] [C1] connected
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:392] [C1] writing 260 bytes, end_stream false
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:392] [C1] writing 32 bytes, end_stream false
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C1] write ready
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:66] [C1] write returns: 292
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C0] socket event: 2
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C0] write ready
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C1] socket event: 2
[2019-06-10 16:55:33.917][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C1] write ready
[2019-06-10 16:55:33.918][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C1] socket event: 2
[2019-06-10 16:55:33.918][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C1] write ready
[2019-06-10 16:55:33.918][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C1] socket event: 1
[2019-06-10 16:55:33.918][5893960][trace][connection] [source/common/network/connection_impl.cc:494] [C1] read ready
[2019-06-10 16:55:33.918][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:23] [C1] read returns: 153
[2019-06-10 16:55:33.918][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:23] [C1] read returns: 5
[2019-06-10 16:55:33.918][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:23] [C1] read returns: 0
[2019-06-10 16:55:33.918][5893960][trace][http] [source/common/http/http1/codec_impl.cc:366] [C1] parsing 158 bytes
[2019-06-10 16:55:33.918][5893960][trace][http] [source/common/http/http1/codec_impl.cc:479] [C1] message begin
[2019-06-10 16:55:33.918][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C1] completed header: key=Content-Type value=text/html; charset=utf-8
[2019-06-10 16:55:33.918][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C1] completed header: key=Content-Length value=5
[2019-06-10 16:55:33.918][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C1] completed header: key=Server value=Werkzeug/0.15.4 Python/3.7.3
[2019-06-10 16:55:33.918][5893960][trace][http] [source/common/http/http1/codec_impl.cc:445] [C1] headers complete
[2019-06-10 16:55:33.918][5893960][trace][http] [source/common/http/http1/codec_impl.cc:334] [C1] completed header: key=Date value=Mon, 10 Jun 2019 23:55:33 GMT
[2019-06-10 16:55:33.919][5893960][debug][http] [source/common/http/conn_manager_impl.cc:1336] [C0][S3058139063139669374] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'text/html; charset=utf-8'
'content-length', '5'
'server', 'envoy'
'date', 'Mon, 10 Jun 2019 23:55:33 GMT'
'x-envoy-upstream-service-time', '1'
[2019-06-10 16:55:33.919][5893960][trace][connection] [source/common/network/connection_impl.cc:392] [C0] writing 164 bytes, end_stream false
[2019-06-10 16:55:33.919][5893960][trace][http] [source/common/http/conn_manager_impl.cc:1474] [C0][S3058139063139669374] encoding data via codec (size=5 end_stream=false)
[2019-06-10 16:55:33.919][5893960][trace][connection] [source/common/network/connection_impl.cc:392] [C0] writing 5 bytes, end_stream false
[2019-06-10 16:55:33.919][5893960][trace][http] [source/common/http/http1/codec_impl.cc:466] [C1] message complete
[2019-06-10 16:55:33.919][5893960][trace][http] [source/common/http/http1/codec_impl.cc:736] [C1] message complete
[2019-06-10 16:55:33.919][5893960][debug][client] [source/common/http/codec_client.cc:95] [C1] response complete
[2019-06-10 16:55:33.920][5893960][trace][http] [source/common/http/conn_manager_impl.cc:1474] [C0][S3058139063139669374] encoding data via codec (size=0 end_stream=true)
[2019-06-10 16:55:33.921][5893960][trace][connection] [source/common/network/connection_impl.cc:288] [C0] readDisable: enabled=false disable=false
[2019-06-10 16:55:33.921][5893960][debug][connection] [source/common/network/connection_impl.cc:101] [C1] closing data_to_write=0 type=1
[2019-06-10 16:55:33.921][5893960][debug][connection] [source/common/network/connection_impl.cc:188] [C1] closing socket: 1
[2019-06-10 16:55:33.921][5893960][debug][client] [source/common/http/codec_client.cc:82] [C1] disconnect. resetting 0 pending requests
[2019-06-10 16:55:33.921][5893960][trace][http] [source/common/http/http1/codec_impl.cc:387] [C1] parsed 158 bytes
[2019-06-10 16:55:33.921][5893960][debug][connection] [source/common/network/connection_impl.cc:518] [C1] remote close
[2019-06-10 16:55:33.921][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C0] socket event: 2
[2019-06-10 16:55:33.921][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C0] write ready
[2019-06-10 16:55:33.921][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:66] [C0] write returns: 169
[2019-06-10 16:55:33.921][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C0] socket event: 2
[2019-06-10 16:55:33.921][5893960][trace][connection] [source/common/network/connection_impl.cc:541] [C0] write ready
[2019-06-10 16:55:38.922][5893960][debug][http] [source/common/http/conn_manager_impl.cc:361] [C0] idle timeout
[2019-06-10 16:55:43.927][5893960][debug][connection] [source/common/network/connection_impl.cc:101] [C0] closing data_to_write=0 type=2
[2019-06-10 16:55:43.927][5893960][debug][connection] [source/common/network/connection_impl.cc:651] [C0] setting delayed close timer with timeout 1000 ms
[2019-06-10 16:55:43.929][5893960][trace][connection] [source/common/network/connection_impl.cc:456] [C0] socket event: 1
[2019-06-10 16:55:43.929][5893960][trace][connection] [source/common/network/connection_impl.cc:494] [C0] read ready
[2019-06-10 16:55:43.929][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:23] [C0] read returns: 200
[2019-06-10 16:55:43.929][5893960][trace][connection] [source/common/network/raw_buffer_socket.cc:37] [C0] read error: Resource temporarily unavailable
[2019-06-10 16:55:44.928][5893960][debug][connection] [source/common/network/connection_impl.cc:640] [C0] triggered delayed close
[2019-06-10 16:55:44.928][5893960][debug][connection] [source/common/network/connection_impl.cc:188] [C0] closing socket: 1
```

**Comment by mattklein123** [comment]
I think this is WAI. There is a chance that you try to make the connection when Envoy is already in the process of closing the connection. This is an inherent race condition with HTTP/1. See https://github.com/envoyproxy/envoy/pull/7159 and other linked issues for similar discussion.

**Comment by jyotima** [comment]
@mattklein123 Thanks for the guidance. The next natural question is that urllib3 python library is not able to transparently handle this. Is it always recommended for H1 clients to retry on  `RemoteDisconnected` failures to mitigate this issue?
I would implement RemoteDisconnected as an expected exception in our python and go clients if that were the case. 

If not, what is the most efficient and known way to handle this kind of error transparently?

**Comment by mattklein123** [comment]
> If not, what is the most efficient and known way to handle this kind of error transparently?

It depends on your application, but in general I would not try to handle this race condition. Let it fail and let the caller retry.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy/issues/7248

**Comment by jyotimahapatra** [comment]
@mattklein123 Thanks for the help. I will close the issue now. We implemented retry at the client side.
