### ISSUE TITLE
Issue running tools/check_spelling_pedantic.py locally

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#8722]
Running check_pedantic_spelling.py locally results in 

```
~/Development/envoy(h1-casing):0 tools/check_spelling_pedantic.py fix
Traceback (most recent call last):
  File "tools/check_spelling_pedantic.py", line 540, in <module>
    locale.setlocale(locale.LC_ALL, 'C.UTF-8')
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

This is on OS X. 

cc @zuercher

**Comment by mattklein123** [comment]
I think this is a dup and was fixed.
