### ISSUE TITLE
Java GRPC call serialization failing

### ISSUE THREAD

**Issue by prateek0394** [envoyproxy/envoy#8985]
*Title*: *Java GRPC call from envoy proxy failing in serialization*

*Description*:
Hi folks,
I am using EnvoyProxy - 1.11.1 version, where I have a Java GRPC service which does external authorization. While Envoy sends authorization request to the Java GRPC service, I am getting following exception trace : 
java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.shouldDiscardUnknownFields()Z
	at com.google.protobuf.GeneratedMessageV3$ExtendableMessage.parseUnknownField(GeneratedMessageV3.java:1126)
	at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:27378)
	at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:27277)
	at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:29285)
	at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:29279)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11236)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11128)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:13546)
	at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:13540)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
	at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:5053)
	at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:4989)
	at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:9917)
	at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:9911)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1249)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1169)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4724)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4718)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:139)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:173)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:190)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom(DescriptorProtos.java:2201)
	at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:410)
	at io.envoyproxy.envoy.type.PercentProto.<clinit>(PercentProto.java:48)
	at io.envoyproxy.envoy.api.v2.core.BaseProto.<clinit>(BaseProto.java:148)
	at io.envoyproxy.envoy.api.v2.core.AddressProto.<clinit>(AddressProto.java:89)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContextProto.<clinit>(AttributeContextProto.java:96)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$HttpRequest$HeadersDefaultEntryHolder.<clinit>(AttributeContext.java:3166)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$HttpRequest.<init>(AttributeContext.java:2971)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$HttpRequest.<init>(AttributeContext.java:2905)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$HttpRequest$1.parsePartialFrom(AttributeContext.java:5168)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$HttpRequest$1.parsePartialFrom(AttributeContext.java:5162)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$Request.<init>(AttributeContext.java:1829)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$Request.<init>(AttributeContext.java:1769)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$Request$1.parsePartialFrom(AttributeContext.java:2622)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$Request$1.parsePartialFrom(AttributeContext.java:2616)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext.<init>(AttributeContext.java:91)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext.<init>(AttributeContext.java:17)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$1.parsePartialFrom(AttributeContext.java:6536)
	at io.envoyproxy.envoy.service.auth.v2.AttributeContext$1.parsePartialFrom(AttributeContext.java:6530)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
	at io.envoyproxy.envoy.service.auth.v2.CheckRequest.<init>(CheckRequest.java:56)
	at io.envoyproxy.envoy.service.auth.v2.CheckRequest.<init>(CheckRequest.java:9)
	at io.envoyproxy.envoy.service.auth.v2.CheckRequest$1.parsePartialFrom(CheckRequest.java:629)
	at io.envoyproxy.envoy.service.auth.v2.CheckRequest$1.parsePartialFrom(CheckRequest.java:623)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:301)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:773)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I am using Google Protocol Buffers : 3.8.0 version and ProtoBuf-Java 
 3.8.0 version (https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.8.0). 

My configuration at envoy for ext-auth cluster:
Filter config :
- name: envoy.ext_authz
            config:
              grpc_service:
                envoy_grpc:
                  cluster_name: <<CLUSTER_NAME>>
                timeout : 1s
Cluster config:
- name : <<CLUSTER_NAME>>
    type : static
    circuit_breakers:
      thresholds:
      - priority: DEFAULT
        max_connections: 20000
        max_requests: 20000
    http2_protocol_options:
      max_concurrent_streams:
        value: 100
    load_assignment:
      cluster_name: <<CLUSTER_NAME>>
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8980
    connect_timeout: 0.25s
    health_checks:
      - timeout: 0.25s
        interval: 60s
        reuse_connection: true
        unhealthy_threshold: 3
        healthy_threshold: 3
        no_traffic_interval: 30s
        grpc_health_check:
          service_name: <<SERVICE_NAME>>

I checked the jar on my machine and the jar is present with correct version.
Any ideas what is causing this issue. What am I missing here?

Thanks in advance.

**Comment by prateek0394** [comment]
To add, the proto libraries I have in my environment : 
grpc-protobuf-1.22.1.jar
grpc-protobuf-lite-1.22.1.jar
libprotobuf-lite.so
libprotobuf-lite.so.3.8.0.0
libprotobuf.so
libprotobuf.so.3.8.0.0
libprotoc.so
libprotoc.so.3.8.0.0
protobuf-java-3.8.0.jar
protobuf-javanano-3.2.0rc2.jar
protobuf-lite-3.0.1.jar
proto-google-common-protos-1.16.0.jar

**Comment by htuch** [comment]
@prateek0394 this seems like a gRPC library bug? Regarding unknown fields, are you using the same proto descriptors on Envoy and server?

**Comment by prateek0394** [comment]
@htuch I have referenced this repository to extract the envoy defined proto files : https://github.com/envoyproxy/java-control-plane

**Comment by htuch** [comment]
@prateek0394 that seems reasonably up-to-date (at least 1.12.0). In any case, I think the stack trace here is an issue in your use of protobuf/gRPC or the libraries themselves, so not sure what is actionable on the Envoy front.

**Comment by prateek0394** [comment]
@htuch I agree with you, there isnt much from Envoy front. I wanted to check with envoy-users if anyone else has experienced the similar issue and can point me to correct direction so that I can resolve this.

**Comment by prateek0394** [comment]
Hey guys,

Found the issue. My lib path had GoogleProtoBuf as well as GoogleProtoBuf-Lite library and at runtime java was picking up CodedInputStream class from GoogleProtoBuf-lite which didnt has the method "shouldDiscardUnknownFields" due to which serialization was failing. 
Closing this issue.
