### ISSUE TITLE
ExtAuthzGrpcIntegrationTest flake

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#9562]
```
2020-01-05T18:10:44.2242604Z [----------] 16 tests from IpVersionsCientType/ExtAuthzGrpcIntegrationTest
2020-01-05T18:10:44.2242866Z [ RUN      ] IpVersionsCientType/ExtAuthzGrpcIntegrationTest.HTTP1DownstreamRequestWithBody/0
2020-01-05T18:10:44.2243349Z test/integration/fake_upstream.cc:91:14: runtime error: member call on address 0x618000030080 which does not point to an object of type 'Envoy::Http::StreamEncoder'
2020-01-05T18:10:44.2274599Z 0x618000030080: note: object has invalid vptr
2020-01-05T18:10:44.2275364Z  d6 00 80 60  c5 00 00 74 00 00 00 00  08 aa c2 1c 00 00 00 00  50 05 18 00 30 60 00 00  00 be be be
2020-01-05T18:10:44.2276205Z               ^~~~~~~~~~~~~~~~~~~~~~~
2020-01-05T18:10:44.2277678Z               invalid vptr
2020-01-05T18:10:44.2278531Z     #0 0xe8689da in Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1::operator()() const /proc/self/cwd/test/integration/fake_upstream.cc:91:14
2020-01-05T18:10:44.2279664Z     #1 0xe868791 in decltype(std::__1::forward<Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1&>(fp)()) std::__1::__invoke<Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1&>(Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1
2020-01-05T18:10:44.2280940Z     #2 0xe8685d1 in void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1&>(Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9
2020-01-05T18:10:44.2283051Z     #3 0xe86851f in std::__1::__function::__alloc_func<Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1, std::__1::allocator<Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1533:16
2020-01-05T18:10:44.2284021Z     #4 0xe862f44 in std::__1::__function::__func<Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1, std::__1::allocator<Envoy::FakeStream::encodeHeaders(Envoy::Http::HeaderMapImpl const&, bool)::$_1>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1707:12
2020-01-05T18:10:44.2284507Z     #5 0xe7f5bf9 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:1860:16
2020-01-05T18:10:44.2285170Z     #6 0xe7f524a in std::__1::function<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:2419:12
2020-01-05T18:10:44.2285547Z     #7 0x170661cb in Envoy::Event::DispatcherImpl::runPostCallbacks() /proc/self/cwd/source/common/event/dispatcher_impl.cc:224:5
2020-01-05T18:10:44.2344147Z     #8 0x17075971 in Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1::operator()() const /proc/self/cwd/source/common/event/dispatcher_impl.cc:43:58
2020-01-05T18:10:44.2396984Z     #9 0x17075821 in decltype(std::__1::forward<Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1&>(fp)()) std::__1::__invoke<Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1&>(Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1
2020-01-05T18:10:44.2397700Z     #10 0x17075661 in void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1&>(Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9
2020-01-05T18:10:44.2398155Z     #11 0x170755af in std::__1::__function::__alloc_func<Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1, std::__1::allocator<Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1533:16
2020-01-05T18:10:44.2398592Z     #12 0x17070014 in std::__1::__function::__func<Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1, std::__1::allocator<Envoy::Event::DispatcherImpl::DispatcherImpl(std::__1::unique_ptr<Envoy::Buffer::WatermarkFactory, std::__1::default_delete<Envoy::Buffer::WatermarkFactory> >&&, Envoy::Api::Api&, Envoy::Event::TimeSystem&)::$_1>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1707:12
2020-01-05T18:10:44.2399025Z     #13 0xe7f5bf9 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:1860:16
2020-01-05T18:10:44.2399240Z     #14 0xe7f524a in std::__1::function<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:2419:12
2020-01-05T18:10:44.2399464Z     #15 0x1753dca8 in Envoy::Event::TimerImpl::TimerImpl(Envoy::CSmartPtr<event_base, &(event_base_free)>&, std::__1::function<void ()>, Envoy::Event::Dispatcher&)::$_0::operator()(int, short, void*) const /proc/self/cwd/source/common/event/timer_impl.cc:15:3
2020-01-05T18:10:44.2399726Z     #16 0x1753d85d in Envoy::Event::TimerImpl::TimerImpl(Envoy::CSmartPtr<event_base, &(event_base_free)>&, std::__1::function<void ()>, Envoy::Event::Dispatcher&)::$_0::__invoke(int, short, void*) /proc/self/cwd/source/common/event/timer_impl.cc:15:3
2020-01-05T18:10:44.2399956Z     #17 0x1b9b250d in event_process_active_single_queue /b/f/w/external/com_github_libevent_libevent/event.c:1713:4
2020-01-05T18:10:44.2400130Z     #18 0x1b989f16 in event_process_active /b/f/w/external/com_github_libevent_libevent/event.c:1805:9
2020-01-05T18:10:44.2400265Z     #19 0x1b981863 in event_base_loop /b/f/w/external/com_github_libevent_libevent/event.c:2047:12
2020-01-05T18:10:44.2400453Z     #20 0x17535155 in Envoy::Event::LibeventScheduler::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/libevent_scheduler.cc:47:3
2020-01-05T18:10:44.2400641Z     #21 0x17065b9b in Envoy::Event::DispatcherImpl::run(Envoy::Event::Dispatcher::RunType) /proc/self/cwd/source/common/event/dispatcher_impl.cc:196:19
2020-01-05T18:10:44.2400833Z     #22 0xe84a45a in Envoy::FakeUpstream::threadRoutine() /proc/self/cwd/test/integration/fake_upstream.cc:459:16
2020-01-05T18:10:44.2401179Z     #23 0xe8b5d51 in Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11::operator()() const /proc/self/cwd/test/integration/fake_upstream.cc:422:67
2020-01-05T18:10:44.2401687Z     #24 0xe8b5c01 in decltype(std::__1::forward<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11&>(fp)()) std::__1::__invoke<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11&>(Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11&) /opt/llvm/bin/../include/c++/v1/type_traits:3530:1
2020-01-05T18:10:44.2402342Z     #25 0xe8b5a41 in void std::__1::__invoke_void_return_wrapper<void>::__call<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11&>(Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11&) /opt/llvm/bin/../include/c++/v1/__functional_base:348:9
2020-01-05T18:10:44.2402972Z     #26 0xe8b598f in std::__1::__function::__alloc_func<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11, std::__1::allocator<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1533:16
2020-01-05T18:10:44.2403538Z     #27 0xe8b03f4 in std::__1::__function::__func<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11, std::__1::allocator<Envoy::FakeUpstream::FakeUpstream(std::__1::unique_ptr<Envoy::Network::TransportSocketFactory, std::__1::default_delete<Envoy::Network::TransportSocketFactory> >&&, std::__1::unique_ptr<Envoy::Network::Socket, std::__1::default_delete<Envoy::Network::Socket> >&&, Envoy::FakeHttpConnection::Type, Envoy::Event::TestTimeSystem&, bool)::$_11>, void ()>::operator()() /opt/llvm/bin/../include/c++/v1/functional:1707:12
2020-01-05T18:10:44.2404010Z     #28 0xe7f5bf9 in std::__1::__function::__value_func<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:1860:16
2020-01-05T18:10:44.2404221Z     #29 0xe7f524a in std::__1::function<void ()>::operator()() const /opt/llvm/bin/../include/c++/v1/functional:2419:12
2020-01-05T18:10:44.2404420Z     #30 0x1b931e04 in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::operator()(void*) const /proc/self/cwd/source/common/common/posix/thread_impl.cc:33:9
2020-01-05T18:10:44.2404624Z     #31 0x1b931cbc in Envoy::Thread::ThreadImplPosix::ThreadImplPosix(std::__1::function<void ()>)::$_0::__invoke(void*) /proc/self/cwd/source/common/common/posix/thread_impl.cc:32:7
2020-01-05T18:10:44.2405182Z     #32 0x7fafb671d6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
2020-01-05T18:10:44.2405635Z     #33 0x7fafb623b41c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)
2020-01-05T18:10:44.2405795Z 
2020-01-05T18:10:44.2406176Z SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test/integration/fake_upstream.cc:91:14 in 
2020-01-05T18:10:44.2406483Z ================================================================================
```

**Comment by mattklein123** [comment]
cc @dio

**Comment by mattklein123** [comment]
Haven't seen this in a while.
