### ISSUE TITLE
flake in http-filter-example:http_filter_integration_test 

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#9989]
[Feb 9](https://dev.azure.com/cncf/envoy/_build/results?buildId=30213&view=logs&j=930b2ee4-0ea7-5b74-a645-6bc26962bc06&t=a22da363-b496-51fd-d3eb-ba836106d671)
[Feb 6](https://dev.azure.com/cncf/envoy/_build/results?buildId=29858&view=logs&j=930b2ee4-0ea7-5b74-a645-6bc26962bc06&t=a22da363-b496-51fd-d3eb-ba836106d671)

I think this may just be 5 ms is not enough time to wait on a load host running instrumented tests.

```
2020-02-09T20:09:48.3635590Z FAIL: //http-filter-example:http_filter_integration_test (see /build/tmp/_bazel_bazel/400406edc57d332f0b9b805d2b8e33a1/execroot/envoy_filter_example/bazel-out/k8-dbg/testlogs/http-filter-example/http_filter_integration_test/test.log)
2020-02-09T20:09:48.3637885Z INFO: From Testing //http-filter-example:http_filter_integration_test:
2020-02-09T20:09:48.3639116Z ==================== Test output for //http-filter-example:http_filter_integration_test:
2020-02-09T20:09:48.3639557Z [==========] Running 2 tests from 1 test suite.
2020-02-09T20:09:48.3640478Z [----------] Global test environment set-up.
2020-02-09T20:09:48.3640932Z [----------] 2 tests from IpVersions/HttpFilterSampleIntegrationTest
2020-02-09T20:09:48.3641182Z [ RUN      ] IpVersions/HttpFilterSampleIntegrationTest.Test1/0
2020-02-09T20:09:48.3641593Z http-filter-example/http_filter_integration_test.cc:33: Failure
2020-02-09T20:09:48.3642093Z Value of: fake_upstreams_[0]->waitForHttpConnection(*dispatcher_, fake_upstream_connection, std::chrono::milliseconds(5))
2020-02-09T20:09:48.3642355Z   Actual: false (Timed out waiting for new connection.)
2020-02-09T20:09:48.3642566Z Expected: true
2020-02-09T20:09:48.3642749Z Stack trace:
2020-02-09T20:09:48.3642961Z   0x17d9fe60: Envoy::HttpFilterSampleIntegrationTest_Test1_Test::TestBody()
2020-02-09T20:09:48.3643299Z   0x2e88313e: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
2020-02-09T20:09:48.3643516Z   0x2e833646: testing::internal::HandleExceptionsInMethodIfSupported<>()
2020-02-09T20:09:48.3643746Z   0x2e7dee77: testing::Test::Run()
2020-02-09T20:09:48.3643959Z   0x2e7e1b80: testing::TestInfo::Run()
2020-02-09T20:09:48.3644168Z ... Google Test internal frames ...
2020-02-09T20:09:48.3644326Z 
2020-02-09T20:09:48.3644972Z [2020-02-09 20:09:42.091][17][critical][assert] [external/envoy/source/common/network/connection_impl.cc:74] assert failure: !ioHandle().isOpen() && delayed_close_timer_ == nullptr. Details: ConnectionImpl was unexpectedly torn down without being closed.
2020-02-09T20:09:48.3645332Z AddressSanitizer:DEADLYSIGNAL
2020-02-09T20:09:48.3645555Z =================================================================
2020-02-09T20:09:48.3645792Z ==17==ERROR: AddressSanitizer: ABRT on unknown address 0xfffe00000011 (pc 0x7fe1d86c8428 bp 0x7ffcc2034540 sp 0x7ffcc2034168 T0)
2020-02-09T20:09:48.3646281Z     #0 0x7fe1d86c8427 in raise (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
2020-02-09T20:09:48.3646742Z     #1 0x7fe1d86ca029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
2020-02-09T20:09:48.3647020Z     #2 0x28308b29 in Envoy::Network::ConnectionImpl::~ConnectionImpl() /proc/self/cwd/external/envoy/source/common/network/connection_impl.cc:73:3
2020-02-09T20:09:48.3647659Z     #3 0x28353081 in Envoy::Network::ClientConnectionImpl::~ClientConnectionImpl() /proc/self/cwd/bazel-out/k8-dbg/bin/external/envoy/source/common/network/_virtual_includes/connection_lib/common/network/connection_impl.h:187:7
2020-02-09T20:09:48.3648371Z     #4 0x2834e25b in Envoy::Network::ClientConnectionImpl::~ClientConnectionImpl() /proc/self/cwd/bazel-out/k8-dbg/bin/external/envoy/source/common/network/_virtual_includes/connection_lib/common/network/connection_impl.h:187:7
2020-02-09T20:09:48.3649065Z     #5 0x2834e2f4 in Envoy::Network::ClientConnectionImpl::~ClientConnectionImpl() /proc/self/cwd/bazel-out/k8-dbg/bin/external/envoy/source/common/network/_virtual_includes/connection_lib/common/network/connection_impl.h:187:7
2020-02-09T20:09:48.3649418Z     #6 0x1e59cb51 in std::__1::default_delete<Envoy::Network::ClientConnection>::operator()(Envoy::Network::ClientConnection*) const /opt/llvm/bin/../include/c++/v1/memory:2338:5
2020-02-09T20:09:48.3649754Z     #7 0x1e59c7ec in std::__1::unique_ptr<Envoy::Network::ClientConnection, std::__1::default_delete<Envoy::Network::ClientConnection> >::reset(Envoy::Network::ClientConnection*) /opt/llvm/bin/../include/c++/v1/memory:2593:7
2020-02-09T20:09:48.3650132Z     #8 0x1e594ce8 in std::__1::unique_ptr<Envoy::Network::ClientConnection, std::__1::default_delete<Envoy::Network::ClientConnection> >::~unique_ptr() /opt/llvm/bin/../include/c++/v1/memory:2547:19
2020-02-09T20:09:48.3650441Z     #9 0x26b9e1ea in Envoy::Http::CodecClient::~CodecClient() /proc/self/cwd/external/envoy/source/common/http/codec_client.cc:47:27
2020-02-09T20:09:48.3651077Z     #10 0x203ce3e7 in Envoy::Http::CodecClientProd::~CodecClientProd() /proc/self/cwd/bazel-out/k8-dbg/bin/external/envoy/source/common/http/_virtual_includes/codec_client_lib/common/http/codec_client.h:243:7
2020-02-09T20:09:48.3651395Z     #11 0x203d871b in Envoy::IntegrationCodecClient::~IntegrationCodecClient() /proc/self/cwd/external/envoy/test/integration/http_integration.h:19:7
2020-02-09T20:09:48.3651765Z     #12 0x203d8784 in Envoy::IntegrationCodecClient::~IntegrationCodecClient() /proc/self/cwd/external/envoy/test/integration/http_integration.h:19:7
2020-02-09T20:09:48.3652062Z     #13 0x17ead261 in std::__1::default_delete<Envoy::IntegrationCodecClient>::operator()(Envoy::IntegrationCodecClient*) const /opt/llvm/bin/../include/c++/v1/memory:2338:5
2020-02-09T20:09:48.3652386Z     #14 0x17eacefc in std::__1::unique_ptr<Envoy::IntegrationCodecClient, std::__1::default_delete<Envoy::IntegrationCodecClient> >::reset(Envoy::IntegrationCodecClient*) /opt/llvm/bin/../include/c++/v1/memory:2593:7
2020-02-09T20:09:48.3652770Z     #15 0x17da4ac8 in std::__1::unique_ptr<Envoy::IntegrationCodecClient, std::__1::default_delete<Envoy::IntegrationCodecClient> >::~unique_ptr() /opt/llvm/bin/../include/c++/v1/memory:2547:19
2020-02-09T20:09:48.3653377Z     #16 0x17da1433 in Envoy::HttpFilterSampleIntegrationTest_Test1_Test::TestBody() /proc/self/cwd/http-filter-example/http_filter_integration_test.cc:42:1
2020-02-09T20:09:48.3653713Z     #17 0x2e88313d in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10
2020-02-09T20:09:48.3654068Z     #18 0x2e833645 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14
2020-02-09T20:09:48.3654408Z     #19 0x2e7dee76 in testing::Test::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2508:5
2020-02-09T20:09:48.3654682Z     #20 0x2e7e1b7f in testing::TestInfo::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2684:11
2020-02-09T20:09:48.3654959Z     #21 0x2e7e42eb in testing::TestSuite::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2816:28
2020-02-09T20:09:48.3655236Z     #22 0x2e815391 in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:5338:44
2020-02-09T20:09:48.3655574Z     #23 0x2e896a9b in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2433:10
2020-02-09T20:09:48.3655982Z     #24 0x2e83e735 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:2469:14
2020-02-09T20:09:48.3656343Z     #25 0x2e8131b7 in testing::UnitTest::Run() /proc/self/cwd/external/com_google_googletest/googletest/src/gtest.cc:4925:10
2020-02-09T20:09:48.3656623Z     #26 0x27d7ec9f in RUN_ALL_TESTS() /proc/self/cwd/external/com_google_googletest/googletest/include/gtest/gtest.h:2473:46
2020-02-09T20:09:48.3656893Z     #27 0x27d7c682 in Envoy::TestRunner::RunTests(int, char**) /proc/self/cwd/external/envoy/test/test_runner.cc:121:10
2020-02-09T20:09:48.3657130Z     #28 0x27d765f2 in main /proc/self/cwd/external/envoy/test/main.cc:46:10
2020-02-09T20:09:48.3657617Z     #29 0x7fe1d86b382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
2020-02-09T20:09:48.3658242Z     #30 0x17cf7028 in _start (/b/f/w/bazel-out/k8-dbg/bin/http-filter-example/http_filter_integration_test.runfiles/envoy_filter_example/http-filter-example/http_filter_integration_test+0x17cf7028)
2020-02-09T20:09:48.3658509Z 
2020-02-09T20:09:48.3658698Z AddressSanitizer can not provide additional info.
2020-02-09T20:09:48.3659145Z SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35427) in raise
2020-02-09T20:09:48.3659446Z ==17==ABORTING
2020-02-09T20:09:48.3659647Z ================================================================================
```

**Comment by zuercher** [comment]
This is the same assertion as #9948

**Comment by zuercher** [comment]
So much the same it's a duplicate.
